<a href="https://colab.research.google.com/github/nikopaterniti98/hlt/blob/main/DataMining_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPORTS

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!unzip "/content/drive/MyDrive/DM-PRJ/gun-data.zip"

Archive:  /content/drive/MyDrive/DM-PRJ/gun-data.zip
  inflating: data/incidents.csv
  inflating: data/povertyByStateYear.csv
  inflating: data/year_state_district_house.csv

In [ ]:
!pip install geopandas

Requirement already satisfied: geopandas in /usr/local/lib/python3.10/dist-packages (0.13.2)
Requirement already satisfied: fiona>=1.8.19 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.9.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from geopandas) (23.2)
Requirement already satisfied: pandas>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.5.3)
Requirement already satisfied: pyproj>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from geopandas) (3.6.1)
Requirement already satisfied: shapely>=1.7.1 in /usr/local/lib/python3.10/dist-packages (from geopandas) (2.0.2)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (23.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (2023.7.22)
Requirement already satisfied: click~=8.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (8.1.7)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (1.1.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (0.7.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (1.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (67.7.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (1.23.5)

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sn
import scipy.stats as stats
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import geopandas as gpd

In [ ]:
df_incidents = pd.read_csv('/content/drive/MyDrive/data/incidents.csv')
df_poverty = pd.read_csv('/content/drive/MyDrive/data/povertyByStateYear.csv')
df_districts = pd.read_csv('/content/drive/MyDrive/data/year_state_district_house.csv')

pd.set_option('display.max_columns', None)

<ipython-input-5-04d2854aba99>:1: DtypeWarning: Columns (15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_incidents = pd.read_csv('/content/drive/MyDrive/data/incidents.csv')

In [ ]:
df_incidents = pd.read_csv('/content/data/incidents.csv')
df_poverty = pd.read_csv('/content/data/povertyByStateYear.csv')
df_districts = pd.read_csv('/content/data/year_state_district_house.csv')

pd.set_option('display.max_columns', None)

<ipython-input-5-cb106be66d2c>:1: DtypeWarning: Columns (15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_incidents = pd.read_csv('/content/data/incidents.csv')

In [ ]:
df_incidents.head()

,date,state,city_or_county,address,latitude,longitude,congressional_district,state_house_district,state_senate_district,participant_age1,participant_age_group1,participant_gender1,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,notes,incident_characteristics1,incident_characteristics2
0,2015-05-02,Indiana,Indianapolis,Lafayette Road and Pike Plaza,39.8322,-86.2492,7.0,94.0,33.0,19.0,Adult 18+,Male,19.0,19.0,19.0,0.0,0.0,1.0,1.0,0.0,0,1,0.0,0.0,1.0,Teen wounded while walking - Security guard at...,Shot - Wounded/Injured,NaN
1,2017-04-03,Pennsylvania,Kane,5647 US 6,41.6645,-78.7856,5.0,NaN,NaN,62.0,Adult 18+,Male,62.0,62.0,62.0,0.0,0.0,1.0,1.0,0.0,1,0,0.0,0.0,1.0,shot self after accident,"Shot - Dead (murder, accidental, suicide)",Suicide^
2,2016-11-05,Michigan,Detroit,6200 Block of East McNichols Road,42.4190,-83.0393,14.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0.0,1.0,2.0,1 inj.,Shot - Wounded/Injured,NaN
3,2016-10-15,District of Columbia,Washington,"1000 block of Bladensburg Road, NE",38.9030,-76.9820,1.0,NaN,NaN,NaN,Adult 18+,Male,248339,707477,761203,0.0,0.0,1.0,1.0,0.0,0,1,0.0,0.0,2.0,NaN,Shot - Wounded/Injured,NaN
4,2030-06-14,Pennsylvania,Pittsburgh,California and Marshall Avenues,40.4621,-80.0308,14.0,NaN,NaN,NaN,Adult 18+,Male,NaN,NaN,NaN,0.0,0.0,1.0,1.0,0.0,0,1,0.0,1.0,2.0,NaN,Shot - Wounded/Injured,"Drive-by (car to street, car to car)"

In [ ]:
df_poverty

             state  year  povertyPercentage
0    United States  2020               11.5
1          Alabama  2020               14.8
2           Alaska  2020               11.5
3          Arizona  2020               12.1
4         Arkansas  2020               15.8
..             ...   ...                ...
879       Virginia  2004                9.1
880     Washington  2004                9.8
881  West Virginia  2004               15.0
882      Wisconsin  2004               10.9
883        Wyoming  2004               10.2

[884 rows x 3 columns]

In [ ]:
df_districts

,year,state,congressional_district,party,candidatevotes,totalvotes
0,1976,ALABAMA,1,REPUBLICAN,98257,157170
1,1976,ALABAMA,2,REPUBLICAN,90069,156362
2,1976,ALABAMA,3,DEMOCRAT,106935,108048
3,1976,ALABAMA,4,DEMOCRAT,141490,176022
4,1976,ALABAMA,5,DEMOCRAT,113553,113560
...,...,...,...,...,...,...
10436,2022,WISCONSIN,5,REPUBLICAN,243741,378523
10437,2022,WISCONSIN,6,REPUBLICAN,239231,251999
10438,2022,WISCONSIN,7,REPUBLICAN,209224,338268
10439,2022,WISCONSIN,8,REPUBLICAN,223981,310196
10440,2022,WYOMING,0,REPUBLICAN,132206,198198

In [ ]:
df_incidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239677 entries, 0 to 239676
Data columns (total 28 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   date                       239677 non-null  object
 1   state                      239677 non-null  object
 2   city_or_county             239677 non-null  object
 3   address                    223180 non-null  object
 4   latitude                   231754 non-null  float64
 5   longitude                  231754 non-null  float64
 6   congressional_district     227733 non-null  float64
 7   state_house_district       200905 non-null  float64
 8   state_senate_district      207342 non-null  float64
 9   participant_age1           147379 non-null  float64
 10  participant_age_group1     197558 non-null  object
 11  participant_gender1        203315 non-null  object
 12  min_age_participants       164879 non-null  object
 13  avg_age_participants       165057 non-null  object
 14  max_age_participants       164969 non-null  object
 15  n_participants_child       197573 non-null  object
 16  n_participants_teen        197578 non-null  object
 17  n_participants_adult       197575 non-null  object
 18  n_males                    203315 non-null  float64
 19  n_females                  203315 non-null  float64
 20  n_killed                   239677 non-null  int64
 21  n_injured                  239677 non-null  int64
 22  n_arrested                 212051 non-null  float64
 23  n_unharmed                 212051 non-null  float64
 24  n_participants             239677 non-null  float64
 25  notes                      158660 non-null  object
 26  incident_characteristics1  239351 non-null  object
 27  incident_characteristics2  141931 non-null  object
dtypes: float64(11), int64(2), object(15)
memory usage: 51.2+ MB

In [ ]:
df_incidents.state.value_counts()

Illinois                17556
California              16306
Florida                 15029
Texas                   13577
Ohio                    10244
New York                 9712
Pennsylvania             8929
Georgia                  8925
North Carolina           8739
Louisiana                8103
Tennessee                7626
South Carolina           6939
Missouri                 6631
Michigan                 6136
Massachusetts            5981
Virginia                 5949
Indiana                  5852
Maryland                 5798
Alabama                  5471
New Jersey               5387
Wisconsin                4787
Kentucky                 4157
Mississippi              3599
Oklahoma                 3455
Washington               3434
Colorado                 3201
District of Columbia     3195
Connecticut              3067
Arkansas                 2842
Iowa                     2517
Minnesota                2408
Arizona                  2328
Oregon                   2286
Kansas                   2145
Nevada                   1952
Delaware                 1685
Nebraska                 1651
New Mexico               1645
West Virginia            1575
Alaska                   1349
Utah                     1072
New Hampshire             964
Maine                     907
Rhode Island              895
Idaho                     661
Montana                   638
North Dakota              573
South Dakota              544
Wyoming                   494
Vermont                   472
Hawaii                    289
Name: state, dtype: int64

sorted df is the incidents dataset sorted by state

In [ ]:
sorted_df = df_incidents.sort_values(by=['state'])
pd.set_option('display.max_columns', None)
sorted_df.head()

,date,state,city_or_county,address,latitude,longitude,congressional_district,state_house_district,state_senate_district,participant_age1,participant_age_group1,participant_gender1,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,notes,incident_characteristics1,incident_characteristics2
85693,2016-06-29,Alabama,Dothan,600 block of East Newton Street,31.2289,-85.3868,2.0,85.0,28.0,25.0,Adult 18+,Male,25.0,25.0,25.0,0.0,0.0,1.0,1.0,0.0,0,0,1.0,0.0,1.0,NaN,Shots Fired - No Injuries,"Drive-by (car to street, car to car)"
220216,2030-05-25,Alabama,Mobile,Warren and South Carolina Streets,30.6694,-88.0493,1.0,97.0,33.0,NaN,Adult 18+,Female,NaN,NaN,NaN,0.0,0.0,2.0,1.0,1.0,0,0,0.0,2.0,2.0,NaN,Non-Shooting Incident,Car-jacking
137613,2016-09-21,Alabama,Semmes,Farrington Loop,30.7366,-88.2438,1.0,102.0,34.0,39.0,Adult 18+,Male,35.0,37.0,39.0,0.0,0.0,2.0,2.0,0.0,1,0,1.0,0.0,2.0,"unspec dv, shot in chest","Shot - Dead (murder, accidental, suicide)",Domestic Violence
57191,2016-02-28,Alabama,Ashville,285 5th Avenue,33.8373,-86.2533,3.0,30.0,17.0,41.0,Adult 18+,Female,41.0,41.0,41.0,0.0,0.0,2.0,1.0,1.0,1,0,0.0,1.0,2.0,"DV, wife had restraining order against husband...","Shot - Dead (murder, accidental, suicide)",Officer Involved Incident
137577,2016-09-03,Alabama,Mobile,651 Azalea Rd.,30.6563,-88.1435,1.0,103.0,35.0,27.0,Adult 18+,Male,24.0,26.0,27.0,0.0,0.0,2.0,2.0,0.0,1,0,1.0,0.0,2.0,NaN,"Shot - Dead (murder, accidental, suicide)",NaN

In [ ]:
state_df = sorted_df[['state','city_or_county']]

In [ ]:
state_df.head()

          state city_or_county
85693   Alabama         Dothan
220216  Alabama         Mobile
137613  Alabama         Semmes
57191   Alabama       Ashville
137577  Alabama         Mobile

# INCIDENTS DATASET - STATE/CITY

In [ ]:
# UTILS
def get_stats(attribute,df):
    stats = df[attribute].describe(datetime_is_numeric=True)
    stats["missing"] = df[attribute].isna().sum()
    return stats

SUMMARY OF NULL VALUES FOR EACH ATTRIBUTE

In [ ]:
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pd.options.plotting.backend = 'plotly'
pio.templates.default = "seaborn"

x = pd.DataFrame(df_incidents.isna().sum())
x.rename(columns={0: 'Missing values'}, inplace=True)
x.index.name = 'Feature'
x.reset_index(inplace=True)
#x.set_index('Feature', inplace=True)

fig = px.bar(x, x="Feature", y="Missing values", log_y=True)

fig.update_layout(
    xaxis_dtick = 1,
    xaxis_tickangle = 45
)

fig.show()

DESCRIPTION OF MANY STATISTICS ABOUT EVERY COLUMN SUCH US THE NUMBER OF UNIQUE VALUES IN EAECH COLUMN, THE VALUE OCCURRING MORE IN EACH COLUMN,THE NUMBER OF OCCURRENCES THE TOP FEATURE HAS ECC...

In [ ]:
df_incidents.describe(include="all", datetime_is_numeric=True)

,date,state,city_or_county,address,latitude,longitude,congressional_district,state_house_district,state_senate_district,participant_age1,participant_age_group1,participant_gender1,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,notes,incident_characteristics1,incident_characteristics2
count,239677,239677,239677,223180,231754.000000,231754.000000,227733.000000,200905.000000,207342.00000,147379.000000,197558,203315,164879,165057,164969,197573,197578,197575.0,203315.000000,203315.000000,239677.000000,239677.000000,212051.000000,212051.000000,239677.000000,158660,239351,141931
unique,2437,51,12898,198037,NaN,NaN,NaN,NaN,NaN,NaN,3,3,12673,12869,12852,32,42,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136652,52,90
top,2017-01-01,Illinois,Chicago,2375 International Pkwy,NaN,NaN,NaN,NaN,NaN,NaN,Adult 18+,Male,19.0,22.0,24.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,man shot,Shot - Wounded/Injured,Officer Involved Incident
freq,342,17556,10814,160,NaN,NaN,NaN,NaN,NaN,NaN,181324,177945,7981,7606,6237,105933,104989,62938.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,501,93926,13881
mean,NaN,NaN,NaN,NaN,37.546598,-89.338348,8.001265,55.447132,20.47711,30.295707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.520252,0.212340,0.252290,0.494007,0.468439,0.494169,1.636895,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,5.130763,14.359546,8.480835,42.048117,14.20456,13.363592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.996767,0.490888,0.521779,0.729952,0.851035,0.925566,1.252514,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,19.111400,-171.429000,0.000000,1.000000,1.00000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,33.903400,-94.158725,2.000000,21.000000,9.00000,21.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,38.570600,-86.249600,5.000000,47.000000,19.00000,27.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,41.437375,-80.048625,10.000000,84.000000,30.00000,37.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,0.000000,0.000000,1.000000,1.000000,1.000000,2.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,71.336800,97.433100,53.000000,901.000000,94.00000,311.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.000000,23.000000,50.000000,53.000000,63.000000,20.000000,103.000000,NaN,NaN,NaN

THE GET STATS FUNCTION EXTRACTS SOME INFORMATIONS ABOUT A SPECIFIC COLUMN OF THE DATAFRAME

In [ ]:
print(get_stats("state", df_incidents))

count        239677
unique           51
top        Illinois
freq          17556
missing           0
Name: state, dtype: object

NUMBER OF INCIDENTS FOR EACH STATE

In [ ]:
incident_number = state_df['state'].value_counts()
incident_number.plot(kind='bar')

Here we can find the number of incidents sorted in descending order, starting by the city with the highest number of crimes which is Chicago, obviously in Illinois which we found to be the state with the most crimes

In [ ]:
city_counts = state_df.groupby(['state', 'city_or_county']).size().reset_index(name='incident_count')
city_counts.sort_values(by=['incident_count'],ascending=False)

                      state city_or_county  incident_count
4070               Illinois        Chicago           10814
6592               Maryland      Baltimore            3943
2524   District of Columbia     Washington            3189
6191              Louisiana    New Orleans            3070
13500          Pennsylvania   Philadelphia            2929
...                     ...            ...             ...
8387            Mississippi        Russell               1
8388            Mississippi         Sallis               1
8390            Mississippi     Sandy Hook               1
8393            Mississippi         Scooba               1
17540               Wyoming         Wright               1

[17541 rows x 3 columns]

In [ ]:
df_incidents['state'] = df_incidents['state'].str.upper()

In [ ]:
# Dizionario dei codici statali
state_abbreviations = {
    'ALABAMA': 'AL', 'ALASKA': 'AK', 'ARIZONA': 'AZ', 'ARKANSAS': 'AR',
    'CALIFORNIA': 'CA', 'COLORADO': 'CO', 'CONNECTICUT': 'CT', 'DELAWARE': 'DE',
    'FLORIDA': 'FL', 'GEORGIA': 'GA', 'HAWAII': 'HI', 'IDAHO': 'ID',
    'ILLINOIS': 'IL', 'INDIANA': 'IN', 'IOWA': 'IA', 'KANSAS': 'KS',
    'KENTUCKY': 'KY', 'LOUISIANA': 'LA', 'MAINE': 'ME', 'MARYLAND': 'MD',
    'MASSACHUSETTS': 'MA', 'MICHIGAN': 'MI', 'MINNESOTA': 'MN', 'MISSISSIPI': 'MS',
    'MISSOURI': 'MO', 'MONTANA': 'MT', 'NEBRASKA': 'NE', 'NEVADA': 'NV',
    'NEW HAMPSHIRE': 'NH', 'NEW JERSEY': 'NJ', 'NEW MEXICO': 'NM', 'NEW YORK': 'NY',
    'NORTH CAROLINA': 'NC', 'NORTH DAKOTA': 'ND', 'OHIO': 'OH', 'OKLAHOMA': 'OK',
    'OREGON': 'OR', 'PENNSYLVANIA': 'PA', 'RHODE ISLAND': 'RI', 'SOUTH CAROLINA': 'SC',
    'SOUTH DAKOTA': 'SD', 'TENNESSEE': 'TN', 'TEXAS': 'TX', 'UTAH': 'UT',
    'VERMONT': 'VT', 'VIRGINIA': 'VA', 'WASHINGTON': 'WA', 'WEST VIRGINIA': 'WV',
    'WISCONSIN': 'WI', 'WYOMING': 'WY'
}

# Aggiungere la colonna con i codici statali usando il dizionario per la mappatura
df_incidents['state_code'] = df_incidents['state'].map(state_abbreviations)

In [ ]:
state_counts = df_incidents['state'].value_counts().reset_index()
state_counts.columns = ['state','Incident Count']
state_counts['state_code'] = state_counts['state'].map(state_abbreviations)
state_counts

                   state  Incident Count state_code
0               ILLINOIS           17556         IL
1             CALIFORNIA           16306         CA
2                FLORIDA           15029         FL
3                  TEXAS           13577         TX
4                   OHIO           10244         OH
5               NEW YORK            9712         NY
6           PENNSYLVANIA            8929         PA
7                GEORGIA            8925         GA
8         NORTH CAROLINA            8739         NC
9              LOUISIANA            8103         LA
10             TENNESSEE            7626         TN
11        SOUTH CAROLINA            6939         SC
12              MISSOURI            6631         MO
13              MICHIGAN            6136         MI
14         MASSACHUSETTS            5981         MA
15              VIRGINIA            5949         VA
16               INDIANA            5852         IN
17              MARYLAND            5798         MD
18               ALABAMA            5471         AL
19            NEW JERSEY            5387         NJ
20             WISCONSIN            4787         WI
21              KENTUCKY            4157         KY
22           MISSISSIPPI            3599        NaN
23              OKLAHOMA            3455         OK
24            WASHINGTON            3434         WA
25              COLORADO            3201         CO
26  DISTRICT OF COLUMBIA            3195        NaN
27           CONNECTICUT            3067         CT
28              ARKANSAS            2842         AR
29                  IOWA            2517         IA
30             MINNESOTA            2408         MN
31               ARIZONA            2328         AZ
32                OREGON            2286         OR
33                KANSAS            2145         KS
34                NEVADA            1952         NV
35              DELAWARE            1685         DE
36              NEBRASKA            1651         NE
37            NEW MEXICO            1645         NM
38         WEST VIRGINIA            1575         WV
39                ALASKA            1349         AK
40                  UTAH            1072         UT
41         NEW HAMPSHIRE             964         NH
42                 MAINE             907         ME
43          RHODE ISLAND             895         RI
44                 IDAHO             661         ID
45               MONTANA             638         MT
46          NORTH DAKOTA             573         ND
47          SOUTH DAKOTA             544         SD
48               WYOMING             494         WY
49               VERMONT             472         VT
50                HAWAII             289         HI

In [ ]:
import plotly.express as px
import pandas as pd


# Load the USA map from Plotly
fig = px.choropleth(
    state_counts,
    locations='state_code',
    locationmode='USA-states',
    color='Incident Count',
    scope="usa",
    color_continuous_scale="Blues",
    title='Distribution of Incidents by State'
)

# Show the plot
fig.show()

# INCIDENTS DATASET - DISTRICT

In [ ]:
district_df = sorted_df[['state','city_or_county','congressional_district','state_house_district','state_senate_district']]
district_df.head()

,state,city_or_county,congressional_district,state_house_district,state_senate_district
85693,Alabama,Dothan,2.0,85.0,28.0
220216,Alabama,Mobile,1.0,97.0,33.0
137613,Alabama,Semmes,1.0,102.0,34.0
57191,Alabama,Ashville,3.0,30.0,17.0
137577,Alabama,Mobile,1.0,103.0,35.0

INFO ABOUT THE DISTRICTS THE INCIDENT TOOK PLACE IN

In [ ]:
district_counts = district_df.groupby(['state',
                                       'city_or_county',
                                       'congressional_district',
                                       'state_house_district',
                                       'state_senate_district']).size().reset_index(name='incident_count')

temp = district_counts.sort_values(by=['incident_count'],ascending=False)

In [ ]:
Illinois_districts = district_counts[district_counts['state'] == 'Illinois']
Illinois_districts.sort_values(by=['incident_count'],ascending=False)

,state,city_or_county,congressional_district,state_house_district,state_senate_district,incident_count
7556,Illinois,Chicago,7.0,10.0,5.0,1225
7555,Illinois,Chicago,7.0,9.0,5.0,879
8072,Illinois,Peoria,17.0,92.0,46.0,805
7554,Illinois,Chicago,7.0,8.0,4.0,690
8128,Illinois,Rockford,17.0,67.0,34.0,646
...,...,...,...,...,...,...
7811,Illinois,Hanna City,18.0,73.0,37.0,1
7810,Illinois,Hancock (county),18.0,94.0,47.0,1
7809,Illinois,Hamilton,18.0,94.0,47.0,1
7808,Illinois,Gurnee,14.0,61.0,31.0,1
7815,Illinois,Hardin County,15.0,118.0,59.0,1

In [ ]:
chicago_districts = district_counts[district_counts['city_or_county'] == 'Chicago']
chicago_districts.sort_values(by=['incident_count'],ascending=False)

,state,city_or_county,congressional_district,state_house_district,state_senate_district,incident_count
7556,Illinois,Chicago,7.0,10.0,5.0,1225
7555,Illinois,Chicago,7.0,9.0,5.0,879
7554,Illinois,Chicago,7.0,8.0,4.0,690
7552,Illinois,Chicago,7.0,6.0,3.0,576
7487,Illinois,Chicago,1.0,31.0,16.0,419
...,...,...,...,...,...,...
7523,Illinois,Chicago,4.0,19.0,10.0,1
7530,Illinois,Chicago,4.0,77.0,39.0,1
7534,Illinois,Chicago,5.0,9.0,5.0,1
7545,Illinois,Chicago,5.0,78.0,39.0,1
7573,Illinois,Chicago,15.0,106.0,53.0,1

In [ ]:
congressionaldistrict_occurrences = df_incidents['congressional_district'].value_counts()
pd.set_option('display.max_rows', None)

print(congressionaldistrict_occurrences)

1.0     36910
2.0     26945
3.0     20621
7.0     19709
4.0     18469
5.0     16512
9.0      9867
6.0      9388
8.0      7353
13.0     6175
12.0     5770
10.0     5606
11.0     5260
14.0     4291
17.0     2925
16.0     2842
18.0     2614
20.0     2600
24.0     2042
15.0     1943
26.0     1847
19.0     1701
27.0     1425
22.0     1424
25.0     1354
23.0     1305
21.0     1276
35.0     1135
30.0      788
31.0      773
29.0      727
36.0      659
33.0      522
28.0      497
0.0       421
44.0      421
32.0      361
34.0      337
43.0      314
47.0      292
37.0      266
46.0      251
38.0      249
40.0      235
51.0      228
41.0      211
52.0      158
53.0      130
48.0      119
42.0      118
50.0      116
49.0      100
39.0       86
45.0       45
Name: congressional_district, dtype: int64

# INCIDENTS CHARATERISTICS

In [ ]:
unique_dates = df_incidents['date'].unique()
print(unique_dates)

['2015-05-02' '2017-04-03' '2016-11-05' ... '2013-07-24' '2013-12-14'
 '2013-04-18']

TRANSFORM YEARS 2030, 2029, 2028 IN 2020, 2019, 2018

In [ ]:
import pandas as pd

# Assuming your dataframe is named 'df' and the date column is named 'date_column'
df_incidents['date'] = pd.to_datetime(df_incidents['date'])

# Replace years 2030, 2029, 2028 with 2020, 2019, 2018 respectively
df_incidents['date'] = df_incidents['date'].apply(lambda x: x.replace(year=x.year - 10) if x.year in [2030, 2029, 2028] else x)

print("Highest Date:", df_incidents['date'].max())
print("Lowest Date:", df_incidents['date'].min())

Highest Date: 2020-11-28 00:00:00
Lowest Date: 2013-01-01 00:00:00

NUMBER OF INCIDENTS FOR EACH DATE

In [ ]:
#Comment the first row and uncomment the second if you want to keep the day in the dates

df_incidents['date'] = pd.to_datetime(df_incidents['date']).dt.to_period('M')
#df_incidents['date'] = pd.to_datetime(df_incidents['date'])
date_occurrences = df_incidents['date'].value_counts()
pd.set_option('display.max_rows', None)

print(date_occurrences)

2017-05    5666
2017-04    5577
2017-07    5547
2016-08    5527
2017-01    5258
2016-10    5251
2016-07    5250
2017-08    5202
2017-10    5200
2017-06    5158
2016-12    5153
2016-11    5092
2017-03    4994
2016-09    4937
2018-01    4928
2016-05    4902
2016-03    4892
2017-11    4802
2017-09    4790
2018-03    4753
2016-04    4672
2017-12    4622
2016-01    4590
2017-02    4585
2016-06    4530
2015-12    4422
2015-07    4190
2015-08    4187
2018-02    4125
2015-09    4067
2015-05    3991
2016-02    3967
2014-08    3942
2015-06    3755
2015-10    3733
2014-07    3722
2014-09    3699
2015-04    3594
2015-11    3589
2014-10    3577
2015-03    3520
2015-01    3183
2014-12    3157
2014-01    3068
2014-06    3046
2014-05    3013
2014-11    2894
2014-04    2727
2014-03    2639
2015-02    2519
2014-02    2193
2019-07    1495
2019-06    1377
2019-09    1376
2019-05    1366
2019-01    1295
2019-08    1286
2019-10    1274
2019-04    1159
2019-03    1069
2020-05    1033
2020-07     920
2019-11     872
2020-04     845
2020-06     838
2019-02     832
2020-03     829
2020-08     795
2020-09     784
2020-10     777
2019-12     706
2020-01     705
2020-02     602
2020-11     601
2018-12     170
2013-07      33
2013-06      27
2013-09      27
2013-08      26
2013-12      22
2013-11      22
2013-05      21
2013-10      18
2013-03      18
2013-04      15
2013-01      13
2013-02      11
2018-05       9
2018-10       4
2018-08       2
2018-04       2
2018-11       1
2018-09       1
2018-07       1
2018-06       1
Freq: M, Name: date, dtype: int64

  NUMBER OF INCIDENTS FOR EACH PARTICIPANT AGE

In [ ]:
participant_age1_occurrences = df_incidents['participant_age1'].value_counts()
pd.set_option('display.max_rows', None)

print(participant_age1_occurrences)

19.0     6842
20.0     6574
22.0     6552
21.0     6513
18.0     6483
23.0     6466
24.0     6394
25.0     5964
26.0     5529
27.0     5112
17.0     4693
28.0     4603
29.0     4355
30.0     4090
31.0     3754
32.0     3694
33.0     3494
34.0     3310
16.0     3228
35.0     3203
36.0     2753
37.0     2649
38.0     2381
39.0     2084
40.0     2075
15.0     2047
41.0     1751
42.0     1626
43.0     1615
44.0     1526
45.0     1477
46.0     1307
47.0     1260
48.0     1252
14.0     1203
50.0     1160
49.0     1125
52.0     1052
51.0     1043
53.0      967
54.0      928
55.0      887
56.0      782
57.0      726
13.0      704
58.0      644
60.0      617
59.0      612
61.0      531
62.0      484
63.0      417
12.0      379
65.0      357
64.0      341
3.0       305
67.0      304
66.0      296
68.0      271
11.0      268
4.0       258
71.0      250
70.0      249
10.0      235
69.0      234
2.0       232
7.0       220
9.0       214
5.0       210
8.0       208
6.0       188
72.0      163
73.0      157
74.0      156
1.0       147
75.0      145
76.0      129
77.0      109
80.0       96
79.0       88
81.0       81
78.0       75
83.0       63
82.0       61
84.0       52
0.0        50
85.0       44
86.0       35
88.0       33
87.0       33
89.0       28
90.0       22
92.0       14
91.0       10
94.0        9
93.0        6
95.0        5
96.0        4
101.0       2
99.0        1
100.0       1
209.0       1
97.0        1
311.0       1
Name: participant_age1, dtype: int64

INCIDENTS CHARATERISTICS1

In [ ]:
nunique_values = df_incidents['incident_characteristics1'].nunique()
incidents_occurrences = df_incidents['incident_characteristics1'].value_counts()

print(f'There are {nunique_values} possible values')
print('//////////////////////////////////////////////////////////////////////////////////')
print(incidents_occurrences)

There are 52 possible values
//////////////////////////////////////////////////////////////////////////////////
Shot - Wounded/Injured                                                                                  93926
Shot - Dead (murder, accidental, suicide)                                                               45054
Non-Shooting Incident                                                                                   41541
Shots Fired - No Injuries                                                                               33949
Armed robbery with injury/death and/or evidence of DGU found                                             7528
Institution/Group/Business                                                                               4316
TSA Action                                                                                               2653
Brandishing/flourishing/open carry/lost/found                                                            1350
Home Invasion                                                                                            1323
Possession (gun(s) found during commission of other crimes)                                              1310
Drug involvement                                                                                         1005
Shots fired, no action (reported, no evidence found)                                                      961
Gun(s) stolen from owner                                                                                  834
Officer Involved Incident                                                                                 692
ATF/LE Confiscation/Raid/Arrest                                                                           450
Car-jacking                                                                                               389
Animal shot/killed                                                                                        309
Domestic Violence                                                                                         234
Accidental Shooting                                                                                       229
Gang involvement                                                                                          177
School Incident                                                                                           118
Sex crime involving firearm                                                                               103
Kidnapping/abductions/hostage                                                                              95
Drive-by (car to street, car to car)                                                                       89
Implied Weapon                                                                                             88
Pistol-whipping                                                                                            87
Suicide - Attempt                                                                                          77
Possession of gun by felon or prohibited person                                                            63
Gun buy back action                                                                                        58
Non-Aggression Incident                                                                                    51
Defensive Use                                                                                              50
Suicide^                                                                                                   34
Criminal act with stolen gun                                                                               30
Road rage                                                                                                  28
Gun at school, no death/injury - elementary/secondary school                                               25
Murder/Suicide                                                                                             24
Bar/club incident - in or around establishment                                                             23
LOCKDOWN/ALERT ONLY: No GV Incident Occurred Onsite                                                        13
Guns stolen from law enforcement                                                                           10
Stolen/Illegally owned gun{s} recovered during arrest/warrant                                               8
Attempted Murder/Suicide (one variable unsuccessful)                                                        7
BB/Pellet/Replica gun                                                                                       6
Under the influence of alcohol or drugs (only applies to the subject/suspect/perpetrator )                  6
Gun shop robbery or burglary                                                                                5
ShotSpotter                                                                                                 5
Child Involved Incident                                                                                     4
Spree Shooting (multiple victims, multiple locations)                                                       4
Hate crime                                                                                                  4
House party                                                                                                 3
Mass Shooting (4+ victims injured or killed excluding the subject/suspect/perpetrator, one location)        1
Unlawful purchase/sale                                                                                      1
Gun range/gun shop/gun show shooting                                                                        1
Name: incident_characteristics1, dtype: int64

INCIDENTS CHARATERISTICS2

In [ ]:
nunique_values = df_incidents['incident_characteristics2'].nunique()
incidents_occurrences2 = df_incidents['incident_characteristics2'].value_counts()

print(f'There are {nunique_values} possible values')
print('//////////////////////////////////////////////////////////////////////////////////')
pd.set_option('display.max_rows', None)
print(incidents_occurrences2)

There are 90 possible values
//////////////////////////////////////////////////////////////////////////////////
Officer Involved Incident                                                                               13881
Drive-by (car to street, car to car)                                                                    11873
Drug involvement                                                                                        11717
Home Invasion                                                                                            8664
Shot - Dead (murder, accidental, suicide)                                                                8345
Armed robbery with injury/death and/or evidence of DGU found                                             6438
Possession (gun(s) found during commission of other crimes)                                              6084
ATF/LE Confiscation/Raid/Arrest                                                                          5916
Accidental Shooting                                                                                      5723
Domestic Violence                                                                                        5690
Institution/Group/Business                                                                               5315
Suicide^                                                                                                 4680
Brandishing/flourishing/open carry/lost/found                                                            4181
Gang involvement                                                                                         3712
Non-Shooting Incident                                                                                    3267
Defensive Use                                                                                            3146
Gun(s) stolen from owner                                                                                 2977
Car-jacking                                                                                              2948
Non-Aggression Incident                                                                                  2736
Bar/club incident - in or around establishment                                                           2722
TSA Action                                                                                               2357
Possession of gun by felon or prohibited person                                                          2352
Shots Fired - No Injuries                                                                                1760
School Incident                                                                                          1436
Road rage                                                                                                1360
Under the influence of alcohol or drugs (only applies to the subject/suspect/perpetrator )               1116
Home Invasion - No death or injury                                                                        918
Child Involved Incident                                                                                   844
Kidnapping/abductions/hostage                                                                             822
Shots fired, no action (reported, no evidence found)                                                      785
Pistol-whipping                                                                                           745
Implied Weapon                                                                                            639
ShotSpotter                                                                                               581
LOCKDOWN/ALERT ONLY: No GV Incident Occurred Onsite                                                       566
Mass Shooting (4+ victims injured or killed excluding the subject/suspect/perpetrator, one location)      560
Shootout (where VENN diagram of shooters and victims overlap)                                             558
House party                                                                                               494
Criminal act with stolen gun                                                                              414
Suicide - Attempt                                                                                         386
BB/Pellet/Replica gun                                                                                     379
Sex crime involving firearm                                                                               334
Officer Involved Incident - Weapon involved but no shots fired                                            317
Home Invasion - Resident injured                                                                          232
Stolen/Illegally owned gun{s} recovered during arrest/warrant                                             180
Animal shot/killed                                                                                        171
Assault weapon (AR-15, AK-47, and ALL variants defined by law enforcement)                                151
Gun shop robbery or burglary                                                                              136
Spree Shooting (multiple victims, multiple locations)                                                     135
Gun at school, no death/injury - elementary/secondary school                                              114
Officer Involved Shooting - subject/suspect/perpetrator killed                                            108
Accidental/Negligent Discharge                                                                             98
Murder/Suicide                                                                                             86
Officer Involved Shooting - subject/suspect/perpetrator shot                                               84
Guns stolen from law enforcement                                                                           83
Accidental Shooting - Injury                                                                               76
Unlawful purchase/sale                                                                                     74
Concealed Carry License - Perpetrator                                                                      60
Hate crime                                                                                                 51
Accidental Shooting - Death                                                                                50
Workplace shooting (disgruntled employee)                                                                  41
Gun range/gun shop/gun show shooting                                                                       37
Gun buy back action                                                                                        30
Mass Murder (4+ deceased victims excluding the subject/suspect/perpetrator , one location)                 24
Officer Involved Shooting - Officer shot                                                                   20
Home Invasion - subject/suspect/perpetrator injured                                                        19
Concealed Carry License - Victim                                                                           15
Home Invasion - Resident killed                                                                            15
Attempted Murder/Suicide (one variable unsuccessful)                                                       15
Gun at school, no death/injury - university/college                                                        15
Terrorism Involvement                                                                                      11
Defensive Use - Victim stops crime                                                                          8
Home Invasion - subject/suspect/perpetrator killed                                                          8
Ghost gun                                                                                                   7
Officer Involved Shooting - Shots fired, no injury                                                          7
Defensive Use - WITHOUT a gun                                                                               5
Officer Involved Shooting - subject/suspect/perpetrator surrender at standoff                               4
Political Violence                                                                                          4
Officer Involved Shooting - subject/suspect/perpetrator suicide at standoff                                 3
Child picked up & fired gun                                                                                 3
Accidental Shooting at a Business                                                                           2
Defensive Use - Shots fired, no injury/death                                                                2
School Shooting - elementary/secondary school                                                               1
Police Targeted                                                                                             1
Officer Involved Shooting - subject/suspect/perpetrator unarmed                                             1
Officer Involved Shooting - Accidental discharge - no injury required                                       1
Cleaning gun                                                                                                1
Child with gun - no shots fired                                                                             1
Defensive Use - Crime occurs, victim shoots subject/suspect/perpetrator                                     1
Officer Involved Shooting - Officer killed                                                                  1
Hunting accident                                                                                            1
Name: incident_characteristics2, dtype: int64

# YEAR DISTRICT HOUSE DATASET

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sn
import scipy.stats as stats
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import geopandas as gpd

In [ ]:
df = pd.read_csv('/content/data/year_state_district_house.csv')

FileNotFoundError: ignored

In [ ]:
df.info()

NameError: ignored

In [ ]:
print(df['party'].unique())
print(df['year'].unique())
print(df['congressional_district'].unique())

['REPUBLICAN' 'DEMOCRAT' 'FOGLIETTA (DEMOCRAT)' 'DEMOCRATIC-FARMER-LABOR'
 'INDEPENDENT' 'INDEPENDENT-REPUBLICAN']
[1976 1978 1980 1982 1984 1986 1988 1990 1992 1994 1996 1998 2000 2002
 2004 2006 2008 2010 2012 2014 2016 2018 2020 2022]
[ 1  2  3  4  5  6  7  0  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53]

In [ ]:
unique_state = df['state'].unique()
total_state = df['state'].count()

print(len(unique_state))
#verificare se gli stati unici sono correttamente tutti stati americani
print(unique_state)
print(total_state)

51
['ALABAMA' 'ALASKA' 'ARIZONA' 'ARKANSAS' 'CALIFORNIA' 'COLORADO'
 'CONNECTICUT' 'DELAWARE' 'FLORIDA' 'GEORGIA' 'HAWAII' 'IDAHO' 'ILLINOIS'
 'INDIANA' 'IOWA' 'KANSAS' 'KENTUCKY' 'LOUISIANA' 'MAINE' 'MARYLAND'
 'MASSACHUSETTS' 'MICHIGAN' 'MINNESOTA' 'MISSISSIPPI' 'MISSOURI' 'MONTANA'
 'NEBRASKA' 'NEVADA' 'NEW HAMPSHIRE' 'NEW JERSEY' 'NEW MEXICO' 'NEW YORK'
 'NORTH CAROLINA' 'NORTH DAKOTA' 'OHIO' 'OKLAHOMA' 'OREGON' 'PENNSYLVANIA'
 'RHODE ISLAND' 'SOUTH CAROLINA' 'SOUTH DAKOTA' 'TENNESSEE' 'TEXAS' 'UTAH'
 'VERMONT' 'VIRGINIA' 'WASHINGTON' 'WEST VIRGINIA' 'WISCONSIN' 'WYOMING'
 'DISTRICT OF COLUMBIA']
10441

In [ ]:
def is_us_state(input_string):
    us_states = {
        'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
        'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
        'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
        'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
        'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
        'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
        'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
        'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
        'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
        'West Virginia', 'Wisconsin', 'Wyoming'
    }
    return input_string in us_states

In [ ]:
#verificare se il numero di voti è maggiore del totale voti

# df_filtered = df.query('party in ("FOGLIETTA (DEMOCRAT)","INDEPENDENT-REPUBLICAN", "INDEPENDENT")')

# df_filtered

df_state_filtered = df.query('state == "DISTRICT OF COLUMBIA"')

df_state_filtered
filtro = df['state'] == 'DISTRICT OF COLUMBIA'

df = df[~filtro]
df
unique_state = df['state'].unique()
print (len(unique_state))

50

In [ ]:
df_filtered = df.query('party == "INDEPENDENT"')
print (len(df_filtered))
print (df_filtered)

10
      year     state  congressional_district        party  candidatevotes  \
3447  1990   VERMONT                       0  INDEPENDENT          117522
3881  1992   VERMONT                       0  INDEPENDENT          162724
4316  1994   VERMONT                       0  INDEPENDENT          105502
4579  1996  MISSOURI                       8  INDEPENDENT          112472
4751  1996   VERMONT                       0  INDEPENDENT          140678
5186  1998   VERMONT                       0  INDEPENDENT          136403
5621  2000   VERMONT                       0  INDEPENDENT          196118
5626  2000  VIRGINIA                       5  INDEPENDENT          143312
6057  2002   VERMONT                       0  INDEPENDENT          144880
6492  2004   VERMONT                       0  INDEPENDENT          205774

      totalvotes
3447      209856
3881      281162
4316      211449
4579      222854
4751      254706
5186      215133
5621      283366
5626      212705
6057      225255
6492      305008

In [ ]:
# unire i dati dei partiti minoritari oppure non considerarli
df_filtered = df.query('congressional_district== 7 and state =="ILLINOIS"')
df_filtered

#calcolare il partito vincente per anno

,year,state,congressional_district,party,candidatevotes,totalvotes
106,1976,ILLINOIS,7,DEMOCRAT,88239,104094
541,1978,ILLINOIS,7,DEMOCRAT,64716,74989
976,1980,ILLINOIS,7,DEMOCRAT,80056,94097
1419,1982,ILLINOIS,7,DEMOCRAT,133978,154974
1854,1984,ILLINOIS,7,DEMOCRAT,135493,172908
2289,1986,ILLINOIS,7,DEMOCRAT,90761,113164
2724,1988,ILLINOIS,7,DEMOCRAT,135331,135331
3159,1990,ILLINOIS,7,DEMOCRAT,80021,100120
3607,1992,ILLINOIS,7,DEMOCRAT,182811,225281
4042,1994,ILLINOIS,7,DEMOCRAT,93457,117468
4477,1996,ILLINOIS,7,DEMOCRAT,149568,181095
4912,1998,ILLINOIS,7,DEMOCRAT,130984,140968
5347,2000,ILLINOIS,7,DEMOCRAT,164155,191027
5789,2002,ILLINOIS,7,DEMOCRAT,137933,165756
6224,2004,ILLINOIS,7,DEMOCRAT,221133,256736
6659,2006,ILLINOIS,7,DEMOCRAT,143071,165011
7094,2008,ILLINOIS,7,DEMOCRAT,235343,276817
7529,2010,ILLINOIS,7,DEMOCRAT,149846,183849
7968,2012,ILLINOIS,7,DEMOCRAT,242439,286435
8403,2014,ILLINOIS,7,DEMOCRAT,155110,182278
8838,2016,ILLINOIS,7,DEMOCRAT,250584,297466
9273,2018,ILLINOIS,7,DEMOCRAT,215746,246243
9709,2020,ILLINOIS,7,DEMOCRAT,249383,310128
10145,2022,ILLINOIS,7,DEMOCRAT,167650,167746

In [ ]:
import plotly.express as px
import pandas as pd
import matplotlib
import geopandas as gpd

df = pd.read_csv('/content/data/year_state_district_house.csv')

# Dizionario dei codici statali
state_abbreviations = {
    'ALABAMA': 'AL', 'ALASKA': 'AK', 'ARIZONA': 'AZ', 'ARKANSAS': 'AR',
    'CALIFORNIA': 'CA', 'COLORADO': 'CO', 'CONNECTICUT': 'CT', 'DELAWARE': 'DE',
    'FLORIDA': 'FL', 'GEORGIA': 'GA', 'HAWAII': 'HI', 'IDAHO': 'ID',
    'ILLINOIS': 'IL', 'INDIANA': 'IN', 'IOWA': 'IA', 'KANSAS': 'KS',
    'KENTUCKY': 'KY', 'LOUISIANA': 'LA', 'MAINE': 'ME', 'MARYLAND': 'MD',
    'MASSACHUSETTS': 'MA', 'MICHIGAN': 'MI', 'MINNESOTA': 'MN', 'MISSISSIPI': 'MS',
    'MISSOURI': 'MO', 'MONTANA': 'MT', 'NEBRASKA': 'NE', 'NEVADA': 'NV',
    'NEW HAMPSHIRE': 'NH', 'NEW JERSEY': 'NJ', 'NEW MEXICO': 'NM', 'NEW YORK': 'NY',
    'NORTH CAROLINA': 'NC', 'NORTH DAKOTA': 'ND', 'OHIO': 'OH', 'OKLAHOMA': 'OK',
    'OREGON': 'OR', 'PENNSYLVANIA': 'PA', 'RHODE ISLAND': 'RI', 'SOUTH CAROLINA': 'SC',
    'SOUTH DAKOTA': 'SD', 'TENNESSEE': 'TN', 'TEXAS': 'TX', 'UTAH': 'UT',
    'VERMONT': 'VT', 'VIRGINIA': 'VA', 'WASHINGTON': 'WA', 'WEST VIRGINIA': 'WV',
    'WISCONSIN': 'WI', 'WYOMING': 'WY'
}

# Aggiungere la colonna con i codici statali usando il dizionario per la mappatura
df['state_code'] = df['state'].map(state_abbreviations)

# Raggruppiamo per anno e partito e sommiamo i voti
votes_per_year_party = df.groupby(['year', 'state_code','party'])['candidatevotes'].sum().reset_index()

# Calcoliamo il totale dei voti per anno
total_votes_per_year = df.groupby('year')['candidatevotes'].sum().reset_index()

# Merge the total votes back to our votes_per_year_party dataframe
votes_per_year_party = votes_per_year_party.merge(total_votes_per_year, on='year', suffixes=('', '_total'))

# Calcoliamo la percentuale dei voti per partito per anno
votes_per_year_party['percentage_of_votes'] = (votes_per_year_party['candidatevotes'] / votes_per_year_party['candidatevotes_total']) * 100

# Ordiniamo i risultati per anno e poi per percentuale di voti in ordine decrescente
votes_per_year_party.sort_values(by=['year', 'percentage_of_votes'], ascending=[True, False], inplace=True)

# Selezioniamo solo le colonne d'interesse per una presentazione più pulita
votes_per_year_party = votes_per_year_party[['year', 'state_code', 'party', 'candidatevotes']]

print(votes_per_year_party)


# Assuming your state column is named 'state'
#state_counts = votes_per_year_party[votes_per_year_party['year'] == '1976']

#state_counts.columns = ['State', 'candidatevotes']

# Load the USA map from Plotly
fig = px.choropleth(
    votes_per_year_party,
    locations='state_code',
    locationmode='USA-states',
    color='candidatevotes',
    hover_name='state_code',   # Colonna per i dettagli al passaggio del mouse
    hover_data={"year": True, "party": True, "candidatevotes": True, "state_code": False},
    scope="usa",
    color_continuous_scale="Blues",
    title='Distribution of Votes by State'
)

# Aggiungere il menu a tendina per selezionare il partito
fig.update_layout(
    updatemenus=[
        dict(
            buttons=list([
                dict(
                    args=[{"z": [votes_per_year_party.loc[votes_per_year_party['party'] == party, 'candidatevotes']]}],
                    label=party,
                    method="restyle"
                ) for party in votes_per_year_party['party'].unique()
            ]),
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=0.1,
            xanchor="left",
            y=1.15,
            yanchor="top"
        ),
    ]
)

# Aggiungere uno slider per l'animazione
fig.update_layout(
    sliders=[{
        'steps': [{
            'method': 'animate',
            'label': str(year),
            'args': [[year], {'frame': {'duration': 300, 'redraw': True}, 'mode': 'immediate'}]
        } for year in votes_per_year_party['year'].unique()]
    }]
)

# Show the plot
fig.show()

      year state_code                    party  candidatevotes
7     1976         CA                 DEMOCRAT         3070977
56    1976         NY                 DEMOCRAT         2438279
71    1976         TX                 DEMOCRAT         2308473
63    1976         PA                 DEMOCRAT         1910292
8     1976         CA               REPUBLICAN         1768211
22    1976         IL               REPUBLICAN         1514098
21    1976         IL                 DEMOCRAT         1456808
59    1976         OH               REPUBLICAN         1435337
31    1976         MA                 DEMOCRAT         1431340
57    1976         NY               REPUBLICAN         1336759
51    1976         NJ                 DEMOCRAT         1250095
36    1976         MI                 DEMOCRAT         1230016
58    1976         OH                 DEMOCRAT         1066017
80    1976         WI                 DEMOCRAT         1024866
64    1976         PA               REPUBLICAN          956269
16    1976         GA                 DEMOCRAT          929829
37    1976         MI               REPUBLICAN          928206
23    1976         IN                 DEMOCRAT          921845
40    1976         MO                 DEMOCRAT          915204
44    1976         NC                 DEMOCRAT          872593
38    1976         MN                 DEMOCRAT          799837
78    1976         WA                 DEMOCRAT          759942
14    1976         FL                 DEMOCRAT          736913
15    1976         FL               REPUBLICAN          691792
60    1976         OK                 DEMOCRAT          608541
62    1976         OR                 DEMOCRAT          599135
69    1976         TN                 DEMOCRAT          571461
33    1976         MD                 DEMOCRAT          545838
29    1976         LA                 DEMOCRAT          531158
76    1976         VA               REPUBLICAN          528055
11    1976         CT                 DEMOCRAT          527700
18    1976         IA                 DEMOCRAT          517430
52    1976         NJ               REPUBLICAN          508150
27    1976         KY                 DEMOCRAT          479543
1     1976         AL                 DEMOCRAT          472474
39    1976         MN               REPUBLICAN          455512
82    1976         WV                 DEMOCRAT          455172
66    1976         SC                 DEMOCRAT          441341
75    1976         VA                 DEMOCRAT          417038
26    1976         KS               REPUBLICAN          375462
24    1976         IN               REPUBLICAN          364961
72    1976         TX               REPUBLICAN          364470
70    1976         TN               REPUBLICAN          331942
35    1976         ME               REPUBLICAN          314815
32    1976         MA               REPUBLICAN          314256
9     1976         CO                 DEMOCRAT          313679
81    1976         WI               REPUBLICAN          303332
48    1976         NE               REPUBLICAN          297278
34    1976         MD               REPUBLICAN          292351
12    1976         CT               REPUBLICAN          283323
2     1976         AL               REPUBLICAN          280439
65    1976         RI                 DEMOCRAT          271127
3     1976         AR                 DEMOCRAT          260998
41    1976         MO               REPUBLICAN          254625
10    1976         CO               REPUBLICAN          246242
19    1976         IA               REPUBLICAN          227651
68    1976         SD               REPUBLICAN          221188
30    1976         LA               REPUBLICAN          208915
28    1976         KY               REPUBLICAN          197697
5     1976         AZ                 DEMOCRAT          194908
6     1976         AZ               REPUBLICAN          189551
17    1976         HI                 DEMOCRAT          184166
45    1976         NC               REPUBLICAN          182179
46    1976         ND               REPUBLICAN          181018
20    1976         ID               REPUBLICAN          180008
25    1976         KS                 DEMOCRAT          178712
54    1976         NM               REPUBLICAN          162587
79    1976         WA               REPUBLICAN          161354
73    1976         UT                 DEMOCRAT          155631
55    1976         NV                 DEMOCRAT          153996
74    1976         UT               REPUBLICAN          144861
77    1976         VT               REPUBLICAN          124458
53    1976         NM                 DEMOCRAT          123563
42    1976         MT                 DEMOCRAT          111487
13    1976         DE               REPUBLICAN          110636
49    1976         NH                 DEMOCRAT          107806
47    1976         NE                 DEMOCRAT          106296
50    1976         NH               REPUBLICAN          100911
83    1976         WY                 DEMOCRAT           85721
43    1976         MT               REPUBLICAN           84149
0     1976         AK               REPUBLICAN           83722
67    1976         SC               REPUBLICAN           83426
61    1976         OK               REPUBLICAN           78651
4     1976         AR               REPUBLICAN               1
91    1978         CA                 DEMOCRAT         2259364
92    1978         CA               REPUBLICAN         1860758
141   1978         NY                 DEMOCRAT         1623769
148   1978         PA                 DEMOCRAT         1338994
107   1978         IL               REPUBLICAN         1197236
121   1978         MI                 DEMOCRAT         1194769
116   1978         MA                 DEMOCRAT         1184443
157   1978         TX                 DEMOCRAT         1145989
144   1978         OH               REPUBLICAN         1129274
142   1978         NY               REPUBLICAN         1098791
149   1978         PA               REPUBLICAN          974430
106   1978         IL                 DEMOCRAT          942995
125   1978         MO                 DEMOCRAT          824141
98    1978         FL                 DEMOCRAT          805528
136   1978         NJ                 DEMOCRAT          785646
143   1978         OH                 DEMOCRAT          757638
122   1978         MI               REPUBLICAN          610573
147   1978         OR                 DEMOCRAT          587445
129   1978         NC                 DEMOCRAT          577563
166   1978         WI                 DEMOCRAT          570619
95    1978         CT                 DEMOCRAT          532478
108   1978         IN                 DEMOCRAT          520100
118   1978         MD                 DEMOCRAT          514701
124   1978         MN               REPUBLICAN          490837
162   1978         VA               REPUBLICAN          480538
123   1978         MN                 DEMOCRAT          474667
155   1978         TN                 DEMOCRAT          463224
164   1978         WA                 DEMOCRAT          454546
137   1978         NJ               REPUBLICAN          435814
100   1978         GA                 DEMOCRAT          432759
111   1978         KS               REPUBLICAN          396732
158   1978         TX               REPUBLICAN          363599
109   1978         IN               REPUBLICAN          345451
167   1978         WI               REPUBLICAN          334984
156   1978         TN               REPUBLICAN          331855
161   1978         VA                 DEMOCRAT          315154
145   1978         OK                 DEMOCRAT          312975
85    1978         AL                 DEMOCRAT          309002
168   1978         WV                 DEMOCRAT          290927
151   1978         SC                 DEMOCRAT          278822
103   1978         IA                 DEMOCRAT          257998
99    1978         FL               REPUBLICAN          257014
104   1978         IA               REPUBLICAN          256243
93    1978         CO                 DEMOCRAT          251300
133   1978         NE               REPUBLICAN          240610
117   1978         MA               REPUBLICAN          233853
120   1978         ME               REPUBLICAN          208730
102   1978         HI                 DEMOCRAT          202824
126   1978         MO               REPUBLICAN          201140
88    1978         AR               REPUBLICAN          195371
86    1978         AL               REPUBLICAN          195335
94    1978         CO               REPUBLICAN          195054
89    1978         AZ                 DEMOCRAT          179728
150   1978         RI                 DEMOCRAT          174165
113   1978         KY               REPUBLICAN          173922
90    1978         AZ               REPUBLICAN          171876
112   1978         KY                 DEMOCRAT          169436
105   1978         ID               REPUBLICAN          167271
119   1978         MD               REPUBLICAN          151576
131   1978         ND               REPUBLICAN          147712
130   1978         NC               REPUBLICAN          133161
140   1978         NV                 DEMOCRAT          132513
152   1978         SC               REPUBLICAN          122515
160   1978         UT               REPUBLICAN          121492
139   1978         NM               REPUBLICAN          118075
110   1978         KS                 DEMOCRAT          100139
165   1978         WA               REPUBLICAN           99942
138   1978         NM                 DEMOCRAT           95710
159   1978         UT                 DEMOCRAT           93892
97    1978         DE               REPUBLICAN           91689
163   1978         VT               REPUBLICAN           90688
127   1978         MT                 DEMOCRAT           86016
135   1978         NH               REPUBLICAN           84535
96    1978         CT               REPUBLICAN           83990
134   1978         NH                 DEMOCRAT           82697
132   1978         NE                 DEMOCRAT           77135
169   1978         WY               REPUBLICAN           75855
128   1978         MT               REPUBLICAN           75766
146   1978         OK               REPUBLICAN           71451
154   1978         SD               REPUBLICAN           70780
84    1978         AK               REPUBLICAN           68811
114   1978         LA                 DEMOCRAT           65587
153   1978         SD                 DEMOCRAT           64683
101   1978         GA               REPUBLICAN           47078
115   1978         LA               REPUBLICAN               3
87    1978         AR                 DEMOCRAT               2
178   1980         CA               REPUBLICAN         3016276
177   1980         CA                 DEMOCRAT         2292007
244   1980         TX                 DEMOCRAT         2079325
193   1980         IL               REPUBLICAN         2012201
225   1980         NY                 DEMOCRAT         1846098
226   1980         NY               REPUBLICAN         1671230
228   1980         OH               REPUBLICAN         1643617
184   1980         FL                 DEMOCRAT         1492451
235   1980         PA               REPUBLICAN         1490789
207   1980         MI                 DEMOCRAT         1400108
202   1980         MA                 DEMOCRAT         1335203
233   1980         PA                 DEMOCRAT         1319753
192   1980         IL                 DEMOCRAT         1118967
227   1980         OH                 DEMOCRAT         1091194
248   1980         VA               REPUBLICAN         1005272
208   1980         MI               REPUBLICAN          977293
186   1980         GA                 DEMOCRAT          906934
222   1980         NJ               REPUBLICAN          889978
221   1980         NJ                 DEMOCRAT          846238
245   1980         TX               REPUBLICAN          837115
204   1980         MD                 DEMOCRAT          818594
210   1980         MN               REPUBLICAN          784060
211   1980         MO                 DEMOCRAT          780952
252   1980         WI                 DEMOCRAT          708610
194   1980         IN                 DEMOCRAT          678556
250   1980         WA                 DEMOCRAT          674189
215   1980         NC                 DEMOCRAT          672758
253   1980         WI               REPUBLICAN          651872
242   1980         TN                 DEMOCRAT          617218
195   1980         IN               REPUBLICAN          610520
185   1980         FL               REPUBLICAN          578558
212   1980         MO               REPUBLICAN          554791
231   1980         OR                 DEMOCRAT          518648
181   1980         CT                 DEMOCRAT          517026
171   1980         AL                 DEMOCRAT          477150
197   1980         KS               REPUBLICAN          463975
218   1980         NE               REPUBLICAN          451328
209   1980         MN                 DEMOCRAT          427861
198   1980         KY                 DEMOCRAT          421773
216   1980         NC               REPUBLICAN          406693
243   1980         TN               REPUBLICAN          406188
229   1980         OK                 DEMOCRAT          402837
200   1980         LA                 DEMOCRAT          398124
189   1980         IA                 DEMOCRAT          375251
206   1980         ME               REPUBLICAN          375073
179   1980         CO                 DEMOCRAT          366734
180   1980         CO               REPUBLICAN          355540
190   1980         IA               REPUBLICAN          352805
246   1980         UT               REPUBLICAN          351996
199   1980         KY               REPUBLICAN          343518
239   1980         SC               REPUBLICAN          341199
251   1980         WA               REPUBLICAN          315166
172   1980         AL               REPUBLICAN          310904
203   1980         MA               REPUBLICAN          288308
176   1980         AZ               REPUBLICAN          279526
175   1980         AZ                 DEMOCRAT          269184
182   1980         CT               REPUBLICAN          241309
188   1980         HI                 DEMOCRAT          239733
191   1980         ID               REPUBLICAN          233041
254   1980         WV                 DEMOCRAT          225066
201   1980         LA               REPUBLICAN          200317
255   1980         WV               REPUBLICAN          197388
223   1980         NM               REPUBLICAN          187474
238   1980         SC                 DEMOCRAT          187453
217   1980         ND                 DEMOCRAT          166437
224   1980         NV                 DEMOCRAT          165107
174   1980         AR               REPUBLICAN          159149
249   1980         VT               REPUBLICAN          154274
232   1980         OR               REPUBLICAN          141854
183   1980         DE               REPUBLICAN          133842
196   1980         KS                 DEMOCRAT          124014
205   1980         MD               REPUBLICAN          120985
236   1980         RI                 DEMOCRAT          120756
256   1980         WY               REPUBLICAN          116361
237   1980         RI               REPUBLICAN          115057
170   1980         AK               REPUBLICAN          114089
219   1980         NH                 DEMOCRAT          114061
220   1980         NH               REPUBLICAN          113304
213   1980         MT                 DEMOCRAT          112866
247   1980         VA                 DEMOCRAT          112143
240   1980         SD                 DEMOCRAT          109910
187   1980         GA               REPUBLICAN           96071
214   1980         MT               REPUBLICAN           91431
230   1980         OK               REPUBLICAN           90053
241   1980         SD               REPUBLICAN           88991
234   1980         PA     FOGLIETTA (DEMOCRAT)           58737
173   1980         AR                 DEMOCRAT               2
264   1982         CA                 DEMOCRAT         2808901
265   1982         CA               REPUBLICAN         2037306
331   1982         TX                 DEMOCRAT         1727806
314   1982         NY                 DEMOCRAT         1701214
279   1982         IL                 DEMOCRAT         1476778
322   1982         PA                 DEMOCRAT         1379783
315   1982         NY               REPUBLICAN         1322255
289   1982         MA                 DEMOCRAT         1300344
294   1982         MI                 DEMOCRAT         1295718
316   1982         OH                 DEMOCRAT         1122030
317   1982         OH               REPUBLICAN         1069493
271   1982         FL                 DEMOCRAT          959342
280   1982         IL               REPUBLICAN          953364
323   1982         PA               REPUBLICAN          926332
308   1982         NJ                 DEMOCRAT          883252
291   1982         MD                 DEMOCRAT          694653
296   1982         MN                 DEMOCRAT          685023
302   1982         NC                 DEMOCRAT          661021
295   1982         MI               REPUBLICAN          644544
298   1982         MO                 DEMOCRAT          626667
273   1982         GA                 DEMOCRAT          619651
329   1982         TN                 DEMOCRAT          597884
339   1982         WI                 DEMOCRAT          559126
282   1982         IN               REPUBLICAN          549526
258   1982         AL                 DEMOCRAT          540365
281   1982         IN                 DEMOCRAT          531027
337   1982         WA                 DEMOCRAT          524553
309   1982         NJ               REPUBLICAN          500046
318   1982         OK                 DEMOCRAT          496960
335   1982         VA               REPUBLICAN          480840
272   1982         FL               REPUBLICAN          469005
332   1982         TX               REPUBLICAN          432251
340   1982         WI               REPUBLICAN          423534
268   1982         CT                 DEMOCRAT          414052
305   1982         NE               REPUBLICAN          402167
297   1982         MN               REPUBLICAN          398653
320   1982         OR                 DEMOCRAT          393502
341   1982         WV                 DEMOCRAT          343236
338   1982         WA               REPUBLICAN          315313
276   1982         IA                 DEMOCRAT          313872
334   1982         VA                 DEMOCRAT          313407
333   1982         UT               REPUBLICAN          312003
284   1982         KS               REPUBLICAN          301417
277   1982         IA               REPUBLICAN          293145
267   1982         CO               REPUBLICAN          288938
266   1982         CO                 DEMOCRAT          288547
263   1982         AZ               REPUBLICAN          285934
299   1982         MO               REPUBLICAN          275877
285   1982         KY                 DEMOCRAT          273225
330   1982         TN               REPUBLICAN          272377
275   1982         HI                 DEMOCRAT          266851
293   1982         ME               REPUBLICAN          260925
260   1982         AR                 DEMOCRAT          245464
261   1982         AR               REPUBLICAN          230684
321   1982         OR               REPUBLICAN          210818
326   1982         SC                 DEMOCRAT          209052
327   1982         SC               REPUBLICAN          205316
286   1982         KY               REPUBLICAN          195455
283   1982         KS                 DEMOCRAT          193612

# POVERTY CLAUDIO STATE/YEAR

In [ ]:
df_poverty.info()
#Il DataFrame ha 3 colonne:
#state: Una colonna di tipo object
#year: Una colonna di tipo int64 (intero). Ci sono 884 valori non nulli in questa colonna.
#povertyPercentage: Una colonna di tipo float64 832 valori non nulli in questa colonna.
#non nulli indicati con Nan

In [ ]:
unique_states = df['state'].unique()
print(unique_states)
#in pandas le string type vengono classificate come object,
#ma si possono trattare anche come stringhe

**Poverty By State Year Dataset**



- **state**
  1.   Type: **Object**
  2.   Description: This is the identifier of the
       single state


- **year**
  1. Type: **Int64**
  2. Description: This is the identifier
     of the Year of the poverty percentage according to each state

- **poveryPercentage**
  1. Type: **Float64**
  2. Description: This is the identifier of the   
  poverty percentage of each state

In [ ]:
df_poverty = df.sort_values(by='povertyPercentage', ascending = False)
# Seleziona il numero desiderato di righe principali.
top_states = df_poverty.head(884)
plt.figure(figsize=(24, 8))
plt.bar(top_states['state'], top_states['povertyPercentage'])
plt.xlabel('Stati')
plt.ylabel('Percentuale di Povertà')
plt.title('Stati con la Percentuale di Povertà più Alta')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()

In [ ]:
#ci sono tuttavia stati che presentano un povertyPercentage pari a Nan
nan_count = df_poverty['povertyPercentage'].isna().sum()
#mostro su un grafico
nan_counts_per_state = df.groupby('state')['povertyPercentage'].apply(lambda x: x.isna().sum())

plt.figure(figsize=(5, 5))
plt.pie(nan_counts_per_state, labels = nan_counts_per_state.index, autopct='%1.1f%%', startangle=140)
plt.axis('equal') #cosi mi da il cerchio
plt.title('Numero di NaN nella colonna "povertyPercentage" per stato')
plt.show()

In [ ]:
#testo su uno stato per vedere se è vero
arizona_data = df[df['state'] == 'Arizona']
nan_percentage_arizona = (arizona_data['povertyPercentage'].isna().mean() * 100).round(1)
print(f"Percentuale di NaN in 'povertyPercentage' per Arizona: {nan_percentage_arizona}%")

In [ ]:
data = {
    'NaN': nan_percentage_arizona,
    'Non-NaN': 100 - nan_percentage_arizona
}
plt.figure(figsize=(6, 6))
plt.pie(data.values(), labels=data.keys(), autopct='%1.1f%%')
plt.axis('equal')  # Assicura che il grafico sia un cerchio.
plt.title('Percentuale di NaN nella colonna "povertyPercentage" per Arizona')
plt.show()
#tutti gli stati hanno solo un Nan

In [ ]:
#percentuale di poverta per ogni stato
nan_percentages = (df.groupby('state')['povertyPercentage'].apply(lambda x: (x.isna().mean() * 100).round(1))
                  .reset_index(name='NaN Percentage'))

print(nan_percentages)

In [ ]:
nan_count = df_poverty['povertyPercentage'].isna().sum()
print("Numero di valori NaN in povertyPercentage:", nan_count)
#numero di Nan in Poverty

In [ ]:
# Crea una lista per tenere traccia degli stati con almeno un NaN.
states_with_nan = []

for state in df['state'].unique():
    state_df = df[df['state'] == state]
    if state_df['povertyPercentage'].isna().any():
        states_with_nan.append(state)

# Stampa gli stati con almeno un NaN.
if len(states_with_nan) > 2:
    print("Stati con almeno 1 NaN:")
    for state in states_with_nan:
        print(state)
else:
    print("Nessun stato ha almeno un NaN.")
  #tutti gli stati hanno 1 Nan

In [ ]:
#LA MEDIA DI POVERTA DI TUTTI GLI STATI DI TUTTI GLI ANNI
import pandas as pd

# Load your CSV data
df = pd.read_csv('/content/data/povertyByStateYear.csv')

# Calcola la media di povertà per ogni stato
average_poverty_by_state = df.groupby('state')['povertyPercentage'].mean().reset_index()

# Mostra il DataFrame con le medie di povertà per ogni stato
print(average_poverty_by_state)

In [ ]:
import plotly.express as px
import pandas as pd
#dato che solo con state la rappresentazione non funzionava ho utilizzato le cordinate degli stati, poiche la lib ploty non mi indicava col nome lo stato
#quindi per tutti gli stati sono state inserite le  coordinate per permettere la visualizzazione della mappa

# Load your CSV data
df = pd.read_csv('/content/data/povertyByStateYear.csv')

# Dizionario con le coordinate degli stati
coordinates = {
      'Alabama': (32.806671, -86.791130),
    'Alaska': (61.370716, -152.404419),
    'Arizona': (33.729759, -111.431221),
    'Arkansas': (34.969704, -92.373123),
    'California': (36.116203, -119.681564),
    'Colorado': (39.059811, -105.311104),
    'Connecticut': (41.597782, -72.755371),
    'Delaware': (39.318523, -75.507141),
    'Florida': (27.994402, -81.760254),
    'Georgia': (33.040619, -83.643074),
    'Hawaii': (21.094318, -157.498337),
    'Idaho': (44.240459, -114.478828),
    'Illinois': (40.349457, -88.986137),
    'Indiana': (39.849426, -86.258278),
    'Iowa': (42.011539, -93.210526),
    'Kansas': (38.526600, -96.726486),
    'Kentucky': (37.668140, -84.670067),
    'Louisiana': (31.169546, -91.867805),
    'Maine': (44.693947, -69.381927),
    'Maryland': (39.063946, -76.802101),
    'Massachusetts': (42.230171, -71.530106),
    'Michigan': (43.326618, -84.536095),
    'Minnesota': (45.694454, -93.900192),
    'Mississippi': (32.741646, -89.678696),
    'Missouri': (38.456085, -92.288368),
    'Montana': (46.921925, -110.454353),
    'Nebraska': (41.125370, -98.268082),
    'Nevada': (38.313515, -117.055374),
    'New Hampshire': (43.452492, -71.563896),
    'New Jersey': (40.298904, -74.521011),
    'New Mexico': (34.840515, -106.248482),
    'New York': (42.165726, -74.948051),
    'North Carolina': (35.630066, -79.806419),
    'North Dakota': (47.528912, -99.784012),
    'Ohio': (40.388783, -82.764915),
    'Oklahoma': (35.565342, -96.928917),
    'Oregon': (44.572021, -122.070938),
    'Pennsylvania': (40.590752, -77.209755),
    'Rhode Island': (41.680893, -71.511780),
    'South Carolina': (33.856892, -80.945007),
    'South Dakota': (44.299782, -99.438828),
    'Tennessee': (35.747845, -86.692345),
    'Texas': (31.054487, -97.563461),
    'Utah': (40.150032, -111.862434),
    'Vermont': (44.045876, -72.710686),
    'Virginia': (37.769337, -78.169968),
    'Washington': (47.400902, -121.490494),
    'West Virginia': (38.491226, -80.954170),
    'Wisconsin': (44.268543, -89.616508),
    'Wyoming': (42.755966, -107.302490),


}

# Aggiungi colonne con le coordinate degli stati
df[['lat_state', 'lon_state']] = df['state'].apply(lambda x: pd.Series(coordinates.get(x, (None, None))))

# Crea la mappa coropletica per gli USA
fig = px.scatter_geo(
    df.dropna(subset=['lat_state', 'lon_state']),
    locationmode='USA-states',
    lon='lon_state',
    lat='lat_state',
    color='povertyPercentage',
    color_continuous_scale="Viridis",
    title='Poverty Percentage in the USA with State Coordinates',
    labels={'povertyPercentage': 'Poverty Percentage'},
    scope="usa",
    hover_data={'state': True, 'povertyPercentage': ':.2f'}
)

# Aggiungi etichette e formattazione al passaggio del mouse
fig.update_layout(
    geo=dict(
        scope='usa',
        showland=True,
    ),
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="Arial",
        bordercolor="black"
    )
)

# Personalizza il testo del popup
fig.update_traces(
    hovertemplate='%{customdata[0]}: %{customdata[1]:.2f}%<extra></extra>'
)

# Mostra la mappa
fig.show()

# DATA CLEANING

**INCIDENTS DATASET**

In [ ]:
import pandas as pd

df_incidents['date'] = pd.to_datetime(df_incidents['date'])

# Replace years 2030, 2029, 2028 with 2020, 2019, 2018 respectively
df_incidents['date'] = df_incidents['date'].apply(lambda x: x.replace(year=x.year - 10) if x.year in [2030, 2029, 2028] else x)

print("Highest Date:", df_incidents['date'].max())
print("Lowest Date:", df_incidents['date'].min())

Highest Date: 2020-11
Lowest Date: 2013-01

In [ ]:
df_incidents['date'] = pd.to_datetime(df_incidents['date']).dt.to_period('M')
#df_incidents['date'] = pd.to_datetime(df_incidents['date'])
date_occurrences = df_incidents['date'].value_counts()
pd.set_option('display.max_rows', None)

print(date_occurrences)

DROPPO LE FEATURE CHE NON SARANNO PRESENTI SUL DATAFRAME FINALE

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
sorted_df_incidents = df_incidents.sort_values(by=['date','state'])
columns_to_drop = ['address','latitude','longitude','state_house_district','state_senate_district','notes']

clean_df_incidents = sorted_df_incidents.drop(columns=columns_to_drop)
#clean_df_incidents['congressional_district'] = clean_df_incidents['congressional_district'].fillna(0).astype('int64')
clean_df_incidents.head(10)

,date,state,city_or_county,congressional_district,participant_age1,participant_age_group1,participant_gender1,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2,state_code
3830,2013-01,CALIFORNIA,Hawthorne,43.0,20.0,Adult 18+,Male,20.0,20.0,20.0,0.0,0.0,4.0,1.0,0.0,1,3,0.0,0.0,5.0,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",CA
55823,2013-01,COLORADO,Aurora,6.0,29.0,Adult 18+,Female,29.0,38.0,56.0,0.0,0.0,4.0,3.0,1.0,4,0,0.0,0.0,4.0,"Shot - Dead (murder, accidental, suicide)",Officer Involved Incident,CO
26639,2013-01,LOUISIANA,New Orleans,2.0,NaN,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0.0,0,5,0.0,0.0,6.0,Shot - Wounded/Injured,"Drive-by (car to street, car to car)",LA
228849,2013-01,LOUISIANA,Charenton,3.0,78.0,Adult 18+,Male,48.0,63.0,78.0,0.0,0.0,5.0,5.0,0.0,2,3,1.0,0.0,5.0,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",LA
44518,2013-01,MARYLAND,Baltimore,7.0,15.0,Teen 12-17,Male,15.0,15.0,15.0,0.0,1.0,6.0,1.0,0.0,1,6,0.0,0.0,7.0,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",MD
115384,2013-01,MISSOURI,Saint Louis,1.0,28.0,Adult 18+,Male,28.0,28.0,28.0,0.0,0.0,1.0,1.0,0.0,1,3,0.0,0.0,5.0,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",MO
69414,2013-01,NEW MEXICO,Albuquerque,1.0,51.0,Adult 18+,Male,2.0,20.0,51.0,3.0,1.0,2.0,3.0,3.0,5,0,1.0,0.0,6.0,"Shot - Dead (murder, accidental, suicide)",Mass Shooting (4+ victims injured or killed ex...,NM
135009,2013-01,NORTH CAROLINA,Greensboro,6.0,18.0,Adult 18+,Female,14.0,31.0,47.0,0.0,1.0,3.0,2.0,2.0,2,2,0.0,0.0,4.0,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",NC
137333,2013-01,OHIO,Lorain,9.0,25.0,Adult 18+,Male,25.0,31.0,34.0,0.0,0.0,5.0,5.0,0.0,1,3,2.0,1.0,5.0,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",OH
222715,2013-01,OHIO,Springfield,8.0,34.0,Adult 18+,Male,23.0,29.0,34.0,0.0,0.0,5.0,5.0,0.0,1,3,1.0,0.0,5.0,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",OH

PULIZIA FEATURE

In [ ]:
#TRASFORMO 'PARTICIPANT_AGE1'
clean_df_incidents['participant_age1'] = clean_df_incidents['participant_age1'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['participant_age1'] = pd.to_numeric(clean_df_incidents['participant_age1'], errors = 'coerce').astype('Int64')
clean_df_incidents['participant_age1'] = (clean_df_incidents['participant_age1'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['participant_age1'] > 100, 'participant_age1'] = pd.NA

In [ ]:
#TRASFORMO 'MIN_AGE_PARTICIPANT'
clean_df_incidents['min_age_participants'] = clean_df_incidents['min_age_participants'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['min_age_participants'] = pd.to_numeric(clean_df_incidents['min_age_participants'], errors = 'coerce').astype('Int64')
clean_df_incidents['min_age_participants'] = (clean_df_incidents['min_age_participants'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['min_age_participants'] > 100, 'min_age_participants'] = pd.NA

In [ ]:
#TRASFORMO 'AVG_AGE_PARTICIPANT'
clean_df_incidents['avg_age_participants'] = clean_df_incidents['avg_age_participants'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['avg_age_participants'] = pd.to_numeric(clean_df_incidents['avg_age_participants'], errors = 'coerce').astype('Int64')
clean_df_incidents['avg_age_participants'] = (clean_df_incidents['avg_age_participants'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['avg_age_participants'] > 100, 'avg_age_participants'] = pd.NA

In [ ]:
#TRASFORMO 'MAX_AGE_PARTICIPANT'
clean_df_incidents['max_age_participants'] = clean_df_incidents['max_age_participants'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['max_age_participants'] = pd.to_numeric(clean_df_incidents['max_age_participants'], errors = 'coerce').astype('Int64')
clean_df_incidents['max_age_participants'] = (clean_df_incidents['max_age_participants'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['max_age_participants'] > 100, 'max_age_participants'] = pd.NA

In [ ]:
#TRASFORMO N_PARTICIPANTS_CHILD
clean_df_incidents['n_participants_child'] = clean_df_incidents['n_participants_child'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['n_participants_child'] = pd.to_numeric(clean_df_incidents['n_participants_child'],errors = 'coerce').astype('Int64')
clean_df_incidents['n_participants_child'] = (clean_df_incidents['n_participants_child'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['n_participants_child'] > clean_df_incidents['n_participants'], 'n_participants_child'] = pd.NA

In [ ]:
#TRASFORMO N_PARTICIPANTS_TEEN
clean_df_incidents['n_participants_teen'] = clean_df_incidents['n_participants_teen'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['n_participants_teen'] = pd.to_numeric(clean_df_incidents['n_participants_teen'],errors = 'coerce').astype('Int64')
clean_df_incidents['n_participants_teen'] = (clean_df_incidents['n_participants_teen'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['n_participants_teen'] > clean_df_incidents['n_participants'], 'n_participants_teen'] = pd.NA

In [ ]:
#TRASFORMO N_PARTICIPANTS_ADULT
clean_df_incidents['n_participants_adult'] = clean_df_incidents['n_participants_adult'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['n_participants_adult'] = pd.to_numeric(clean_df_incidents['n_participants_adult'],errors = 'coerce').astype('Int64')
clean_df_incidents['n_participants_adult'] = (clean_df_incidents['n_participants_adult'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['n_participants_adult'] > clean_df_incidents['n_participants'], 'n_participants_adult'] = pd.NA

In [ ]:
#TRASFORMO N_MALES
clean_df_incidents['n_males'] = clean_df_incidents['n_males'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['n_males'] = pd.to_numeric(clean_df_incidents['n_males'],errors = 'coerce').astype('Int64')
clean_df_incidents['n_males'] = (clean_df_incidents['n_males'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['n_males'] > clean_df_incidents['n_participants'], 'n_males'] = pd.NA

In [ ]:
#TRASFORMO N_FEMALES
clean_df_incidents['n_females'] = clean_df_incidents['n_females'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['n_females'] = pd.to_numeric(clean_df_incidents['n_females'],errors = 'coerce').astype('Int64')
clean_df_incidents['n_females'] = (clean_df_incidents['n_females'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['n_females'] > clean_df_incidents['n_participants'], 'n_females'] = pd.NA

In [ ]:
#TRASFORMO N_ARRESTED
clean_df_incidents['n_arrested'] = clean_df_incidents['n_arrested'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['n_arrested'] = pd.to_numeric(clean_df_incidents['n_arrested'],errors = 'coerce').astype('Int64')
clean_df_incidents['n_arrested'] = (clean_df_incidents['n_arrested'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['n_arrested'] > clean_df_incidents['n_participants'], 'n_arrested'] = pd.NA

In [ ]:
#TRASFORMO N_UNHARMED
clean_df_incidents['n_unharmed'] = clean_df_incidents['n_unharmed'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['n_unharmed'] = pd.to_numeric(clean_df_incidents['n_unharmed'],errors = 'coerce').astype('Int64')
clean_df_incidents['n_unharmed'] = (clean_df_incidents['n_unharmed'] / 10).astype('Int64')
clean_df_incidents.loc[clean_df_incidents['n_unharmed'] > clean_df_incidents['n_participants'], 'n_unharmed'] = pd.NA

In [ ]:
#TRASFORMO N_PARTICIPANTS
clean_df_incidents['n_participants'] = clean_df_incidents['n_participants'].apply(lambda x: ''.join(filter(str.isdigit, str(x))) if pd.notnull(x) else x)
clean_df_incidents['n_participants'] = pd.to_numeric(clean_df_incidents['n_participants'],errors = 'coerce').astype('Int64')
clean_df_incidents['n_participants'] = (clean_df_incidents['n_participants'] / 10).astype('Int64')

In [ ]:
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pd.options.plotting.backend = 'plotly'
pio.templates.default = "seaborn"

x = pd.DataFrame(clean_df_incidents.isna().sum())
x.rename(columns={0: 'Missing values'}, inplace=True)
x.index.name = 'Feature'
x.reset_index(inplace=True)
#x.set_index('Feature', inplace=True)

fig = px.bar(x, x="Feature", y="Missing values", log_y=True)

fig.update_layout(
    xaxis_dtick = 1,
    xaxis_tickangle = 45
)

fig.show()

ELIMINAZIONE RIGHE SENZA INCIDENTI

In [ ]:
columns_to_check = [
    #'participant_age1',
    #'participant_age_group1',
    #'participant_gender1',
    'min_age_participants',
    'avg_age_participants',
    'max_age_participants',
    'n_participants_child',
    'n_participants_teen',
    'n_participants_adult',
    'n_males',
    'n_females',
    #'n_killed',
    #'n_injured',
    'n_arrested',
    'n_unharmed',
    #'n_participants'
]
clean_df_incidents[columns_to_check] = clean_df_incidents[columns_to_check].replace({'<NA>': pd.NA})
rows_to_replace = clean_df_incidents[columns_to_check].isna().all(axis=1)
clean_df_incidents.loc[rows_to_replace, 'n_participants'] = clean_df_incidents.loc[rows_to_replace, 'n_participants'].replace({0: pd.NA})

clean_df_incidents.dropna(subset=columns_to_check, how='all', inplace=True)

In [ ]:
print(len(clean_df_incidents))

213683

IF PARTICIPANT_AGE1 < MIN_AGE_PARTICIPANT UPDATE THE MIN
IF PARTICIPANT_AGE1 > MAX_AGE_PARTICIPANT UPDATE THE MAX
IF MIN_AGE_PARTICIPANT > MAX_AGE_PARTICIPANT SWAP THEM

In [ ]:
def check_and_swap_ages(row):
    min_age = row['min_age_participants']
    avg_age = row['avg_age_participants']
    max_age = row['max_age_participants']
    participant_age1 = row['participant_age1']

    # Check if participant_age1 is less than min_age, assign to min_age
    if pd.notna(participant_age1) and pd.notna(min_age) and participant_age1 < min_age:
        row['min_age_participants'] = participant_age1

    # Check if participant_age1 is greater than max_age, assign to max_age
    if pd.notna(participant_age1) and pd.notna(max_age) and participant_age1 > max_age:
        row['max_age_participants'] = participant_age1

    # Check and swap values if necessary
    if pd.notna(min_age) and pd.notna(avg_age) and pd.notna(max_age):
        if min_age > max_age:
            row['min_age_participants'], row['max_age_participants'] = max_age, min_age

    return row

# Apply the function to each row
clean_df_incidents = clean_df_incidents.apply(check_and_swap_ages, axis=1)

IF THE MIN,MAX AGE PARTICIPANTS ARE NOT NAN AND N_PARTICIPANTS IS EQUAL TO 2 EXTRACT THE AVERAGE_AGE_PARTICIPANTS

In [ ]:

def process_age(row):
    min_age = row['min_age_participants']
    avg_age = row['avg_age_participants']
    max_age = row['max_age_participants']
    n_participants = row['n_participants']

    # Check if necessary columns are not NaN and n_participants is 2
    if pd.notna(min_age) and pd.notna(max_age) and n_participants == 2:
       # Assign the average between min_age and max_age to avg_age
       row['avg_age_participants'] = (min_age + max_age) / 2

    if pd.isna(min_age) and pd.isna(max_age):
      # Check if avg_age is equal to 0, swap it to NaN
      if pd.notna(avg_age) and avg_age == 0:
            row['avg_age_participants'] = pd.NA

    return row

# Apply the function to each row
clean_df_incidents = clean_df_incidents.apply(process_age, axis=1)

FILLING NaN VALUES IN PARTICIPANT_AGE_GROUP1

In [ ]:

def fill_age_group2(row):
    if pd.isna(row['min_age_participants']) and pd.isna(row['avg_age_participants']) and pd.isna(row['max_age_participants']):
        return row['participant_age_group1']
    elif any(0 <= age <= 11 for age in [row['min_age_participants'], row['avg_age_participants'], row['max_age_participants']] if pd.notna(age)):
        return 'Child 0-11'
    elif any(12 <= age <= 17 for age in [row['min_age_participants'], row['avg_age_participants'], row['max_age_participants']] if pd.notna(age)):
        return 'Teen 12-17'
    else:
        return 'Adult 18+'

# Apply the function to fill NaN values in 'participant_age_group1'
clean_df_incidents['participant_age_group1'] = clean_df_incidents.apply(fill_age_group2, axis=1)

EXTRACT VALUES FOR N_PARTICIPANTS_ADULT/TEEN/CHILD

In [ ]:
# Check if n_participants > 0 and n_participants_adult = 0 or NaN
condition_adult = (clean_df_incidents['n_participants'] > 0) & ((clean_df_incidents['n_participants_adult'] == 0) | clean_df_incidents['n_participants_adult'].isna()) & (clean_df_incidents['participant_age_group1'] == 'Adult 18+')
clean_df_incidents.loc[condition_adult, 'n_participants_adult'] = 1

# Check if n_participants > 0 and n_participants_teen = 0 or NaN
condition_teen = (clean_df_incidents['n_participants'] > 0) & ((clean_df_incidents['n_participants_teen'] == 0) | clean_df_incidents['n_participants_teen'].isna()) & (clean_df_incidents['participant_age_group1'] == 'Teen 12-17')
clean_df_incidents.loc[condition_teen, 'n_participants_teen'] = 1

# Check if n_participants > 0 and n_participants_child = 0 or NaN
condition_child = (clean_df_incidents['n_participants'] > 0) & ((clean_df_incidents['n_participants_child'] == 0) | clean_df_incidents['n_participants_child'].isna()) & (clean_df_incidents['participant_age_group1'] == 'Child 0-11')
clean_df_incidents.loc[condition_child, 'n_participants_child'] = 1

In [ ]:
# Check if n_participants > 0 and n_males = 0 or NaN
condition_males = (clean_df_incidents['n_participants'] > 0) & ((clean_df_incidents['n_males'] == 0) | clean_df_incidents['n_males'].isna()) & (clean_df_incidents['participant_gender1'] == 'Male')
clean_df_incidents.loc[condition_males, 'n_males'] = 1

# Check if n_participants > 0 and n_females = 0 or NaN
condition_females = (clean_df_incidents['n_participants'] > 0) & ((clean_df_incidents['n_females'] == 0) | clean_df_incidents['n_females'].isna()) & (clean_df_incidents['participant_gender1'] == 'Female')
clean_df_incidents.loc[condition_females, 'n_females'] = 1

In [ ]:
columns_to_drop2 = ['participant_age1','participant_age_group1','participant_gender1']
clean_df_incidents = clean_df_incidents.drop(columns=columns_to_drop2)

In [ ]:
columns_to_convert = [
    'min_age_participants',
    'avg_age_participants',
    'max_age_participants',
    'n_participants_child',
    'n_participants_teen',
    'n_participants_adult',
    'n_males',
    'n_females',
    'n_arrested',
    'n_unharmed'
]
# Convert specified columns to 'float64' to handle non-numeric values
clean_df_incidents[columns_to_convert] = clean_df_incidents[columns_to_convert].apply(pd.to_numeric, errors='coerce')

# Convert to 'Int64' after handling non-numeric values
# Use round() to handle floating-point numbers
clean_df_incidents[columns_to_convert] = clean_df_incidents[columns_to_convert].round().astype('Int64')

In [ ]:
clean_df_incidents['congressional_district'] = clean_df_incidents['congressional_district'].apply(pd.to_numeric, errors='coerce').astype('Int64')

In [ ]:
clean_df_incidents = clean_df_incidents.drop(columns=['state_code'])

In [ ]:
clean_df_incidents.head(10)

,date,state,city_or_county,congressional_district,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2
3830,2013-01,CALIFORNIA,Hawthorne,43,20,20,20,0,0,4,1,0,1,3,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)"
55823,2013-01,COLORADO,Aurora,6,29,38,56,0,0,4,3,1,4,0,0,0,4,"Shot - Dead (murder, accidental, suicide)",Officer Involved Incident
26639,2013-01,LOUISIANA,New Orleans,2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5,0,0,5,0,0,6,Shot - Wounded/Injured,"Drive-by (car to street, car to car)"
228849,2013-01,LOUISIANA,Charenton,3,48,63,78,0,0,5,5,0,2,3,1,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)"
44518,2013-01,MARYLAND,Baltimore,7,15,15,15,0,1,6,1,0,1,6,0,0,7,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)"
115384,2013-01,MISSOURI,Saint Louis,1,28,28,28,0,0,1,1,0,1,3,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)"
69414,2013-01,NEW MEXICO,Albuquerque,1,2,20,51,3,1,2,3,3,5,0,1,0,6,"Shot - Dead (murder, accidental, suicide)",Mass Shooting (4+ victims injured or killed ex...
135009,2013-01,NORTH CAROLINA,Greensboro,6,14,31,47,0,1,3,2,2,2,2,0,0,4,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)"
137333,2013-01,OHIO,Lorain,9,25,31,34,0,0,5,5,0,1,3,2,1,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)"
222715,2013-01,OHIO,Springfield,8,23,29,34,0,0,5,5,0,1,3,1,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)"

In [ ]:
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pd.options.plotting.backend = 'plotly'
pio.templates.default = "seaborn"

x = pd.DataFrame(clean_df_incidents.isna().sum())
x.rename(columns={0: 'Missing values'}, inplace=True)
x.index.name = 'Feature'
x.reset_index(inplace=True)
#x.set_index('Feature', inplace=True)

fig = px.bar(x, x="Feature", y="Missing values", log_y=True)

fig.update_layout(
    xaxis_dtick = 1,
    xaxis_tickangle = 45
)

fig.show()

TRANSFORMING THE DATE

In [ ]:
'''
clean_df_incidents['date'] = pd.to_datetime(clean_df_incidents['date'])
# Replace years 2030, 2029, 2028 with 2020, 2019, 2018 respectively
clean_df_incidents['date'] = clean_df_incidents['date'].apply(lambda x: x.replace(year=x.year - 10) if x.year in [2030, 2029, 2028] else x)

print("Highest Date:", clean_df_incidents['date'].max())
print("Lowest Date:", clean_df_incidents['date'].min())
'''

'\nclean_df_incidents[\'date\'] = pd.to_datetime(clean_df_incidents[\'date\'])\n# Replace years 2030, 2029, 2028 with 2020, 2019, 2018 respectively\nclean_df_incidents[\'date\'] = clean_df_incidents[\'date\'].apply(lambda x: x.replace(year=x.year - 10) if x.year in [2030, 2029, 2028] else x)\n\nprint("Highest Date:", clean_df_incidents[\'date\'].max())\nprint("Lowest Date:", clean_df_incidents[\'date\'].min())\n'

In [ ]:
'''
clean_df_incidents['date'] = pd.to_datetime(clean_df_incidents['date']).dt.to_period('M')
#df_incidents['date'] = pd.to_datetime(df_incidents['date'])
date_occurrences = clean_df_incidents['date'].value_counts()
pd.set_option('display.max_rows', None)

print(date_occurrences)
'''

"\nclean_df_incidents['date'] = pd.to_datetime(clean_df_incidents['date']).dt.to_period('M')\n#df_incidents['date'] = pd.to_datetime(df_incidents['date'])\ndate_occurrences = clean_df_incidents['date'].value_counts()\npd.set_option('display.max_rows', None)\n\nprint(date_occurrences)\n"

In [ ]:
clean_df_incidents.to_csv('/content/drive/MyDrive/' + 'final_incidents_dataset.csv', index=False)

**POVERTY DATASET**

DROP FROM THE 'POVERTY' DATASET ALL THE ROWS WITH YEARS NOT PRESENT IN THE 'INCIDENTS' DATASET

In [ ]:
sorted_df_poverty = df_poverty.sort_values(by=['year','state'])
condition = (sorted_df_poverty['year'] >= 2013) & (sorted_df_poverty['year'] <= 2020)
clean_df_poverty = sorted_df_poverty[condition]
clean_df_poverty.head(10)

                    state  year  povertyPercentage
365               Alabama  2013               17.5
366                Alaska  2013               10.2
367               Arizona  2013               18.7
368              Arkansas  2013               16.1
369            California  2013               14.9
370              Colorado  2013               11.0
371           Connecticut  2013                9.5
372              Delaware  2013               11.1
373  District of Columbia  2013               19.6
374               Florida  2013               15.9

In [ ]:
clean_df_poverty['state'] = clean_df_poverty['state'].str.upper()
clean_df_poverty.head(10)

<ipython-input-63-28e523dd479e>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                    state  year  povertyPercentage
365               ALABAMA  2013               17.5
366                ALASKA  2013               10.2
367               ARIZONA  2013               18.7
368              ARKANSAS  2013               16.1
369            CALIFORNIA  2013               14.9
370              COLORADO  2013               11.0
371           CONNECTICUT  2013                9.5
372              DELAWARE  2013               11.1
373  DISTRICT OF COLUMBIA  2013               19.6
374               FLORIDA  2013               15.9

In [ ]:
clean_df_poverty.to_csv('/content/drive/MyDrive/' + 'clean_poverty.csv', index=False)

ELIMINO DAL DATASET 'DISTRICTS' GLI ANNI NON PRESENTI NEL DATASET 'INCIDENTS'

In [ ]:
sorted_df_districts = df_districts.sort_values(by=['year','state'])
condition = (sorted_df_districts['year'] >= 2012) & (sorted_df_districts['year'] <= 2020)
clean_df_districts = sorted_df_districts[condition]
clean_df_districts.tail(10)

,year,state,congressional_district,party,candidatevotes,totalvotes
9996,2020,WEST VIRGINIA,3,REPUBLICAN,161585,226668
9997,2020,WISCONSIN,1,REPUBLICAN,238271,401754
9998,2020,WISCONSIN,2,DEMOCRAT,318523,457205
9999,2020,WISCONSIN,3,DEMOCRAT,199870,389618
10000,2020,WISCONSIN,4,DEMOCRAT,232668,311697
10001,2020,WISCONSIN,5,REPUBLICAN,265434,441599
10002,2020,WISCONSIN,6,REPUBLICAN,238874,403333
10003,2020,WISCONSIN,7,REPUBLICAN,252048,415007
10004,2020,WISCONSIN,8,REPUBLICAN,268173,417838
10005,2020,WYOMING,0,REPUBLICAN,185732,278503

Creo una copia del dataframe cosi da avere anche le date dispari

In [ ]:
# Creiamo una copia del DataFrame
clean_districts = clean_df_districts.copy()

# Riduci di 1 l'anno per la nuova riga
clean_districts['year'] = clean_districts['year'] + 1

# Concateniamo il DataFrame originale con la versione modificata
clean_districts = pd.concat([clean_df_districts, clean_districts])

# Ordiniamo il DataFrame risultante per 'year', 'state' e 'congressional_district'
clean_districts = clean_districts.sort_values(by=['year', 'state'])

# Ripristiniamo l'indice del DataFrame risultante
clean_districts = clean_districts.reset_index(drop=True)

condition = (clean_districts['year'] >= 2013) & (clean_districts['year'] <= 2020)
clean_districts = clean_districts[condition]
# DATAFRAME FINALE DEI DISTRETTI COMPLETO ANCHE CON GLI ANNI DISPARI
clean_districts.head(100)

,year,state,congressional_district,party,candidatevotes,totalvotes
435,2013,ALABAMA,1,REPUBLICAN,196374,200676
436,2013,ALABAMA,2,REPUBLICAN,180591,283953
437,2013,ALABAMA,3,REPUBLICAN,175306,273930
438,2013,ALABAMA,4,REPUBLICAN,199071,269118
439,2013,ALABAMA,5,REPUBLICAN,189185,291293
440,2013,ALABAMA,6,REPUBLICAN,219262,308102
441,2013,ALABAMA,7,DEMOCRAT,232520,306558
442,2013,ALASKA,0,REPUBLICAN,185296,289804
443,2013,ARIZONA,1,DEMOCRAT,122774,251595
444,2013,ARIZONA,2,DEMOCRAT,147338,292279
445,2013,ARIZONA,3,DEMOCRAT,98468,168698
446,2013,ARIZONA,4,REPUBLICAN,162907,243760
447,2013,ARIZONA,5,REPUBLICAN,183470,273059
448,2013,ARIZONA,6,REPUBLICAN,179706,293177
449,2013,ARIZONA,7,DEMOCRAT,104489,127827
450,2013,ARIZONA,8,REPUBLICAN,172809,272791
451,2013,ARIZONA,9,DEMOCRAT,121881,250131
452,2013,ARKANSAS,1,REPUBLICAN,138800,246843
453,2013,ARKANSAS,2,REPUBLICAN,158175,286598
454,2013,ARKANSAS,3,REPUBLICAN,186467,245660
455,2013,ARKANSAS,4,REPUBLICAN,154149,258953
456,2013,CALIFORNIA,1,REPUBLICAN,168827,294213
457,2013,CALIFORNIA,2,DEMOCRAT,226216,317526
458,2013,CALIFORNIA,3,DEMOCRAT,126882,233968
459,2013,CALIFORNIA,4,REPUBLICAN,197803,323688
460,2013,CALIFORNIA,5,DEMOCRAT,202872,272417
461,2013,CALIFORNIA,6,DEMOCRAT,160667,214073
462,2013,CALIFORNIA,7,DEMOCRAT,141241,273291
463,2013,CALIFORNIA,8,REPUBLICAN,103093,179644
464,2013,CALIFORNIA,9,DEMOCRAT,118373,213077
465,2013,CALIFORNIA,10,REPUBLICAN,110265,209199
466,2013,CALIFORNIA,11,DEMOCRAT,200743,287879
467,2013,CALIFORNIA,12,DEMOCRAT,253709,298187
468,2013,CALIFORNIA,13,DEMOCRAT,250436,288582
469,2013,CALIFORNIA,14,DEMOCRAT,203828,258283
470,2013,CALIFORNIA,15,DEMOCRAT,120388,231034
471,2013,CALIFORNIA,16,DEMOCRAT,84649,147450
472,2013,CALIFORNIA,17,DEMOCRAT,159392,216728
473,2013,CALIFORNIA,18,DEMOCRAT,212831,301934
474,2013,CALIFORNIA,19,DEMOCRAT,162300,221613
475,2013,CALIFORNIA,20,DEMOCRAT,172996,233562
476,2013,CALIFORNIA,21,REPUBLICAN,67164,116283
477,2013,CALIFORNIA,22,REPUBLICAN,132386,213941
478,2013,CALIFORNIA,23,REPUBLICAN,158161,216003
479,2013,CALIFORNIA,24,DEMOCRAT,156749,284495
480,2013,CALIFORNIA,25,REPUBLICAN,129593,236575
481,2013,CALIFORNIA,26,DEMOCRAT,139072,263935
482,2013,CALIFORNIA,27,DEMOCRAT,154191,241008
483,2013,CALIFORNIA,28,DEMOCRAT,188703,246711
484,2013,CALIFORNIA,29,DEMOCRAT,111287,150281
485,2013,CALIFORNIA,30,DEMOCRAT,149456,247851
486,2013,CALIFORNIA,31,REPUBLICAN,88964,161219
487,2013,CALIFORNIA,32,DEMOCRAT,124903,190111
488,2013,CALIFORNIA,33,DEMOCRAT,171860,318520
489,2013,CALIFORNIA,34,DEMOCRAT,120367,140590
490,2013,CALIFORNIA,35,DEMOCRAT,79698,142680
491,2013,CALIFORNIA,36,DEMOCRAT,110189,208142
492,2013,CALIFORNIA,37,DEMOCRAT,207039,239580
493,2013,CALIFORNIA,38,DEMOCRAT,145280,215087
494,2013,CALIFORNIA,39,REPUBLICAN,145607,251967
495,2013,CALIFORNIA,40,DEMOCRAT,73940,125553
496,2013,CALIFORNIA,41,DEMOCRAT,103578,175652
497,2013,CALIFORNIA,42,REPUBLICAN,130245,214947
498,2013,CALIFORNIA,43,DEMOCRAT,143123,200894
499,2013,CALIFORNIA,44,DEMOCRAT,99909,165898
500,2013,CALIFORNIA,45,REPUBLICAN,171417,293231
501,2013,CALIFORNIA,46,DEMOCRAT,95694,149815
502,2013,CALIFORNIA,47,DEMOCRAT,130093,230012
503,2013,CALIFORNIA,48,REPUBLICAN,177144,290502
504,2013,CALIFORNIA,49,REPUBLICAN,159725,274618
505,2013,CALIFORNIA,50,REPUBLICAN,174838,258293
506,2013,CALIFORNIA,51,DEMOCRAT,113934,159398
507,2013,CALIFORNIA,52,DEMOCRAT,151451,295910
508,2013,CALIFORNIA,53,DEMOCRAT,164825,268307
509,2013,COLORADO,1,DEMOCRAT,237579,348210
510,2013,COLORADO,2,DEMOCRAT,234758,421580
511,2013,COLORADO,3,REPUBLICAN,185291,347247
512,2013,COLORADO,4,REPUBLICAN,200006,342336
513,2013,COLORADO,5,REPUBLICAN,199639,307231
514,2013,COLORADO,6,REPUBLICAN,163938,342914
515,2013,COLORADO,7,DEMOCRAT,182460,340970
516,2013,CONNECTICUT,1,DEMOCRAT,192840,297061
517,2013,CONNECTICUT,2,DEMOCRAT,189444,298960
518,2013,CONNECTICUT,3,DEMOCRAT,197163,291301
519,2013,CONNECTICUT,4,DEMOCRAT,167320,293432
520,2013,CONNECTICUT,5,DEMOCRAT,137631,284757
521,2013,DELAWARE,0,DEMOCRAT,249933,388059
522,2013,FLORIDA,1,REPUBLICAN,238440,342594
523,2013,FLORIDA,2,REPUBLICAN,175856,333718
524,2013,FLORIDA,3,REPUBLICAN,204331,315669
525,2013,FLORIDA,4,REPUBLICAN,239988,315470
526,2013,FLORIDA,5,DEMOCRAT,190472,269153
527,2013,FLORIDA,6,REPUBLICAN,195962,342451
528,2013,FLORIDA,7,REPUBLICAN,185518,316010
529,2013,FLORIDA,8,REPUBLICAN,205432,348909
530,2013,FLORIDA,9,DEMOCRAT,164891,263747
531,2013,FLORIDA,10,REPUBLICAN,164649,318269
532,2013,FLORIDA,11,REPUBLICAN,218360,338663
533,2013,FLORIDA,12,REPUBLICAN,209604,330167
534,2013,FLORIDA,13,REPUBLICAN,189605,329347

**OUTLIERS**

In [ ]:
clean_districts['party'] = clean_districts['party'].replace('DEMOCRATIC-FARMER-LABOR', 'DEMOCRAT')
clean_districts['party'].unique()

array(['REPUBLICAN', 'DEMOCRAT'], dtype=object)

AFTER SOME RESEARCHES WE FOUND OUT THAT THE OUTLIERS ARE DUE TO THE WINNER BEING UNOPPOSED DURING THE GENERAL ELECTIONS SO WE REPLACE THEM WITH NaN

In [ ]:
def find_outliers(data_frame, column_name):
    # Get the column data
    column_data = data_frame[column_name]

    # Calculate the first and third quartiles (Q1 and Q3)
    Q1 = column_data.quantile(0.25)
    Q3 = column_data.quantile(0.75)

    # Calculate the Interquartile Range (IQR)
    IQR = Q3 - Q1

    # Define the lower and upper bounds to identify outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Identify outliers using the bounds
    outliers = column_data[(column_data < lower_bound) | (column_data > upper_bound)]

    return outliers

outliers_candidatevotes = find_outliers(clean_districts, 'candidatevotes')
outliers_totalvotes = find_outliers(clean_districts, 'totalvotes')

# Print the identified outliers
print("Outliers candidatevotes:")
print(outliers_candidatevotes)
print('/////////////////////////')
print("Outliers totalvotes:")
print(outliers_totalvotes)

Outliers candidatevotes:
536          1
545          1
760     318176
968          1
970          1
981          1
983          1
1184         1
1403         1
1405         1
1416         1
1418         1
1619         1
1850         0
2054         1
2065    322514
2285         0
2489         1
2500    322514
2706         1
2710         1
2717         1
2720         1
3029    329800
3141         1
3145         1
3152         1
3155         1
3464    329800
3513    327863
3554    331621
3555    316925
3578    316979
3592        -1
3611    310736
3677    310940
3713    339169
3766    311887
3768    332421
3776    341457
3802    343574
3807    341708
3832    321984
3900    387109
3908    318523
Name: candidatevotes, dtype: int64
/////////////////////////
Outliers totalvotes:
536          1
545          1
968          1
970          1
981          1
983          1
1184         1
1403         1
1405         1
1416         1
1418         1
1619         1
1850         0
1972    507831
2054         1
2285         0
2407    507831
2489         1
2706         1
2710         1
2717         1
2720         1
2842    504421
3141         1
3145         1
3152         1
3155         1
3277    504421
3555    515663
3571    504940
3592        -1
3713    601509
3766    495345
3768    493719
Name: totalvotes, dtype: int64

In [ ]:
clean_districts['candidatevotes'] = clean_districts['candidatevotes'].apply(pd.to_numeric, errors='coerce').astype('Int64')
clean_districts['totalvotes'] = clean_districts['totalvotes'].apply(pd.to_numeric, errors='coerce').astype('Int64')

In [ ]:
# List of values to replace with NaN
values_to_replace = [-1, 0, 1]

# Replace values in 'candidatevotes' and 'totalvotes' columns with NaN
clean_districts[['candidatevotes', 'totalvotes']] = clean_districts[['candidatevotes', 'totalvotes']].replace(values_to_replace, pd.NA)

In [ ]:
clean_districts.sort_values(by='candidatevotes',na_position='first').head(26)

,year,state,congressional_district,party,candidatevotes,totalvotes
536,2013,FLORIDA,15,REPUBLICAN,<NA>,<NA>
545,2013,FLORIDA,24,DEMOCRAT,<NA>,<NA>
968,2014,FLORIDA,12,REPUBLICAN,<NA>,<NA>
970,2014,FLORIDA,14,DEMOCRAT,<NA>,<NA>
981,2014,FLORIDA,25,REPUBLICAN,<NA>,<NA>
983,2014,FLORIDA,27,REPUBLICAN,<NA>,<NA>
1184,2014,OKLAHOMA,1,REPUBLICAN,<NA>,<NA>
1403,2015,FLORIDA,12,REPUBLICAN,<NA>,<NA>
1405,2015,FLORIDA,14,DEMOCRAT,<NA>,<NA>
1416,2015,FLORIDA,25,REPUBLICAN,<NA>,<NA>
1418,2015,FLORIDA,27,REPUBLICAN,<NA>,<NA>
1619,2015,OKLAHOMA,1,REPUBLICAN,<NA>,<NA>
1850,2016,FLORIDA,24,DEMOCRAT,<NA>,<NA>
2054,2016,OKLAHOMA,1,REPUBLICAN,<NA>,<NA>
2285,2017,FLORIDA,24,DEMOCRAT,<NA>,<NA>
2489,2017,OKLAHOMA,1,REPUBLICAN,<NA>,<NA>
2706,2018,FLORIDA,10,DEMOCRAT,<NA>,<NA>
2710,2018,FLORIDA,14,DEMOCRAT,<NA>,<NA>
2717,2018,FLORIDA,21,DEMOCRAT,<NA>,<NA>
2720,2018,FLORIDA,24,DEMOCRAT,<NA>,<NA>
3141,2019,FLORIDA,10,DEMOCRAT,<NA>,<NA>
3145,2019,FLORIDA,14,DEMOCRAT,<NA>,<NA>
3152,2019,FLORIDA,21,DEMOCRAT,<NA>,<NA>
3155,2019,FLORIDA,24,DEMOCRAT,<NA>,<NA>
3592,2020,FLORIDA,25,REPUBLICAN,<NA>,<NA>
1365,2015,CALIFORNIA,40,DEMOCRAT,30208,49379

In [ ]:
clean_districts.to_csv('/content/drive/MyDrive/' + 'clean_districts.csv', index=False)

# MERGE

In [ ]:
clean_df_incidents['date'] = clean_df_incidents['date'].astype(str)
clean_df_incidents[['year', 'month']] = clean_df_incidents['date'].str.split('-', expand=True)

clean_df_incidents = clean_df_incidents[['date', 'year', 'month', 'state', 'city_or_county', 'congressional_district',
                                         'min_age_participants', 'avg_age_participants', 'max_age_participants',
                                         'n_participants_child', 'n_participants_teen', 'n_participants_adult',
                                         'n_males', 'n_females', 'n_killed', 'n_injured', 'n_arrested', 'n_unharmed',
                                         'n_participants', 'incident_characteristics1', 'incident_characteristics2']]

clean_df_incidents = clean_df_incidents.drop('date', axis=1)
clean_df_incidents['year'] = clean_df_incidents['year'].astype('Int64')
clean_df_incidents['month'] = clean_df_incidents['month'].astype('Int64')

clean_df_incidents = clean_df_incidents.sort_values(by=['year', 'state', 'month'])
clean_df_incidents.head(5)

,year,month,state,city_or_county,congressional_district,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2
167104,2013,7,ALABAMA,Florence,5,22,22,22,0,0,1,0,1,0,4,1,0,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...
161692,2013,12,ALABAMA,Montgomery,2,20,22,25,0,0,9,8,1,3,5,2,0,10,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)"
141684,2013,4,ARIZONA,Phoenix,6,16,18,22,0,3,4,7,0,2,4,1,0,7,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)"
160790,2013,5,ARIZONA,Apache Junction,4,47,47,47,0,0,5,4,1,0,5,1,1,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...
198643,2013,10,ARIZONA,Avondale,3,<NA>,<NA>,<NA>,0,0,4,<NA>,<NA>,0,4,0,0,4,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...

In [ ]:
clean_df_incidents['state'] = clean_df_incidents['state'].str.upper()

In [ ]:
merged_df = pd.merge(clean_df_incidents, clean_df_poverty, on=['year', 'state'], how='left')
merged_df.head(5)

,year,month,state,city_or_county,congressional_district,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2,povertyPercentage
0,2013,7,ALABAMA,Florence,5,22,22,22,0,0,1,0,1,0,4,1,0,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,17.5
1,2013,12,ALABAMA,Montgomery,2,20,22,25,0,0,9,8,1,3,5,2,0,10,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",17.5
2,2013,4,ARIZONA,Phoenix,6,16,18,22,0,3,4,7,0,2,4,1,0,7,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7
3,2013,5,ARIZONA,Apache Junction,4,47,47,47,0,0,5,4,1,0,5,1,1,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7
4,2013,10,ARIZONA,Avondale,3,<NA>,<NA>,<NA>,0,0,4,<NA>,<NA>,0,4,0,0,4,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7

In [ ]:
clean_districts['congressional_district'] = clean_districts['congressional_district'].astype('Int64')

In [ ]:
#clean_districts.sort_values(by=['year','state','congressional_district'])

In [ ]:
final_dataset = pd.merge(merged_df, clean_districts, on=['year', 'state','congressional_district'], how='left')

In [ ]:
final_dataset.head(10)

,year,month,state,city_or_county,congressional_district,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2,povertyPercentage,party,candidatevotes,totalvotes
0,2013,7,ALABAMA,Florence,5,22,22,22,0,0,1,0,1,0,4,1,0,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,17.5,REPUBLICAN,189185,291293
1,2013,12,ALABAMA,Montgomery,2,20,22,25,0,0,9,8,1,3,5,2,0,10,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",17.5,REPUBLICAN,180591,283953
2,2013,4,ARIZONA,Phoenix,6,16,18,22,0,3,4,7,0,2,4,1,0,7,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,REPUBLICAN,179706,293177
3,2013,5,ARIZONA,Apache Junction,4,47,47,47,0,0,5,4,1,0,5,1,1,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7,REPUBLICAN,162907,243760
4,2013,10,ARIZONA,Avondale,3,<NA>,<NA>,<NA>,0,0,4,<NA>,<NA>,0,4,0,0,4,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7,DEMOCRAT,98468,168698
5,2013,10,ARIZONA,Phoenix,7,17,43,66,0,1,4,4,1,5,0,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,DEMOCRAT,104489,127827
6,2013,11,ARIZONA,Phoenix,7,15,19,22,0,1,8,6,2,1,3,5,0,9,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,DEMOCRAT,104489,127827
7,2013,1,CALIFORNIA,Hawthorne,43,20,20,20,0,0,4,1,0,1,3,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",14.9,DEMOCRAT,143123,200894
8,2013,2,CALIFORNIA,Vallejo,5,22,22,22,0,0,5,3,2,1,4,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",14.9,DEMOCRAT,202872,272417
9,2013,2,CALIFORNIA,Lancaster,25,22,28,37,0,0,4,4,0,0,4,0,2,6,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,14.9,REPUBLICAN,129593,236575

In [ ]:
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pd.options.plotting.backend = 'plotly'
pio.templates.default = "seaborn"

x = pd.DataFrame(final_dataset.isna().sum())
x.rename(columns={0: 'Missing values'}, inplace=True)
x.index.name = 'Feature'
x.reset_index(inplace=True)
#x.set_index('Feature', inplace=True)

fig = px.bar(x, x="Feature", y="Missing values", log_y=True)

fig.update_layout(
    title_text='FINAL_DATASET',
    xaxis_dtick = 1,
    xaxis_tickangle = 45
)

fig.show()

**MERGE DATASET ELIMINANDO TUTTE LE RIGHE CON DISTRETTI NULLI**

In [ ]:
test_incidents = clean_df_incidents.copy()
test_incidents['congressional_district'] = test_incidents['congressional_district'].replace(0, pd.NA)

test_districts = clean_districts.copy()
test_districts['congressional_district'] = test_districts['congressional_district'].replace(0, pd.NA)

test_incidents['congressional_district'] = test_incidents['congressional_district'].fillna(test_districts['congressional_district'])
test_districts['congressional_district'] = test_districts['congressional_district'].fillna(test_incidents['congressional_district'])

In [ ]:
# Funzione per popolare i valori mancanti in 'congressional_district'
def popola_congressional_district(row):
    if pd.isna(row['congressional_district']):
        same_city_rows = test_incidents[(test_incidents['city_or_county'] == row['city_or_county']) & (~pd.isna(test_incidents['congressional_district']))]
        if not same_city_rows.empty:
            return same_city_rows.iloc[0]['congressional_district']
    return row['congressional_district']

# Applica la funzione a ciascuna riga del DataFrame
test_incidents['congressional_district'] = test_incidents.apply(popola_congressional_district, axis=1)

In [ ]:
#test_incidents = clean_df_incidents.copy()
#test_incidents['congressional_district'] = test_incidents['congressional_district'].replace(0, pd.NA)

#test_districts = clean_districts.copy()
#test_districts['congressional_district'] = test_districts['congressional_district'].replace(0, pd.NA)

test_incidents['congressional_district'] = test_incidents['congressional_district'].fillna(test_districts['congressional_district'])
test_districts['congressional_district'] = test_districts['congressional_district'].fillna(test_incidents['congressional_district'])

test_incidents = test_incidents.dropna(subset=['congressional_district'])
test_districts = test_districts.dropna(subset=['congressional_district'])

test_merge = pd.merge(test_incidents, clean_df_poverty, on=['year', 'state'], how='left')
test_merge = pd.merge(test_merge, test_districts, on=['year', 'state','congressional_district'], how='left')

print(len(test_merge))

test_merge.head(10)

213402

,year,month,state,city_or_county,congressional_district,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2,povertyPercentage,party,candidatevotes,totalvotes
0,2013,7,ALABAMA,Florence,5,22,22,22,0,0,1,0,1,0,4,1,0,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,17.5,REPUBLICAN,189185,291293
1,2013,12,ALABAMA,Montgomery,2,20,22,25,0,0,9,8,1,3,5,2,0,10,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",17.5,REPUBLICAN,180591,283953
2,2013,4,ARIZONA,Phoenix,6,16,18,22,0,3,4,7,0,2,4,1,0,7,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,REPUBLICAN,179706,293177
3,2013,5,ARIZONA,Apache Junction,4,47,47,47,0,0,5,4,1,0,5,1,1,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7,REPUBLICAN,162907,243760
4,2013,10,ARIZONA,Avondale,3,<NA>,<NA>,<NA>,0,0,4,<NA>,<NA>,0,4,0,0,4,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7,DEMOCRAT,98468,168698
5,2013,10,ARIZONA,Phoenix,7,17,43,66,0,1,4,4,1,5,0,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,DEMOCRAT,104489,127827
6,2013,11,ARIZONA,Phoenix,7,15,19,22,0,1,8,6,2,1,3,5,0,9,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,DEMOCRAT,104489,127827
7,2013,1,CALIFORNIA,Hawthorne,43,20,20,20,0,0,4,1,0,1,3,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",14.9,DEMOCRAT,143123,200894
8,2013,2,CALIFORNIA,Vallejo,5,22,22,22,0,0,5,3,2,1,4,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",14.9,DEMOCRAT,202872,272417
9,2013,2,CALIFORNIA,Lancaster,25,22,28,37,0,0,4,4,0,0,4,0,2,6,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,14.9,REPUBLICAN,129593,236575

In [ ]:
prova = test_merge.copy()
prova = prova.dropna(subset=['congressional_district'])

In [ ]:
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pd.options.plotting.backend = 'plotly'
pio.templates.default = "seaborn"

x = pd.DataFrame(test_merge.isna().sum())
x.rename(columns={0: 'Missing values'}, inplace=True)
x.index.name = 'Feature'
x.reset_index(inplace=True)
#x.set_index('Feature', inplace=True)

fig = px.bar(x, x="Feature", y="Missing values", log_y=True)

fig.update_layout(
    title_text='FINAL_DATASET',
    xaxis_dtick = 1,
    xaxis_tickangle = 45
)

fig.show()

In [ ]:
#test_merge.sort_values(by='party',na_position='first').head(100)

In [ ]:
clean_df_incidents.to_csv('/content/drive/MyDrive/' + 'final_incidents.csv', index=False)
clean_df_poverty.to_csv('/content/drive/MyDrive/' + 'final_poverty.csv', index=False)
clean_districts.to_csv('/content/drive/MyDrive/' + 'final_districts.csv', index=False)

In [ ]:
final_dataset.to_csv('/content/drive/MyDrive/' + 'final_dataset2.csv', index=False)

In [ ]:
test_merge.to_csv('/content/drive/MyDrive/' + 'final_datasetV3.csv', index=False)

# DATA PREPARATION - New Features  GAETANO

*   How many males are involved in the incident w.r.t. the total number of males involved in incidents for the same city and in the same period?
*   How many injured and killed people have been involved w.r.t the total injured and killed people in the same congressional district in a given period of time?
*   Ratio of the number of the killed people in the incident w.r.t. the number of participants in the incident: it is an indicator if the incidents that occur cause killings
*   Ratio of unharmed people in the incident w.r.t. the average of unharmed people involved in incidents for the same period: it is an indicator if the incidents thata occur don't cause any issue to people involved
*   How many male/famale partecipants are involved w.r.t. to the number of total incident in the same period: indicator of how the gender of involved people is distributed across the incidents
* How many adult/child/teen partecipants are involved w.r.t. to the number of total incident in the same period: indicator of how the age of involved people is distributed across the incidents
* Ratio of the number of the injuried people in the incident w.r.t. the number of partecipants in the incident: it is an indicator if the incidents that occur cause injuries
* Ratio of the number of the arrested people in the incident w.r.t. the number of partecipangs in the incident: it is an indicator if the incidents that occur cause arrests
* Ratio of the total number of the incidents w.r.t to the poverty in the same period:it is an indicator whether the poverty index contributes in some way to the increase in accidents - FORSE è PIù UNA CORRELAZIONE CHE UNA FEATURE

**IMPORT DATA**

In [ ]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df = pd.read_csv('/content/final_datasetV3.csv')
print(len(df))

213402

Casting features since when saving the dataframe in csv format it automatically changes the types to float64

In [ ]:
convert_columns = ['min_age_participants', 'avg_age_participants', 'max_age_participants',
                   'n_participants_child', 'n_participants_teen', 'n_participants_adult',
                   'n_males', 'n_females','n_arrested','n_unharmed','candidatevotes','totalvotes']

df[convert_columns] = df[convert_columns].astype('Int64')

In [ ]:
df.sort_values(by=['city_or_county','year','month']).head(10)

,year,month,state,city_or_county,congressional_district,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2,povertyPercentage,party,candidatevotes,totalvotes
13393,2014,1,LOUISIANA,Abbeville,3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0,1,0,1,2,Shot - Wounded/Injured,NaN,20.6,REPUBLICAN,185867,236268
13823,2014,6,LOUISIANA,Abbeville,3,19,20,20,0,0,3,3,0,1,0,0,2,3,"Shot - Dead (murder, accidental, suicide)",Officer Involved Incident,20.6,REPUBLICAN,185867,236268
14211,2014,9,LOUISIANA,Abbeville,3,22,22,22,0,0,3,2,1,0,1,0,2,3,Shot - Wounded/Injured,NaN,20.6,REPUBLICAN,185867,236268
14378,2014,11,LOUISIANA,Abbeville,3,17,18,18,0,1,3,3,0,0,0,0,4,4,Possession (gun(s) found during commission of ...,Brandishing/flourishing/open carry/lost/found,20.6,REPUBLICAN,185867,236268
14481,2014,12,LOUISIANA,Abbeville,3,<NA>,<NA>,<NA>,0,0,3,<NA>,<NA>,0,0,0,3,3,Shots Fired - No Injuries,Institution/Group/Business,20.6,REPUBLICAN,185867,236268
47327,2015,1,LOUISIANA,Abbeville,3,<NA>,<NA>,<NA>,0,0,1,<NA>,<NA>,0,1,0,0,1,Shot - Wounded/Injured,Gun(s) stolen from owner,20.0,REPUBLICAN,185867,236268
47430,2015,2,LOUISIANA,Abbeville,3,<NA>,<NA>,<NA>,0,0,2,<NA>,<NA>,0,2,0,0,2,Shot - Wounded/Injured,NaN,20.0,REPUBLICAN,185867,236268
71245,2016,2,ALABAMA,Abbeville,2,38,52,<NA>,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,Officer Involved Incident,16.0,REPUBLICAN,134886,276584
92587,2016,2,LOUISIANA,Abbeville,3,25,25,25,0,0,2,2,0,0,1,0,1,2,Shot - Wounded/Injured,Possession of gun by felon or prohibited person,19.8,REPUBLICAN,77671,282443
114530,2016,8,SOUTH CAROLINA,Abbeville,3,50,50,50,0,0,2,1,1,0,1,1,0,2,Non-Shooting Incident,Domestic Violence,14.1,REPUBLICAN,196325,269540

In [ ]:
def calcola_moda(serie):
    moda = serie.mode()
    if len(moda) > 0:
        return moda.iloc[0]  # Restituisce il primo elemento in caso di più modi
    return None  # Restituisce None se la serie è vuota

In [ ]:
feature_dataset = None

**FEATURE 1: N_MALES RATIO**

In [ ]:
#FEATURE 1
#How many males are involved in the incident w.r.t. the total number of males involved
#in incidents for the same city and in the same period?

# decommentare se si vuole utilizzare tutto il DF
#df_reduced = df

#decommentare se si vuole utilizzare il DF senza alcune colonne
df_reduced = df.drop(columns=['incident_characteristics1','incident_characteristics2'])
df_reduced = df_reduced.groupby(['state', 'city_or_county', 'congressional_district', 'year']).agg({
        'min_age_participants': 'mean',
        'avg_age_participants': 'mean',
        'min_age_participants':'mean',
        'n_participants_child':'sum',
        'n_participants_teen':'sum',
        'n_participants_adult':'sum',
        'n_males':'sum',
        'n_females':'sum',
        'n_killed':'sum',
        'n_injured':'sum',
        'n_arrested':'sum',
        'n_unharmed':'sum',
        'n_participants':'sum',
        'povertyPercentage':'mean',
        'candidatevotes':'mean',
        'totalvotes':'mean',
        'party':calcola_moda}).reset_index()



result = df_reduced.groupby(['state','city_or_county', 'congressional_district', 'year']).apply(
    lambda x: x['n_males'] / x['n_males'].sum()
    ).reset_index(name='male_participation_rate')



#feature_dataset = feature_dataset.duplicated(subset=['state', 'city_or_county', 'congressional_district', 'year', 'month']).sum()
feature_dataset = result

print(feature_dataset.head(1))

     state city_or_county  congressional_district  year  level_4  \
0  ALABAMA      Abbeville                       2  2016        0

   male_participation_rate
0                      1.0

In [ ]:
feature_dataset = feature_dataset.drop(columns=['level_4'])
print(len(feature_dataset))

41323

**FEATURE 2**

In [ ]:
#FEATURE 2
#How many injured and killed people have been involved w.r.t the total injured and
#killed people in the same congressional district in a given period of time?

# Grouping by congressional district and date (year and month), and calculating the required statistics
#result = df.groupby(['congressional_district', 'year', 'month']).apply(
#    lambda x: {
#        'total_injured': x['n_injured'].sum(),
#        'total_killed': x['n_killed'].sum(),
#        'total_injured_killed': x['n_injured'].sum() + x['n_killed'].sum()
#    }
#).reset_index()

result = df_reduced.groupby(['state', 'city_or_county','congressional_district', 'year']).apply(
    lambda x: x['n_killed'] / x['n_killed'].sum()
).reset_index(name='killed_participation_rate')
#result = result.drop(columns='level_3')

In [ ]:
result = result.drop(columns='level_4')
feature_dataset = pd.merge(feature_dataset, result, on=['state', 'city_or_county', 'congressional_district', 'year'], how='inner')

In [ ]:
print(len(df))
print(len(df_reduced))
print(len(feature_dataset))
print(feature_dataset.head(1))

213402
41323
41323
     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   male_participation_rate  killed_participation_rate
0                      1.0                        NaN

**FEATURE 3**

In [ ]:
# Calculating the ratio of the number of killed people to the number of participants in each incident
df_reduced['killed_participant_ratio'] = df_reduced['n_killed'] / df_reduced['n_participants']

In [ ]:
result = df_reduced[['state', 'city_or_county', 'congressional_district', 'year', 'killed_participant_ratio']]
print(result.head(1))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   killed_participant_ratio
0                       0.0

In [ ]:
feature_dataset = feature_dataset.merge(result, on=['state', 'city_or_county', 'congressional_district', 'year'],how='inner')
print(feature_dataset.head(1))
print(len(feature_dataset))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   male_participation_rate  killed_participation_rate  \
0                      1.0                        NaN

   killed_participant_ratio
0                       0.0
41323

**FEATURE 4**

In [ ]:
# Calculating the average number of unharmed people for each period
avg_unharmed_per_period = df_reduced.groupby(['state', 'city_or_county', 'congressional_district', 'year'])['n_unharmed'].mean().reset_index()
avg_unharmed_per_period.rename(columns={'n_unharmed': 'avg_unharmed'}, inplace=True)

print(avg_unharmed_per_period.head(1))

     state city_or_county  congressional_district  year  avg_unharmed
0  ALABAMA      Abbeville                       2  2016           0.0

In [ ]:
# Merging the average back into the original dataframe
df_reduced = df_reduced.merge(avg_unharmed_per_period, on=['state', 'city_or_county', 'congressional_district', 'year'],how='inner')

print(df_reduced.head(1))

     state city_or_county  congressional_district  year  min_age_participants  \
0  ALABAMA      Abbeville                       2  2016                  38.0

   avg_age_participants  n_participants_child  n_participants_teen  \
0                  52.0                     0                    0

   n_participants_adult  n_males  n_females  n_killed  n_injured  n_arrested  \
0                     1        1          0         0          1           0

   n_unharmed  n_participants  povertyPercentage  candidatevotes  totalvotes  \
0           0               1               16.0        134886.0    276584.0

        party  killed_participant_ratio  avg_unharmed
0  REPUBLICAN                       0.0           0.0

In [ ]:
# Calculating the ratio
df_reduced['unharmed_ratio'] = df_reduced['n_unharmed'] / df_reduced['avg_unharmed']

In [ ]:
result = df_reduced[['state', 'city_or_county', 'congressional_district', 'year', 'unharmed_ratio']]

In [ ]:
feature_dataset = feature_dataset.merge(result, on=['state', 'city_or_county', 'congressional_district', 'year'], how='inner')
print(feature_dataset.head(1))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   male_participation_rate  killed_participation_rate  \
0                      1.0                        NaN

   killed_participant_ratio  unharmed_ratio
0                       0.0             NaN

**FEATURE 5**

In [ ]:
# Calculating the total number of incidents per period
total_incidents_per_period = df_reduced.groupby(['state', 'city_or_county', 'congressional_district', 'year']).size().reset_index(name='total_incidents')

# Summing male and female participants per period
gender_totals_per_period = df_reduced.groupby(['state', 'city_or_county', 'congressional_district', 'year'])[['n_males', 'n_females']].sum().reset_index()

# Merging the total incidents into the gender totals
gender_totals_per_period = gender_totals_per_period.merge(total_incidents_per_period, on=['state', 'city_or_county', 'congressional_district', 'year'])

# Calculating the ratios
gender_totals_per_period['male_participant_ratio'] = gender_totals_per_period['n_males'] / gender_totals_per_period['total_incidents']
gender_totals_per_period['female_participant_ratio'] = gender_totals_per_period['n_females'] / gender_totals_per_period['total_incidents']

result = gender_totals_per_period[['state', 'city_or_county', 'congressional_district', 'year', 'total_incidents', 'male_participant_ratio', 'female_participant_ratio']]

In [ ]:
feature_dataset = feature_dataset.merge(result, on=['state', 'city_or_county', 'congressional_district', 'year'],how='inner')
print(feature_dataset.head(1))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   male_participation_rate  killed_participation_rate  \
0                      1.0                        NaN

   killed_participant_ratio  unharmed_ratio  total_incidents  \
0                       0.0             NaN                1

   male_participant_ratio  female_participant_ratio
0                     1.0                       0.0

**FEATURE 6**

In [ ]:
# Calculating the total number of incidents per period
total_incidents_per_period = df_reduced.groupby(['state', 'city_or_county', 'congressional_district', 'year']).size().reset_index(name='total_incidents')

# Summing child, teen, and adult participants per period
age_group_totals_per_period = df_reduced.groupby(['state', 'city_or_county', 'congressional_district', 'year'])[['n_participants_child', 'n_participants_teen', 'n_participants_adult']].sum().reset_index()

# Merging the total incidents into the age group totals
age_group_totals_per_period = age_group_totals_per_period.merge(total_incidents_per_period, on=['state', 'city_or_county', 'congressional_district', 'year'])

# Calculating the ratios
age_group_totals_per_period['child_participant_ratio'] = age_group_totals_per_period['n_participants_child'] / age_group_totals_per_period['total_incidents']
age_group_totals_per_period['teen_participant_ratio'] = age_group_totals_per_period['n_participants_teen'] / age_group_totals_per_period['total_incidents']
age_group_totals_per_period['adult_participant_ratio'] = age_group_totals_per_period['n_participants_adult'] / age_group_totals_per_period['total_incidents']

result = age_group_totals_per_period[['state', 'city_or_county', 'congressional_district', 'year', 'child_participant_ratio', 'teen_participant_ratio', 'adult_participant_ratio']]

In [ ]:
feature_dataset = feature_dataset.merge(result, on=['state', 'city_or_county', 'congressional_district', 'year'], how='inner')
print(feature_dataset.head(1))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   male_participation_rate  killed_participation_rate  \
0                      1.0                        NaN

   killed_participant_ratio  unharmed_ratio  total_incidents  \
0                       0.0             NaN                1

   male_participant_ratio  female_participant_ratio  child_participant_ratio  \
0                     1.0                       0.0                      0.0

   teen_participant_ratio  adult_participant_ratio
0                     0.0                      1.0

**FEATURE 7**

In [ ]:
# Calculating the ratio of the number of injured people to the number of participants in each incident
df_reduced['injured_participant_ratio'] = df_reduced['n_injured'] / df_reduced['n_participants']

result = df_reduced[['state', 'city_or_county', 'congressional_district', 'year', 'injured_participant_ratio']]
print (result.head(1))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   injured_participant_ratio
0                        1.0

In [ ]:
feature_dataset = feature_dataset.merge(result, on=['state', 'city_or_county', 'congressional_district', 'year'], how='inner')
print(feature_dataset.head(1))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   male_participation_rate  killed_participation_rate  \
0                      1.0                        NaN

   killed_participant_ratio  unharmed_ratio  total_incidents  \
0                       0.0             NaN                1

   male_participant_ratio  female_participant_ratio  child_participant_ratio  \
0                     1.0                       0.0                      0.0

   teen_participant_ratio  adult_participant_ratio  injured_participant_ratio
0                     0.0                      1.0                        1.0

**FEATURE 8**

In [ ]:
# Calculating the ratio of the number of arrested people to the number of participants in each incident
df_reduced['arrested_participant_ratio'] = df_reduced['n_arrested'] / df_reduced['n_participants']

result = df_reduced[['state', 'city_or_county', 'congressional_district', 'year', 'arrested_participant_ratio']]
print (result.head(1))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   arrested_participant_ratio
0                         0.0

In [ ]:
feature_dataset = feature_dataset.merge(result, on=['state', 'city_or_county', 'congressional_district', 'year'], how='inner')
print(feature_dataset.head(1))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   male_participation_rate  killed_participation_rate  \
0                      1.0                        NaN

   killed_participant_ratio  unharmed_ratio  total_incidents  \
0                       0.0             NaN                1

   male_participant_ratio  female_participant_ratio  child_participant_ratio  \
0                     1.0                       0.0                      0.0

   teen_participant_ratio  adult_participant_ratio  injured_participant_ratio  \
0                     0.0                      1.0                        1.0

   arrested_participant_ratio
0                         0.0

**FEATURE 9**

In [ ]:
# Grouping data by year and month to count the number of incidents
incident_counts = df_reduced.groupby(['state', 'city_or_county', 'congressional_district', 'year']).size().reset_index(name='incident_count')

# Averaging the poverty percentage for each period
avg_poverty_per_period = df_reduced.groupby(['state', 'city_or_county', 'congressional_district', 'year'])['povertyPercentage'].mean().reset_index()

# Merging the counts and averages
result = incident_counts.merge(avg_poverty_per_period, on=['state', 'city_or_county', 'congressional_district', 'year'],how='inner')

print (result.head(1))

     state city_or_county  congressional_district  year  incident_count  \
0  ALABAMA      Abbeville                       2  2016               1

   povertyPercentage
0               16.0

In [ ]:
feature_dataset = feature_dataset.merge(result, on=['state', 'city_or_county', 'congressional_district', 'year'],how='inner')
print(feature_dataset.head(1))

     state city_or_county  congressional_district  year  \
0  ALABAMA      Abbeville                       2  2016

   male_participation_rate  killed_participation_rate  \
0                      1.0                        NaN

   killed_participant_ratio  unharmed_ratio  total_incidents  \
0                       0.0             NaN                1

   male_participant_ratio  female_participant_ratio  child_participant_ratio  \
0                     1.0                       0.0                      0.0

   teen_participant_ratio  adult_participant_ratio  injured_participant_ratio  \
0                     0.0                      1.0                        1.0

   arrested_participant_ratio  incident_count  povertyPercentage
0                         0.0               1               16.0

In [ ]:
feature_dataset.to_csv('feature_dataset.csv')

# CLUSTERING

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sn
import scipy.stats as stats
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import geopandas as gpd

In [33]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df = pd.read_csv('/content/drive/MyDrive/final_datasetV3.csv')
df_features = pd.read_csv('/content/drive/MyDrive/feature_dataset.csv')

In [ ]:
df.sort_values(by=['year','state']).head(10)

,year,month,state,city_or_county,congressional_district,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2,povertyPercentage,party,candidatevotes,totalvotes
0,2013,7,ALABAMA,Florence,5,22,22,22,0,0,1,0,1,0,4,1,0,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,17.5,REPUBLICAN,189185,291293
1,2013,12,ALABAMA,Montgomery,2,20,22,25,0,0,9,8,1,3,5,2,0,10,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",17.5,REPUBLICAN,180591,283953
2,2013,4,ARIZONA,Phoenix,6,16,18,22,0,3,4,7,0,2,4,1,0,7,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,REPUBLICAN,179706,293177
3,2013,5,ARIZONA,Apache Junction,4,47,47,47,0,0,5,4,1,0,5,1,1,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7,REPUBLICAN,162907,243760
4,2013,10,ARIZONA,Avondale,3,<NA>,<NA>,<NA>,0,0,4,<NA>,<NA>,0,4,0,0,4,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7,DEMOCRAT,98468,168698
5,2013,10,ARIZONA,Phoenix,7,17,43,66,0,1,4,4,1,5,0,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,DEMOCRAT,104489,127827
6,2013,11,ARIZONA,Phoenix,7,15,19,22,0,1,8,6,2,1,3,5,0,9,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,DEMOCRAT,104489,127827
7,2013,1,CALIFORNIA,Hawthorne,43,20,20,20,0,0,4,1,0,1,3,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",14.9,DEMOCRAT,143123,200894
8,2013,2,CALIFORNIA,Vallejo,5,22,22,22,0,0,5,3,2,1,4,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",14.9,DEMOCRAT,202872,272417
9,2013,2,CALIFORNIA,Lancaster,25,22,28,37,0,0,4,4,0,0,4,0,2,6,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,14.9,REPUBLICAN,129593,236575

In [ ]:
df_features.sort_values(by=['state','city_or_county','year']).head(100)

,Unnamed: 0,state,city_or_county,congressional_district,year,male_participation_rate,killed_participation_rate,killed_participant_ratio,unharmed_ratio,total_incidents,male_participant_ratio,female_participant_ratio,child_participant_ratio,teen_participant_ratio,adult_participant_ratio,injured_participant_ratio,arrested_participant_ratio,incident_count,povertyPercentage
0,0,ALABAMA,Abbeville,2,2016,1.0,NaN,0.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,1.000000,0.000000,1,16.0
1,1,ALABAMA,Abbeville,2,2017,1.0,1.0,1.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,14.7
2,2,ALABAMA,Adamsville,6,2014,1.0,NaN,0.000000,NaN,1,2.0,0.0,0.0,0.0,2.0,1.000000,0.000000,1,16.8
3,3,ALABAMA,Adamsville,6,2016,1.0,NaN,0.000000,1.0,1,2.0,0.0,0.0,0.0,3.0,0.666667,0.000000,1,16.0
6,6,ALABAMA,Adamsville,7,2016,NaN,NaN,0.000000,1.0,1,0.0,0.0,0.0,0.0,2.0,0.000000,0.000000,1,16.0
4,4,ALABAMA,Adamsville,6,2017,1.0,1.0,0.200000,1.0,1,5.0,0.0,0.0,0.0,4.0,0.400000,0.200000,1,14.7
5,5,ALABAMA,Adamsville,6,2019,1.0,NaN,0.000000,1.0,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,14.5
7,7,ALABAMA,Adger,6,2014,1.0,NaN,0.000000,1.0,1,2.0,0.0,0.0,0.0,1.0,0.500000,0.000000,1,16.8
8,8,ALABAMA,Adger,6,2017,1.0,1.0,0.166667,1.0,1,3.0,2.0,0.0,1.0,4.0,0.000000,0.500000,1,14.7
9,9,ALABAMA,Alabaster,6,2014,1.0,NaN,0.000000,1.0,1,2.0,0.0,0.0,0.0,2.0,0.500000,0.000000,1,16.8
10,10,ALABAMA,Alabaster,6,2016,1.0,1.0,0.250000,NaN,1,3.0,1.0,0.0,0.0,4.0,0.000000,0.750000,1,16.0
11,11,ALABAMA,Alberta,7,2017,1.0,1.0,0.500000,NaN,1,1.0,1.0,0.0,0.0,2.0,0.500000,0.000000,1,14.7
12,12,ALABAMA,Albertville,4,2014,1.0,1.0,0.083333,1.0,1,8.0,2.0,0.0,2.0,9.0,0.166667,0.250000,1,16.8
13,13,ALABAMA,Albertville,4,2015,1.0,NaN,0.000000,1.0,1,3.0,0.0,0.0,0.0,3.0,0.000000,0.666667,1,15.8
14,14,ALABAMA,Albertville,4,2016,1.0,1.0,0.090909,NaN,1,9.0,1.0,0.0,1.0,10.0,0.363636,0.545455,1,16.0
15,15,ALABAMA,Albertville,4,2017,1.0,1.0,0.166667,NaN,1,5.0,0.0,3.0,0.0,6.0,0.500000,0.333333,1,14.7
16,16,ALABAMA,Albertville,4,2018,1.0,NaN,0.000000,NaN,1,1.0,0.0,1.0,1.0,0.0,0.000000,1.000000,1,14.6
17,17,ALABAMA,Albertville,4,2019,1.0,NaN,0.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.000000,1.000000,1,14.5
18,18,ALABAMA,Albertville,4,2020,1.0,NaN,0.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,1.000000,0.000000,1,14.8
19,19,ALABAMA,Alexander City,3,2014,1.0,1.0,0.300000,1.0,1,9.0,0.0,0.0,0.0,10.0,0.200000,0.000000,1,16.8
20,20,ALABAMA,Alexander City,3,2016,1.0,1.0,0.500000,NaN,1,4.0,0.0,0.0,0.0,4.0,0.250000,0.500000,1,16.0
21,21,ALABAMA,Alexander City,3,2017,1.0,1.0,0.200000,NaN,1,22.0,1.0,1.0,2.0,23.0,0.080000,0.680000,1,14.7
22,22,ALABAMA,Alexander City,3,2018,1.0,NaN,0.000000,NaN,1,3.0,0.0,0.0,0.0,2.0,0.666667,0.333333,1,14.6
23,23,ALABAMA,Alexander City,3,2019,1.0,NaN,0.000000,1.0,1,3.0,0.0,0.0,0.0,3.0,0.000000,0.000000,1,14.5
24,24,ALABAMA,Aliceville,7,2014,NaN,1.0,1.000000,NaN,1,0.0,1.0,0.0,0.0,1.0,0.000000,0.000000,1,16.8
25,25,ALABAMA,Aliceville,7,2016,1.0,NaN,0.000000,NaN,1,1.0,0.0,0.0,1.0,3.0,0.750000,0.250000,1,16.0
26,26,ALABAMA,Alpine,3,2017,1.0,1.0,0.666667,NaN,1,2.0,1.0,0.0,0.0,3.0,0.000000,0.333333,1,14.7
27,27,ALABAMA,Andalusia,2,2014,1.0,NaN,0.000000,1.0,1,1.0,0.0,0.0,0.0,3.0,0.000000,0.000000,1,16.8
28,28,ALABAMA,Andalusia,2,2015,1.0,1.0,1.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,15.8
29,29,ALABAMA,Andalusia,2,2016,1.0,NaN,0.000000,1.0,1,2.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1,16.0
30,30,ALABAMA,Andalusia,2,2017,1.0,1.0,0.333333,NaN,1,2.0,1.0,0.0,0.0,3.0,0.000000,0.666667,1,14.7
31,31,ALABAMA,Andalusia,2,2018,1.0,NaN,0.000000,NaN,1,3.0,0.0,0.0,0.0,3.0,0.333333,0.666667,1,14.6
32,32,ALABAMA,Andalusia,2,2019,1.0,NaN,0.000000,1.0,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,14.5
33,33,ALABAMA,Anderson,5,2019,1.0,1.0,1.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,14.5
34,34,ALABAMA,Anniston,3,2014,1.0,1.0,0.250000,1.0,1,12.0,3.0,2.0,1.0,13.0,0.437500,0.000000,1,16.8
35,35,ALABAMA,Anniston,3,2015,1.0,1.0,0.315789,1.0,1,10.0,2.0,0.0,1.0,17.0,0.421053,0.105263,1,15.8
36,36,ALABAMA,Anniston,3,2016,1.0,1.0,0.360000,1.0,1,14.0,4.0,0.0,1.0,23.0,0.320000,0.160000,1,16.0
37,37,ALABAMA,Anniston,3,2017,1.0,1.0,0.444444,1.0,1,27.0,8.0,1.0,1.0,35.0,0.333333,0.194444,1,14.7
38,38,ALABAMA,Anniston,3,2018,1.0,NaN,0.000000,NaN,1,4.0,0.0,1.0,0.0,4.0,0.750000,0.250000,1,14.6
39,39,ALABAMA,Anniston,3,2019,1.0,NaN,0.000000,1.0,1,4.0,0.0,1.0,0.0,4.0,0.200000,0.000000,1,14.5
40,40,ALABAMA,Anniston,3,2020,1.0,NaN,0.000000,NaN,1,2.0,0.0,0.0,0.0,2.0,0.500000,0.500000,1,14.8
41,41,ALABAMA,Arab,4,2014,1.0,1.0,0.250000,NaN,1,2.0,1.0,1.0,0.0,3.0,0.500000,0.000000,1,16.8
42,42,ALABAMA,Arab,4,2016,1.0,1.0,0.111111,1.0,1,7.0,2.0,1.0,0.0,8.0,0.333333,0.444444,1,16.0
43,43,ALABAMA,Arab,4,2017,1.0,NaN,0.000000,1.0,1,4.0,2.0,2.0,0.0,5.0,0.166667,0.500000,1,14.7
44,44,ALABAMA,Arab,4,2018,1.0,NaN,0.000000,NaN,1,2.0,0.0,0.0,1.0,2.0,0.000000,1.000000,1,14.6
45,45,ALABAMA,Arab,4,2019,1.0,NaN,0.000000,1.0,1,6.0,1.0,0.0,0.0,7.0,0.142857,0.000000,1,14.5
46,46,ALABAMA,Ariton,2,2014,1.0,1.0,0.500000,1.0,1,2.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,16.8
47,47,ALABAMA,Ariton,2,2016,1.0,1.0,0.333333,1.0,1,1.0,0.0,1.0,0.0,1.0,0.000000,0.000000,1,16.0
48,48,ALABAMA,Ashford,2,2014,1.0,1.0,1.000000,NaN,1,1.0,1.0,0.0,0.0,2.0,0.000000,0.000000,1,16.8
49,49,ALABAMA,Ashford,2,2019,1.0,1.0,1.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,14.5
50,50,ALABAMA,Ashland,4,2019,1.0,NaN,0.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.500000,0.000000,1,14.5
51,51,ALABAMA,Ashville,3,2016,1.0,1.0,0.500000,1.0,1,1.0,1.0,0.0,0.0,2.0,0.000000,0.000000,1,16.0
52,52,ALABAMA,Ashville,3,2017,1.0,1.0,0.500000,NaN,1,2.0,0.0,0.0,0.0,2.0,0.000000,0.500000,1,14.7
53,53,ALABAMA,Athens,5,2014,1.0,1.0,0.250000,1.0,1,4.0,2.0,0.0,0.0,6.0,0.500000,0.000000,1,16.8
54,54,ALABAMA,Athens,5,2015,1.0,NaN,0.000000,1.0,1,6.0,5.0,0.0,1.0,10.0,0.272727,0.636364,1,15.8
55,55,ALABAMA,Athens,5,2016,1.0,1.0,0.066667,1.0,1,14.0,0.0,0.0,1.0,14.0,0.133333,0.600000,1,16.0
56,56,ALABAMA,Athens,5,2017,1.0,1.0,0.128205,1.0,1,33.0,5.0,4.0,4.0,32.0,0.358974,0.461538,1,14.7
57,57,ALABAMA,Athens,5,2018,1.0,1.0,0.250000,NaN,1,7.0,1.0,1.0,0.0,8.0,0.125000,0.625000,1,14.6
58,58,ALABAMA,Athens,5,2019,1.0,NaN,0.000000,1.0,1,2.0,0.0,0.0,0.0,3.0,0.333333,0.000000,1,14.5
59,59,ALABAMA,Athens,5,2020,1.0,NaN,0.000000,NaN,1,2.0,0.0,0.0,0.0,2.0,1.000000,0.000000,1,14.8
60,60,ALABAMA,Atmore,1,2016,1.0,1.0,0.250000,1.0,1,7.0,1.0,1.0,0.0,7.0,0.250000,0.375000,1,16.0
61,61,ALABAMA,Atmore,1,2017,1.0,1.0,0.333333,1.0,1,7.0,1.0,1.0,0.0,7.0,0.222222,0.222222,1,14.7
62,62,ALABAMA,Atmore,1,2018,1.0,1.0,0.400000,1.0,1,3.0,0.0,0.0,2.0,2.0,0.200000,0.200000,1,14.6
63,63,ALABAMA,Atmore (Canoe),1,2016,1.0,NaN,0.000000,NaN,1,2.0,0.0,0.0,0.0,2.0,0.500000,0.500000,1,16.0
64,64,ALABAMA,Attalla,4,2014,1.0,NaN,0.000000,NaN,1,1.0,2.0,0.0,0.0,2.0,0.000000,0.333333,1,16.8
65,65,ALABAMA,Attalla,4,2016,1.0,NaN,0.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.000000,1.000000,1,16.0
66,66,ALABAMA,Attalla,4,2017,1.0,NaN,0.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,1.000000,0.000000,1,14.7
68,68,ALABAMA,Auburn,3,2014,1.0,1.0,0.083333,1.0,1,21.0,3.0,0.0,0.0,24.0,0.375000,0.083333,1,16.8
67,67,ALABAMA,Auburn,1,2015,1.0,NaN,0.000000,NaN,1,3.0,0.0,0.0,0.0,3.0,0.333333,0.666667,1,15.8
69,69,ALABAMA,Auburn,3,2015,1.0,1.0,0.250000,NaN,1,4.0,0.0,0.0,0.0,4.0,0.000000,0.750000,1,15.8
70,70,ALABAMA,Auburn,3,2016,1.0,1.0,0.352941,1.0,1,14.0,1.0,1.0,2.0,16.0,0.176471,0.352941,1,16.0
75,75,ALABAMA,Auburn,8,2016,1.0,NaN,0.000000,NaN,1,1.0,1.0,1.0,0.0,1.0,1.000000,0.000000,1,16.0
71,71,ALABAMA,Auburn,3,2017,1.0,1.0,0.545455,NaN,1,9.0,2.0,0.0,0.0,11.0,0.000000,0.454545,1,14.7
72,72,ALABAMA,Auburn,3,2018,1.0,NaN,0.000000,1.0,1,6.0,0.0,0.0,0.0,5.0,0.428571,0.428571,1,14.6
76,76,ALABAMA,Auburn,8,2018,1.0,1.0,0.750000,NaN,1,4.0,0.0,0.0,0.0,4.0,0.000000,0.250000,1,14.6
73,73,ALABAMA,Auburn,3,2019,1.0,1.0,0.166667,1.0,1,4.0,1.0,0.0,0.0,5.0,0.166667,0.000000,1,14.5
74,74,ALABAMA,Auburn,3,2020,1.0,NaN,0.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,1.000000,0.000000,1,14.8
77,77,ALABAMA,Auburn,3,2019,1.0,NaN,0.000000,1.0,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,14.5
78,78,ALABAMA,Autaugaville,2,2014,1.0,1.0,0.500000,1.0,1,2.0,0.0,0.0,0.0,2.0,0.000000,0.000000,1,16.8
79,79,ALABAMA,Autaugaville,2,2015,NaN,NaN,0.000000,NaN,1,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,1,15.8
80,80,ALABAMA,Autaugaville,2,2017,NaN,NaN,0.000000,NaN,1,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,1,14.7
81,81,ALABAMA,Autaugaville,2,2018,1.0,NaN,0.000000,1.0,1,1.0,1.0,0.0,0.0,2.0,0.000000,0.500000,1,14.6
82,82,ALABAMA,Autaugaville,2,2020,1.0,1.0,1.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,14.8
83,83,ALABAMA,Axis,1,2014,1.0,NaN,0.000000,1.0,1,2.0,0.0,0.0,0.0,2.0,0.500000,0.000000,1,16.8
84,84,ALABAMA,Baileyton,4,2017,1.0,1.0,0.333333,1.0,1,3.0,0.0,0.0,0.0,3.0,0.000000,0.333333,1,14.7
85,85,ALABAMA,Baldwin (county),1,2015,1.0,NaN,0.000000,1.0,1,1.0,2.0,0.0,0.0,3.0,0.000000,0.666667,1,15.8
86,86,ALABAMA,Baldwin (county),1,2016,1.0,1.0,1.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,16.0
87,87,ALABAMA,Baldwin County,1,2020,1.0,1.0,1.000000,NaN,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,14.8
88,88,ALABAMA,Bay Minette,1,2014,1.0,NaN,0.000000,1.0,1,5.0,0.0,0.0,0.0,5.0,0.000000,0.000000,1,16.8
89,89,ALABAMA,Bay Minette,1,2016,1.0,NaN,0.000000,1.0,1,2.0,0.0,0.0,1.0,1.0,0.500000,0.000000,1,16.0
90,90,ALABAMA,Bay Minette,1,2017,1.0,1.0,0.250000,NaN,1,6.0,0.0,0.0,0.0,8.0,0.250000,0.500000,1,14.7
91,91,ALABAMA,Bay Minette,1,2018,1.0,1.0,0.142857,1.0,1,6.0,1.0,1.0,0.0,7.0,0.428571,0.142857,1,14.6
92,92,ALABAMA,Bay Minette,1,2019,1.0,NaN,0.000000,1.0,1,1.0,1.0,0.0,0.0,1.0,0.000000,0.500000,1,14.5
93,93,ALABAMA,Bay Minette,1,2019,1.0,NaN,0.000000,1.0,1,2.0,0.0,0.0,0.0,2.0,0.000000,0.000000,1,14.5
94,94,ALABAMA,Bayou La Batre,1,2017,1.0,NaN,0.000000,NaN,1,1.0,0.0,0.0,1.0,1.0,0.000000,1.000000,1,14.7
95,95,ALABAMA,Bessemer,6,2014,1.0,NaN,0.000000,1.0,1,1.0,0.0,0.0,0.0,1.0,0.000000,0.000000,1,16.8
101,101,ALABAMA,Bessemer,7,2014,1.0,1.0,0.250000,1.0,1,10.0,3.0,0.0,0.0,16.0,0.187500,0.062500,1,16.8
96,96,ALABAMA,Bessemer,6,2015,1.0,1.0,0.333333,NaN,1,3.0,0.0,0.0,0.0,3.0,0.333333,0.333333,1,15.8
102,102,ALABAMA,Bessemer,7,2015,1.0,1.0,0.333333,1.0,1,18.0,6.0,0.0,1.0,21.0,0.200000,0.100000,1,15.8
97,97,ALABAMA,Bessemer,6,2016,1.0,1.0,0.176471,1.0,1,14.0,3.0,3.0,0.0,16.0,0.352941,0.411765,1,16.0

In [ ]:
convert_columns = ['min_age_participants', 'avg_age_participants', 'max_age_participants',
                   'n_participants_child', 'n_participants_teen', 'n_participants_adult',
                   'n_males', 'n_females','n_arrested','n_unharmed','candidatevotes','totalvotes']

df[convert_columns] = df[convert_columns].astype('Int64')

In [ ]:
df.head(10)

,year,month,state,city_or_county,congressional_district,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2,povertyPercentage,party,candidatevotes,totalvotes
0,2013,7,ALABAMA,Florence,5,22,22,22,0,0,1,0,1,0,4,1,0,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,17.5,REPUBLICAN,189185,291293
1,2013,12,ALABAMA,Montgomery,2,20,22,25,0,0,9,8,1,3,5,2,0,10,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",17.5,REPUBLICAN,180591,283953
2,2013,4,ARIZONA,Phoenix,6,16,18,22,0,3,4,7,0,2,4,1,0,7,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,REPUBLICAN,179706,293177
3,2013,5,ARIZONA,Apache Junction,4,47,47,47,0,0,5,4,1,0,5,1,1,5,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7,REPUBLICAN,162907,243760
4,2013,10,ARIZONA,Avondale,3,<NA>,<NA>,<NA>,0,0,4,<NA>,<NA>,0,4,0,0,4,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,18.7,DEMOCRAT,98468,168698
5,2013,10,ARIZONA,Phoenix,7,17,43,66,0,1,4,4,1,5,0,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,DEMOCRAT,104489,127827
6,2013,11,ARIZONA,Phoenix,7,15,19,22,0,1,8,6,2,1,3,5,0,9,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",18.7,DEMOCRAT,104489,127827
7,2013,1,CALIFORNIA,Hawthorne,43,20,20,20,0,0,4,1,0,1,3,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",14.9,DEMOCRAT,143123,200894
8,2013,2,CALIFORNIA,Vallejo,5,22,22,22,0,0,5,3,2,1,4,0,0,5,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",14.9,DEMOCRAT,202872,272417
9,2013,2,CALIFORNIA,Lancaster,25,22,28,37,0,0,4,4,0,0,4,0,2,6,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,14.9,REPUBLICAN,129593,236575

In [ ]:
#df.dtypes

**K-MEANS**

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

In [ ]:
selected_columns = [
    'min_age_participants',
    'avg_age_participants',
    'max_age_participants',
    'n_participants_child',
    'n_participants_teen',
    'n_participants_adult',
    'n_males',
    'n_females',
    'n_killed',
    'n_injured',
    'n_arrested',
    'n_unharmed',
    'n_participants',
    'povertyPercentage',
    'candidatevotes',
    'totalvotes'
]
X = df[selected_columns]

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
wcss = []
for i in range(2, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', max_iter=300, n_init=10, random_state=0)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.plot(range(2, 11), wcss, marker='o')
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

ValueError: ignored



# DATA CORRELATION

# TEST

*   How many males are involved in the incident w.r.t. the total number of males involved in incidents for the same city and in the same period?
*   How many injured and killed people have been involved w.r.t the total injured and killed people in the same congressional district in a given period of time?
*   Ratio of the number of the killed people in the incident w.r.t. the number of participants in the incident: it is an indicator if the incidents that occur cause killings
*   Ratio of unharmed people in the incident w.r.t. the average of unharmed people involved in incidents for the same period: it is an indicator if the incidents thata occur don't cause any issue to people involved
*   How many male/famale partecipants are involved w.r.t. to the number of total incident in the same period: indicator of how the gender of involved people is distributed across the incidents
* How many adult/child/teen partecipants are involved w.r.t. to the number of total incident in the same period: indicator of how the age of involved people is distributed across the incidents
* Ratio of the number of the injuried people in the incident w.r.t. the number of partecipants in the incident: it is an indicator if the incidents that occur cause injuries
* Ratio of the number of the arrested people in the incident w.r.t. the number of partecipangs in the incident: it is an indicator if the incidents that occur cause arrests
* Ratio of the total number of the incidents w.r.t to the poverty in the same period:it is an indicator whether the poverty index contributes in some way to the increase in accidents - FORSE è PIù UNA CORRELAZIONE CHE UNA FEATURE

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import seaborn as sn
import scipy.stats as stats
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import geopandas as gpd

In [3]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df = pd.read_csv('/content/drive/MyDrive/final_datasetV3.csv')
print(len(df))

213402

In [4]:
feature1 = pd.read_csv('/content/drive/MyDrive/feature1.csv')
feature2 = pd.read_csv('/content/drive/MyDrive/feature2.csv')
feature3 = pd.read_csv('/content/drive/MyDrive/feature3.csv')
feature4 = pd.read_csv('/content/drive/MyDrive/feature4.csv')
feature5 = pd.read_csv('/content/drive/MyDrive/feature5.csv')

In [5]:
convert_columns = ['min_age_participants', 'avg_age_participants', 'max_age_participants',
                   'n_participants_child', 'n_participants_teen', 'n_participants_adult',
                   'n_males', 'n_females','n_arrested','n_unharmed','candidatevotes','totalvotes']

df[convert_columns] = df[convert_columns].astype('Int64')

In [6]:
df.sort_values(by=['state','city_or_county','year','month']).head(100)

,year,month,state,city_or_county,congressional_district,min_age_participants,avg_age_participants,max_age_participants,n_participants_child,n_participants_teen,n_participants_adult,n_males,n_females,n_killed,n_injured,n_arrested,n_unharmed,n_participants,incident_characteristics1,incident_characteristics2,povertyPercentage,party,candidatevotes,totalvotes
71245,2016,2,ALABAMA,Abbeville,2,38,52,<NA>,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,Officer Involved Incident,16.0,REPUBLICAN,134886,276584
124508,2017,6,ALABAMA,Abbeville,2,29,29,29,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",Officer Involved Incident,14.7,REPUBLICAN,134886,276584
542,2014,5,ALABAMA,Adamsville,6,39,39,39,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,BB/Pellet/Replica gun,16.8,REPUBLICAN,135945,178449
770,2014,8,ALABAMA,Adamsville,6,33,33,33,0,0,1,1,0,0,1,0,0,1,Officer Involved Incident,Officer Involved Shooting - subject/suspect/pe...,16.8,REPUBLICAN,135945,178449
71215,2016,1,ALABAMA,Adamsville,7,<NA>,<NA>,<NA>,0,0,2,<NA>,<NA>,0,0,0,2,2,Shots Fired - No Injuries,Defensive Use,16.0,DEMOCRAT,229330,233028
71486,2016,4,ALABAMA,Adamsville,6,28,28,28,0,0,2,2,0,0,1,0,1,2,Shot - Wounded/Injured,NaN,16.0,REPUBLICAN,245313,329306
72207,2016,11,ALABAMA,Adamsville,6,<NA>,<NA>,<NA>,0,0,1,<NA>,<NA>,0,1,0,0,1,Shot - Wounded/Injured,NaN,16.0,REPUBLICAN,245313,329306
124070,2017,3,ALABAMA,Adamsville,6,96,<NA>,72,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,NaN,14.7,REPUBLICAN,245313,329306
124158,2017,3,ALABAMA,Adamsville,6,61,61,61,0,0,1,1,0,0,0,1,0,1,Shots Fired - No Injuries,NaN,14.7,REPUBLICAN,245313,329306
124839,2017,9,ALABAMA,Adamsville,6,38,38,38,0,0,2,3,0,1,1,0,1,3,"Shot - Dead (murder, accidental, suicide)",Home Invasion,14.7,REPUBLICAN,245313,329306
190985,2019,10,ALABAMA,Adamsville,6,<NA>,<NA>,<NA>,0,0,1,1,0,0,0,0,1,1,Institution/Group/Business,Non-Shooting Incident,14.5,REPUBLICAN,192542,278328
804,2014,9,ALABAMA,Adger,6,59,59,59,0,0,1,2,0,0,1,0,1,2,Shot - Wounded/Injured,NaN,16.8,REPUBLICAN,135945,178449
124312,2017,5,ALABAMA,Adger,6,28,29,30,0,0,3,3,0,0,0,3,0,4,Non-Shooting Incident,Home Invasion,14.7,REPUBLICAN,245313,329306
125151,2017,11,ALABAMA,Adger,6,15,15,15,0,1,1,0,2,1,0,0,1,2,"Shot - Dead (murder, accidental, suicide)",Non-Aggression Incident,14.7,REPUBLICAN,245313,329306
964,2014,12,ALABAMA,Alabaster,6,54,54,55,0,0,2,2,0,0,1,0,1,2,Shot - Wounded/Injured,NaN,16.8,REPUBLICAN,135945,178449
71509,2016,4,ALABAMA,Alabaster,6,24,34,43,0,0,2,2,0,0,0,2,0,2,Non-Shooting Incident,ATF/LE Confiscation/Raid/Arrest,16.0,REPUBLICAN,245313,329306
72121,2016,10,ALABAMA,Alabaster,6,43,48,54,0,0,2,1,1,1,0,1,0,2,"Shot - Dead (murder, accidental, suicide)",Institution/Group/Business,16.0,REPUBLICAN,245313,329306
124428,2017,6,ALABAMA,Alberta,7,50,50,50,0,0,2,1,1,1,1,0,0,2,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",14.7,DEMOCRAT,229330,233028
284,2014,1,ALABAMA,Albertville,4,20,22,25,0,0,5,4,1,1,0,0,4,5,"Shot - Dead (murder, accidental, suicide)",NaN,16.8,REPUBLICAN,132831,134752
475,2014,4,ALABAMA,Albertville,4,18,18,18,0,2,1,1,0,0,2,0,1,3,Shot - Wounded/Injured,NaN,16.8,REPUBLICAN,132831,134752
598,2014,6,ALABAMA,Albertville,4,23,27,31,0,0,3,3,1,0,0,3,1,4,Non-Shooting Incident,Drug involvement,16.8,REPUBLICAN,132831,134752
32744,2015,1,ALABAMA,Albertville,4,19,22,24,0,0,3,3,0,0,0,2,1,3,Shots Fired - No Injuries,Home Invasion,15.8,REPUBLICAN,132831,134752
71316,2016,3,ALABAMA,Albertville,4,39,57,76,0,0,3,3,0,0,0,3,0,3,Non-Shooting Incident,ATF/LE Confiscation/Raid/Arrest,16.0,REPUBLICAN,235925,239444
71650,2016,6,ALABAMA,Albertville,4,43,50,57,0,0,2,2,0,1,0,1,0,2,"Shot - Dead (murder, accidental, suicide)",NaN,16.0,REPUBLICAN,235925,239444
71774,2016,7,ALABAMA,Albertville,4,18,18,18,0,0,2,2,0,0,1,1,0,2,Shot - Wounded/Injured,NaN,16.0,REPUBLICAN,235925,239444
72022,2016,10,ALABAMA,Albertville,4,<NA>,<NA>,<NA>,0,0,2,1,1,0,1,1,0,2,Shot - Wounded/Injured,NaN,16.0,REPUBLICAN,235925,239444
72125,2016,11,ALABAMA,Albertville,4,12,12,12,0,1,1,1,0,0,2,0,0,2,Shot - Wounded/Injured,"Drive-by (car to street, car to car)",16.0,REPUBLICAN,235925,239444
124271,2017,4,ALABAMA,Albertville,4,<NA>,<NA>,<NA>,0,0,1,<NA>,<NA>,0,1,0,0,1,Shot - Wounded/Injured,NaN,14.7,REPUBLICAN,235925,239444
124473,2017,6,ALABAMA,Albertville,4,41,<NA>,0,1,0,1,1,0,0,0,1,0,1,Shots Fired - No Injuries,Domestic Violence,14.7,REPUBLICAN,235925,239444
124639,2017,7,ALABAMA,Albertville,4,<NA>,<NA>,<NA>,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,NaN,14.7,REPUBLICAN,235925,239444
125109,2017,11,ALABAMA,Albertville,4,<NA>,<NA>,0,1,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,14.7,REPUBLICAN,235925,239444
125177,2017,12,ALABAMA,Albertville,4,0,<NA>,<NA>,1,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,Road rage,14.7,REPUBLICAN,235925,239444
125227,2017,12,ALABAMA,Albertville,4,33,<NA>,<NA>,0,0,1,1,0,0,0,1,0,1,Shots Fired - No Injuries,Officer Involved Incident,14.7,REPUBLICAN,235925,239444
178499,2018,2,ALABAMA,Albertville,4,0,<NA>,<NA>,1,1,0,1,0,0,0,1,0,1,Non-Shooting Incident,School Incident,14.6,REPUBLICAN,184255,230969
191047,2019,12,ALABAMA,Albertville,4,<NA>,<NA>,<NA>,0,0,1,1,0,0,0,1,0,1,Possession (gun(s) found during commission of ...,NaN,14.5,REPUBLICAN,184255,230969
204781,2020,5,ALABAMA,Albertville,4,<NA>,<NA>,<NA>,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,NaN,14.8,REPUBLICAN,261553,318029
375,2014,2,ALABAMA,Alexander City,3,60,68,75,0,0,2,2,0,1,0,0,1,2,"Shot - Dead (murder, accidental, suicide)",NaN,16.8,REPUBLICAN,103558,156620
419,2014,3,ALABAMA,Alexander City,3,21,21,21,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",Officer Involved Incident,16.8,REPUBLICAN,103558,156620
550,2014,5,ALABAMA,Alexander City,3,39,49,59,0,0,5,5,0,0,1,0,4,5,Shot - Wounded/Injured,Home Invasion,16.8,REPUBLICAN,103558,156620
699,2014,7,ALABAMA,Alexander City,3,58,58,58,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",Suicide^,16.8,REPUBLICAN,103558,156620
864,2014,10,ALABAMA,Alexander City,3,22,22,22,0,0,1,<NA>,<NA>,0,1,0,0,1,Shot - Wounded/Injured,Accidental Shooting,16.8,REPUBLICAN,103558,156620
71508,2016,4,ALABAMA,Alexander City,3,51,51,51,0,0,2,2,0,1,0,1,0,2,"Shot - Dead (murder, accidental, suicide)",NaN,16.0,REPUBLICAN,192164,287104
72098,2016,10,ALABAMA,Alexander City,3,19,24,28,0,0,2,2,0,1,1,1,0,2,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",16.0,REPUBLICAN,192164,287104
123883,2017,1,ALABAMA,Alexander City,3,<NA>,<NA>,<NA>,0,2,0,<NA>,<NA>,0,0,2,0,2,Institution/Group/Business,Shots Fired - No Injuries,14.7,REPUBLICAN,192164,287104
123896,2017,1,ALABAMA,Alexander City,3,20,22,27,0,0,3,3,0,1,0,2,0,3,"Shot - Dead (murder, accidental, suicide)",NaN,14.7,REPUBLICAN,192164,287104
124072,2017,3,ALABAMA,Alexander City,3,18,18,18,0,0,2,2,0,1,0,0,0,2,"Shot - Dead (murder, accidental, suicide)","Drive-by (car to street, car to car)",14.7,REPUBLICAN,192164,287104
124214,2017,4,ALABAMA,Alexander City,3,21,21,21,0,0,2,2,0,0,1,1,0,2,Shot - Wounded/Injured,NaN,14.7,REPUBLICAN,192164,287104
124268,2017,4,ALABAMA,Alexander City,3,7,<NA>,<NA>,1,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,NaN,14.7,REPUBLICAN,192164,287104
124355,2017,5,ALABAMA,Alexander City,3,33,<NA>,87,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,14.7,REPUBLICAN,192164,287104
124530,2017,6,ALABAMA,Alexander City,3,19,22,25,0,0,2,2,0,0,0,2,0,2,Shots Fired - No Injuries,NaN,14.7,REPUBLICAN,192164,287104
124666,2017,7,ALABAMA,Alexander City,3,18,24,30,0,0,2,1,1,0,0,2,0,2,Non-Shooting Incident,Drug involvement,14.7,REPUBLICAN,192164,287104
124727,2017,8,ALABAMA,Alexander City,3,<NA>,76,52,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",Suicide^,14.7,REPUBLICAN,192164,287104
124865,2017,9,ALABAMA,Alexander City,3,21,21,21,0,0,2,2,0,1,0,1,0,2,"Shot - Dead (murder, accidental, suicide)",NaN,14.7,REPUBLICAN,192164,287104
125184,2017,12,ALABAMA,Alexander City,3,30,44,67,0,0,5,5,0,0,0,5,0,5,Non-Shooting Incident,Drug involvement,14.7,REPUBLICAN,192164,287104
125202,2017,12,ALABAMA,Alexander City,3,33,33,33,0,0,1,1,0,0,0,1,0,1,Non-Shooting Incident,ATF/LE Confiscation/Raid/Arrest,14.7,REPUBLICAN,192164,287104
125209,2017,12,ALABAMA,Alexander City,3,22,22,22,0,0,1,1,0,0,0,1,0,1,Non-Shooting Incident,ATF/LE Confiscation/Raid/Arrest,14.7,REPUBLICAN,192164,287104
178539,2018,2,ALABAMA,Alexander City,3,27,27,27,0,0,1,2,0,0,1,1,0,2,Shot - Wounded/Injured,NaN,14.6,REPUBLICAN,147770,231915
178543,2018,2,ALABAMA,Alexander City,3,49,49,49,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,NaN,14.6,REPUBLICAN,147770,231915
190939,2019,9,ALABAMA,Alexander City,3,<NA>,<NA>,<NA>,0,0,3,3,0,0,0,0,3,4,Shots Fired - No Injuries,Armed robbery with injury/death and/or evidenc...,14.5,REPUBLICAN,147770,231915
811,2014,9,ALABAMA,Aliceville,7,29,29,29,0,0,1,0,1,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",Accidental Shooting,16.8,DEMOCRAT,133687,135899
71782,2016,7,ALABAMA,Aliceville,7,16,28,42,0,1,3,1,0,0,3,1,0,4,Shot - Wounded/Injured,NaN,16.0,DEMOCRAT,229330,233028
124389,2017,5,ALABAMA,Alpine,3,32,34,35,0,0,2,1,1,1,0,1,0,2,"Shot - Dead (murder, accidental, suicide)",NaN,14.7,REPUBLICAN,192164,287104
125045,2017,11,ALABAMA,Alpine,3,32,32,32,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,14.7,REPUBLICAN,192164,287104
290,2014,1,ALABAMA,Andalusia,2,34,34,34,0,0,3,1,0,0,0,0,3,3,Non-Shooting Incident,NaN,16.8,REPUBLICAN,113103,167952
33061,2015,7,ALABAMA,Andalusia,2,29,29,29,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",Officer Involved Incident,15.8,REPUBLICAN,113103,167952
71640,2016,6,ALABAMA,Andalusia,2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,0,0,0,0,2,2,Shots Fired - No Injuries,Home Invasion,16.0,REPUBLICAN,134886,276584
124055,2017,2,ALABAMA,Andalusia,2,21,21,21,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,14.7,REPUBLICAN,134886,276584
124443,2017,6,ALABAMA,Andalusia,2,32,32,33,0,0,2,1,1,0,0,2,0,2,Non-Shooting Incident,ATF/LE Confiscation/Raid/Arrest,14.7,REPUBLICAN,134886,276584
178592,2018,3,ALABAMA,Andalusia,2,18,19,20,0,0,3,3,0,0,1,2,0,3,Shot - Wounded/Injured,NaN,14.6,REPUBLICAN,138879,226230
190806,2019,6,ALABAMA,Andalusia,2,<NA>,<NA>,<NA>,0,0,1,1,0,0,0,0,1,2,Armed robbery with injury/death and/or evidenc...,Institution/Group/Business,14.5,REPUBLICAN,138879,226230
190714,2019,4,ALABAMA,Anderson,5,<NA>,<NA>,<NA>,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",Drug involvement,14.5,REPUBLICAN,159063,260673
294,2014,1,ALABAMA,Anniston,3,22,28,34,0,0,2,1,1,1,1,0,0,2,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",16.8,REPUBLICAN,103558,156620
538,2014,5,ALABAMA,Anniston,3,38,42,46,0,0,2,1,1,1,0,0,0,2,"Shot - Dead (murder, accidental, suicide)",NaN,16.8,REPUBLICAN,103558,156620
603,2014,6,ALABAMA,Anniston,3,32,44,55,0,0,2,2,0,1,0,0,1,2,"Shot - Dead (murder, accidental, suicide)",NaN,16.8,REPUBLICAN,103558,156620
681,2014,7,ALABAMA,Anniston,3,11,11,11,1,1,0,2,0,0,1,0,1,2,Shot - Wounded/Injured,Accidental Shooting,16.8,REPUBLICAN,103558,156620
712,2014,7,ALABAMA,Anniston,3,11,11,11,1,0,1,2,0,0,1,0,1,2,Shot - Wounded/Injured,Accidental Shooting,16.8,REPUBLICAN,103558,156620
716,2014,7,ALABAMA,Anniston,3,20,20,20,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,NaN,16.8,REPUBLICAN,103558,156620
912,2014,12,ALABAMA,Anniston,3,19,30,42,0,0,3,2,0,1,1,0,1,3,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",16.8,REPUBLICAN,103558,156620
917,2014,12,ALABAMA,Anniston,3,60,60,60,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,Officer Involved Incident,16.8,REPUBLICAN,103558,156620
952,2014,12,ALABAMA,Anniston,3,48,48,48,0,0,1,0,1,0,1,0,0,1,Shot - Wounded/Injured,NaN,16.8,REPUBLICAN,103558,156620
32801,2015,2,ALABAMA,Anniston,3,28,28,28,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,15.8,REPUBLICAN,103558,156620
32851,2015,3,ALABAMA,Anniston,3,46,52,63,0,0,4,2,2,1,1,1,1,4,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",15.8,REPUBLICAN,103558,156620
32855,2015,3,ALABAMA,Anniston,3,18,20,21,0,0,2,2,0,1,0,1,0,2,"Shot - Dead (murder, accidental, suicide)",NaN,15.8,REPUBLICAN,103558,156620
32919,2015,5,ALABAMA,Anniston,3,32,32,32,0,0,1,1,0,0,1,0,0,1,Shot - Wounded/Injured,NaN,15.8,REPUBLICAN,103558,156620
32920,2015,5,ALABAMA,Anniston,3,<NA>,<NA>,<NA>,0,0,2,<NA>,<NA>,0,1,0,1,2,Shot - Wounded/Injured,NaN,15.8,REPUBLICAN,103558,156620
33000,2015,6,ALABAMA,Anniston,3,59,59,59,0,0,2,<NA>,<NA>,0,2,0,0,2,Shot - Wounded/Injured,NaN,15.8,REPUBLICAN,103558,156620
33001,2015,6,ALABAMA,Anniston,3,18,30,41,0,0,2,<NA>,<NA>,0,2,0,0,2,Shot - Wounded/Injured,NaN,15.8,REPUBLICAN,103558,156620
33178,2015,9,ALABAMA,Anniston,3,<NA>,<NA>,<NA>,0,0,1,<NA>,<NA>,0,1,0,0,1,Shot - Wounded/Injured,NaN,15.8,REPUBLICAN,103558,156620
33224,2015,10,ALABAMA,Anniston,3,34,34,34,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,15.8,REPUBLICAN,103558,156620
33255,2015,10,ALABAMA,Anniston,3,17,17,17,0,1,0,2,0,1,0,0,1,2,"Shot - Dead (murder, accidental, suicide)",NaN,15.8,REPUBLICAN,103558,156620
33346,2015,12,ALABAMA,Anniston,3,27,27,27,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,15.8,REPUBLICAN,103558,156620
71169,2016,1,ALABAMA,Anniston,3,22,26,30,0,0,2,2,0,1,0,1,0,2,"Shot - Dead (murder, accidental, suicide)",Domestic Violence,16.0,REPUBLICAN,192164,287104
71188,2016,1,ALABAMA,Anniston,3,23,29,42,0,0,3,3,0,1,1,1,0,3,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",16.0,REPUBLICAN,192164,287104
71462,2016,4,ALABAMA,Anniston,3,<NA>,<NA>,<NA>,0,0,4,<NA>,<NA>,0,4,0,0,4,Shot - Wounded/Injured,Mass Shooting (4+ victims injured or killed ex...,16.0,REPUBLICAN,192164,287104
71538,2016,5,ALABAMA,Anniston,3,17,17,17,0,1,2,1,0,1,2,0,0,3,Shot - Wounded/Injured,"Shot - Dead (murder, accidental, suicide)",16.0,REPUBLICAN,192164,287104
71613,2016,6,ALABAMA,Anniston,3,43,43,43,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,16.0,REPUBLICAN,192164,287104
71671,2016,6,ALABAMA,Anniston,3,<NA>,<NA>,<NA>,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,16.0,REPUBLICAN,192164,287104
71740,2016,7,ALABAMA,Anniston,3,43,43,43,0,0,1,1,0,1,0,0,0,1,"Shot - Dead (murder, accidental, suicide)",NaN,16.0,REPUBLICAN,192164,287104
71829,2016,8,ALABAMA,Anniston,3,95,72,50,0,0,1,1,0,0,0,0,1,2,Shots Fired - No Injuries,NaN,16.0,REPUBLICAN,192164,287104
71975,2016,9,ALABAMA,Anniston,3,39,39,39,0,0,2,0,2,1,0,0,1,2,"Shot - Dead (murder, accidental, suicide)",NaN,16.0,REPUBLICAN,192164,287104

In [73]:
df = df.drop_duplicates()
print(len(df))

206435

**FEATURE 1**

How many males are involved in the incident w.r.t. the total number of males involved in incidents for the same city and in the same period?

In [74]:
#FEATURE 1

feature1 = df.groupby(['state','city_or_county','congressional_district', 'year', 'month']).apply(
    lambda x: x['n_males'] / x['n_males'].sum()
).reset_index(name='male_participation_rate')

In [155]:
feature1_2 = df.groupby(['state','city_or_county','congressional_district', 'year', 'month']).apply(
    lambda x: x['n_females'] / x['n_females'].sum()
).reset_index(name='female_participation_rate')

In [159]:
print(len(feature1_2))
feature1_2.head(100)

206435

,state,city_or_county,congressional_district,year,month,level_5,female_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,NaN
2,ALABAMA,Adamsville,6,2014,5,542,NaN
3,ALABAMA,Adamsville,6,2014,8,770,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,NaN
5,ALABAMA,Adamsville,6,2016,11,72207,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,NaN
7,ALABAMA,Adamsville,6,2017,3,124158,NaN
8,ALABAMA,Adamsville,6,2017,9,124839,NaN
9,ALABAMA,Adamsville,6,2019,10,190985,NaN
10,ALABAMA,Adamsville,7,2016,1,71215,NaN
11,ALABAMA,Adger,6,2014,9,804,NaN
12,ALABAMA,Adger,6,2017,5,124312,NaN
13,ALABAMA,Adger,6,2017,11,125151,1.0
14,ALABAMA,Alabaster,6,2014,12,964,NaN
15,ALABAMA,Alabaster,6,2016,4,71509,NaN
16,ALABAMA,Alabaster,6,2016,10,72121,1.0
17,ALABAMA,Alberta,7,2017,6,124428,1.0
18,ALABAMA,Albertville,4,2014,1,284,1.0
19,ALABAMA,Albertville,4,2014,4,475,NaN
20,ALABAMA,Albertville,4,2014,6,598,1.0
21,ALABAMA,Albertville,4,2015,1,32744,NaN
22,ALABAMA,Albertville,4,2016,3,71316,NaN
23,ALABAMA,Albertville,4,2016,6,71650,NaN
24,ALABAMA,Albertville,4,2016,7,71774,NaN
25,ALABAMA,Albertville,4,2016,10,72022,1.0
26,ALABAMA,Albertville,4,2016,11,72125,NaN
27,ALABAMA,Albertville,4,2017,4,124271,NaN
28,ALABAMA,Albertville,4,2017,6,124473,NaN
29,ALABAMA,Albertville,4,2017,7,124639,NaN
30,ALABAMA,Albertville,4,2017,11,125109,NaN
31,ALABAMA,Albertville,4,2017,12,125177,NaN
32,ALABAMA,Albertville,4,2017,12,125227,NaN
33,ALABAMA,Albertville,4,2018,2,178499,NaN
34,ALABAMA,Albertville,4,2019,12,191047,NaN
35,ALABAMA,Albertville,4,2020,5,204781,NaN
36,ALABAMA,Alexander City,3,2014,2,375,NaN
37,ALABAMA,Alexander City,3,2014,3,419,NaN
38,ALABAMA,Alexander City,3,2014,5,550,NaN
39,ALABAMA,Alexander City,3,2014,7,699,NaN
40,ALABAMA,Alexander City,3,2014,10,864,NaN
41,ALABAMA,Alexander City,3,2016,4,71508,NaN
42,ALABAMA,Alexander City,3,2016,10,72098,NaN
43,ALABAMA,Alexander City,3,2017,1,123883,NaN
44,ALABAMA,Alexander City,3,2017,1,123896,NaN
45,ALABAMA,Alexander City,3,2017,3,124072,NaN
46,ALABAMA,Alexander City,3,2017,4,124214,NaN
47,ALABAMA,Alexander City,3,2017,4,124268,NaN
48,ALABAMA,Alexander City,3,2017,5,124355,NaN
49,ALABAMA,Alexander City,3,2017,6,124530,NaN
50,ALABAMA,Alexander City,3,2017,7,124666,1.0
51,ALABAMA,Alexander City,3,2017,8,124727,NaN
52,ALABAMA,Alexander City,3,2017,9,124865,NaN
53,ALABAMA,Alexander City,3,2017,12,125184,NaN
54,ALABAMA,Alexander City,3,2017,12,125202,NaN
55,ALABAMA,Alexander City,3,2017,12,125209,NaN
56,ALABAMA,Alexander City,3,2018,2,178539,NaN
57,ALABAMA,Alexander City,3,2018,2,178543,NaN
58,ALABAMA,Alexander City,3,2019,9,190939,NaN
59,ALABAMA,Aliceville,7,2014,9,811,1.0
60,ALABAMA,Aliceville,7,2016,7,71782,NaN
61,ALABAMA,Alpine,3,2017,5,124389,1.0
62,ALABAMA,Alpine,3,2017,11,125045,NaN
63,ALABAMA,Andalusia,2,2014,1,290,NaN
64,ALABAMA,Andalusia,2,2015,7,33061,NaN
65,ALABAMA,Andalusia,2,2016,6,71640,NaN
66,ALABAMA,Andalusia,2,2017,2,124055,NaN
67,ALABAMA,Andalusia,2,2017,6,124443,1.0
68,ALABAMA,Andalusia,2,2018,3,178592,NaN
69,ALABAMA,Andalusia,2,2019,6,190806,NaN
70,ALABAMA,Anderson,5,2019,4,190714,NaN
71,ALABAMA,Anniston,3,2014,1,294,1.0
72,ALABAMA,Anniston,3,2014,5,538,1.0
73,ALABAMA,Anniston,3,2014,6,603,NaN
74,ALABAMA,Anniston,3,2014,7,681,NaN
75,ALABAMA,Anniston,3,2014,7,712,NaN
76,ALABAMA,Anniston,3,2014,7,716,NaN
77,ALABAMA,Anniston,3,2014,12,912,0.0
78,ALABAMA,Anniston,3,2014,12,917,0.0
79,ALABAMA,Anniston,3,2014,12,952,1.0
80,ALABAMA,Anniston,3,2015,2,32801,NaN
81,ALABAMA,Anniston,3,2015,3,32851,1.0
82,ALABAMA,Anniston,3,2015,3,32855,0.0
83,ALABAMA,Anniston,3,2015,5,32919,NaN
84,ALABAMA,Anniston,3,2015,5,32920,NaN
85,ALABAMA,Anniston,3,2015,6,33000,NaN
86,ALABAMA,Anniston,3,2015,6,33001,NaN
87,ALABAMA,Anniston,3,2015,9,33178,NaN
88,ALABAMA,Anniston,3,2015,10,33224,NaN
89,ALABAMA,Anniston,3,2015,10,33255,NaN
90,ALABAMA,Anniston,3,2015,12,33346,NaN
91,ALABAMA,Anniston,3,2016,1,71169,NaN
92,ALABAMA,Anniston,3,2016,1,71188,NaN
93,ALABAMA,Anniston,3,2016,4,71462,NaN
94,ALABAMA,Anniston,3,2016,5,71538,NaN
95,ALABAMA,Anniston,3,2016,6,71613,NaN
96,ALABAMA,Anniston,3,2016,6,71671,NaN
97,ALABAMA,Anniston,3,2016,7,71740,NaN
98,ALABAMA,Anniston,3,2016,8,71829,NaN
99,ALABAMA,Anniston,3,2016,9,71975,1.0

In [89]:
print('NUMBER OF ROWS: '+str(len(feature1)))
feature1.head(10)

NUMBER OF ROWS: 206435

,state,city_or_county,congressional_district,year,month,level_5,male_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0
1,ALABAMA,Abbeville,2,2017,6,124508,1.0
2,ALABAMA,Adamsville,6,2014,5,542,1.0
3,ALABAMA,Adamsville,6,2014,8,770,1.0
4,ALABAMA,Adamsville,6,2016,4,71486,1.0
5,ALABAMA,Adamsville,6,2016,11,72207,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,0.5
7,ALABAMA,Adamsville,6,2017,3,124158,0.5
8,ALABAMA,Adamsville,6,2017,9,124839,1.0
9,ALABAMA,Adamsville,6,2019,10,190985,1.0

In [ ]:
#FEATURE 2: MALES + FEMALES

#feature1 = pd.merge(feature1, feature1_2, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
feature1.head(10)

In [90]:
feature1.to_csv('/content/drive/MyDrive/' + 'feature1.csv', index=False)

In [ ]:
#features = pd.merge(features, feature1, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
#features.head(10)

**FEATURE 2**

How many injured and killed people have been involved w.r.t the total injured and killed people in the same congressional district in a given period of time?

In [91]:
#FEATURE 2

feature2 = df.groupby(['state', 'city_or_county','congressional_district','year','month']).apply(
    lambda x: x['n_killed'] / x['n_killed'].sum()
).reset_index(name='killed_participation_rate')

feature_3 = df.groupby(['state', 'city_or_county','congressional_district','year','month']).apply(
    lambda x: x['n_injured'] / x['n_injured'].sum()
).reset_index(name='injuredd_participation_rate')

In [78]:
#feature2 = feature2.drop(columns='level_5')

In [92]:
#FEATURE 2: KILLED
print(len(feature2))
feature2.head(10)

206435

,state,city_or_county,congressional_district,year,month,level_5,killed_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,1.0
2,ALABAMA,Adamsville,6,2014,5,542,NaN
3,ALABAMA,Adamsville,6,2014,8,770,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,NaN
5,ALABAMA,Adamsville,6,2016,11,72207,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,NaN
7,ALABAMA,Adamsville,6,2017,3,124158,NaN
8,ALABAMA,Adamsville,6,2017,9,124839,1.0
9,ALABAMA,Adamsville,6,2019,10,190985,NaN

In [81]:
#feature_3 = feature_3.drop(columns='level_5')

In [93]:
#FEATURE 2: INJURED
print(len(feature_3))
feature_3.head(10)

206435

,state,city_or_county,congressional_district,year,month,level_5,injuredd_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0
1,ALABAMA,Abbeville,2,2017,6,124508,NaN
2,ALABAMA,Adamsville,6,2014,5,542,1.0
3,ALABAMA,Adamsville,6,2014,8,770,1.0
4,ALABAMA,Adamsville,6,2016,4,71486,1.0
5,ALABAMA,Adamsville,6,2016,11,72207,1.0
6,ALABAMA,Adamsville,6,2017,3,124070,1.0
7,ALABAMA,Adamsville,6,2017,3,124158,0.0
8,ALABAMA,Adamsville,6,2017,9,124839,1.0
9,ALABAMA,Adamsville,6,2019,10,190985,NaN

In [96]:
#FEATURE 2: KILLED + INJURED

feature_2 = pd.merge(feature2, feature_3, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
#feature_2 = feature_2.drop_duplicates()
feature_2.head(10)

,state,city_or_county,congressional_district,year,month,level_5,killed_participation_rate,injuredd_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,NaN,1.0
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,NaN
2,ALABAMA,Adamsville,6,2014,5,542,NaN,1.0
3,ALABAMA,Adamsville,6,2014,8,770,NaN,1.0
4,ALABAMA,Adamsville,6,2016,4,71486,NaN,1.0
5,ALABAMA,Adamsville,6,2016,11,72207,NaN,1.0
6,ALABAMA,Adamsville,6,2017,3,124070,NaN,1.0
7,ALABAMA,Adamsville,6,2017,3,124158,NaN,0.0
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,1.0
9,ALABAMA,Adamsville,6,2019,10,190985,NaN,NaN

In [97]:
print(len(feature_2))

206435

In [98]:
feature_2.to_csv('/content/drive/MyDrive/' + 'feature2.csv', index=False)

In [119]:
#FEATURE 1 + FEATURE 2
feature_dataset = pd.merge(feature1, feature_2, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
#features = features.drop(columns='level_5')
feature_dataset = feature_dataset.drop_duplicates()

In [121]:
print(len(feature_dataset))
feature_dataset.head(10)

206435

,state,city_or_county,congressional_district,year,month,level_5,male_participation_rate,killed_participation_rate,injuredd_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0,NaN,1.0
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,1.0,NaN
2,ALABAMA,Adamsville,6,2014,5,542,1.0,NaN,1.0
3,ALABAMA,Adamsville,6,2014,8,770,1.0,NaN,1.0
4,ALABAMA,Adamsville,6,2016,4,71486,1.0,NaN,1.0
5,ALABAMA,Adamsville,6,2016,11,72207,NaN,NaN,1.0
6,ALABAMA,Adamsville,6,2017,3,124070,0.5,NaN,1.0
7,ALABAMA,Adamsville,6,2017,3,124158,0.5,NaN,0.0
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,1.0,1.0
9,ALABAMA,Adamsville,6,2019,10,190985,1.0,NaN,NaN

**FEATURE 3**

Ratio of the number of the killed people in the incident w.r.t. the number of participants in the incident: it is an indicator if the incidents that occur cause killings

In [103]:
feature3 = df.groupby(['state','city_or_county','congressional_district', 'year', 'month']).apply(
    lambda x: x['n_killed'] / x['n_participants']
).reset_index(name='killed/participants_rate')

In [104]:
print(len(feature3))

206435

In [122]:
#feature3 = feature3.drop(columns='level_5')
feature3.head(10)

,state,city_or_county,congressional_district,year,month,level_5,killed/participants_rate
0,ALABAMA,Abbeville,2,2016,2,71245,0.000000
1,ALABAMA,Abbeville,2,2017,6,124508,1.000000
2,ALABAMA,Adamsville,6,2014,5,542,0.000000
3,ALABAMA,Adamsville,6,2014,8,770,0.000000
4,ALABAMA,Adamsville,6,2016,4,71486,0.000000
5,ALABAMA,Adamsville,6,2016,11,72207,0.000000
6,ALABAMA,Adamsville,6,2017,3,124070,0.000000
7,ALABAMA,Adamsville,6,2017,3,124158,0.000000
8,ALABAMA,Adamsville,6,2017,9,124839,0.333333
9,ALABAMA,Adamsville,6,2019,10,190985,0.000000

In [106]:
feature3.to_csv('/content/drive/MyDrive/' + 'feature3.csv', index=False)

In [123]:
#FEATURE 1 + 2 + 3

features = pd.merge(feature_dataset, feature3, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
features = features.drop_duplicates()

In [124]:
print(len(features))

206435

In [125]:
features.head(10)

,state,city_or_county,congressional_district,year,month,level_5,male_participation_rate,killed_participation_rate,injuredd_participation_rate,killed/participants_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0,NaN,1.0,0.000000
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,1.0,NaN,1.000000
2,ALABAMA,Adamsville,6,2014,5,542,1.0,NaN,1.0,0.000000
3,ALABAMA,Adamsville,6,2014,8,770,1.0,NaN,1.0,0.000000
4,ALABAMA,Adamsville,6,2016,4,71486,1.0,NaN,1.0,0.000000
5,ALABAMA,Adamsville,6,2016,11,72207,NaN,NaN,1.0,0.000000
6,ALABAMA,Adamsville,6,2017,3,124070,0.5,NaN,1.0,0.000000
7,ALABAMA,Adamsville,6,2017,3,124158,0.5,NaN,0.0,0.000000
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,1.0,1.0,0.333333
9,ALABAMA,Adamsville,6,2019,10,190985,1.0,NaN,NaN,0.000000

**FEATURE 4**

Ratio of unharmed people in the incident w.r.t. the average of unharmed people involved in incidents for the same period

In [110]:
feature4 = df.groupby(['state','city_or_county','congressional_district', 'year', 'month']).apply(
    lambda x: x['n_unharmed'] / x['n_unharmed'].mean()
).reset_index(name='unharmed_rate')

In [126]:
feature4.head(10)

,state,city_or_county,congressional_district,year,month,level_5,unharmed_rate
0,ALABAMA,Abbeville,2,2016,2,71245,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,NaN
2,ALABAMA,Adamsville,6,2014,5,542,NaN
3,ALABAMA,Adamsville,6,2014,8,770,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,1.0
5,ALABAMA,Adamsville,6,2016,11,72207,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,NaN
7,ALABAMA,Adamsville,6,2017,3,124158,NaN
8,ALABAMA,Adamsville,6,2017,9,124839,1.0
9,ALABAMA,Adamsville,6,2019,10,190985,1.0

In [127]:
feature4.to_csv('/content/drive/MyDrive/' + 'feature4.csv', index=False)

In [128]:
features = pd.merge(features, feature4, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
features = features.drop_duplicates()

In [131]:
print(len(features))

206435

In [130]:
#FEATURE 1 + 2 + 3 + 4
features.head(10)

,state,city_or_county,congressional_district,year,month,level_5,male_participation_rate,killed_participation_rate,injuredd_participation_rate,killed/participants_rate,unharmed_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0,NaN,1.0,0.000000,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,1.0,NaN,1.000000,NaN
2,ALABAMA,Adamsville,6,2014,5,542,1.0,NaN,1.0,0.000000,NaN
3,ALABAMA,Adamsville,6,2014,8,770,1.0,NaN,1.0,0.000000,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,1.0,NaN,1.0,0.000000,1.0
5,ALABAMA,Adamsville,6,2016,11,72207,NaN,NaN,1.0,0.000000,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,0.5,NaN,1.0,0.000000,NaN
7,ALABAMA,Adamsville,6,2017,3,124158,0.5,NaN,0.0,0.000000,NaN
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,1.0,1.0,0.333333,1.0
9,ALABAMA,Adamsville,6,2019,10,190985,1.0,NaN,NaN,0.000000,1.0

FEATURE 5

How many adult/teen/child participants are involved w.r.t. to the total number of adults, teens and childs involved in incidents for the same city and in the same period

In [132]:
feature5_adults = df.groupby(['state', 'city_or_county','congressional_district','year','month']).apply(
    lambda x: x['n_participants_adult'] / x['n_participants_adult'].sum()
).reset_index(name='adult_participation_rate')

feature5_teens = df.groupby(['state', 'city_or_county','congressional_district','year','month']).apply(
    lambda x: x['n_participants_teen'] / x['n_participants_teen'].sum()
).reset_index(name='teen_participation_rate')

feature5_childs = df.groupby(['state', 'city_or_county','congressional_district','year','month']).apply(
    lambda x: x['n_participants_child'] / x['n_participants_child'].sum()
).reset_index(name='child_participation_rate')

In [133]:
feature5_adults.head(10)

,state,city_or_county,congressional_district,year,month,level_5,adult_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0
1,ALABAMA,Abbeville,2,2017,6,124508,1.0
2,ALABAMA,Adamsville,6,2014,5,542,1.0
3,ALABAMA,Adamsville,6,2014,8,770,1.0
4,ALABAMA,Adamsville,6,2016,4,71486,1.0
5,ALABAMA,Adamsville,6,2016,11,72207,1.0
6,ALABAMA,Adamsville,6,2017,3,124070,0.5
7,ALABAMA,Adamsville,6,2017,3,124158,0.5
8,ALABAMA,Adamsville,6,2017,9,124839,1.0
9,ALABAMA,Adamsville,6,2019,10,190985,1.0

In [134]:
feature5_teens.head(10)

,state,city_or_county,congressional_district,year,month,level_5,teen_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,NaN
2,ALABAMA,Adamsville,6,2014,5,542,NaN
3,ALABAMA,Adamsville,6,2014,8,770,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,NaN
5,ALABAMA,Adamsville,6,2016,11,72207,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,NaN
7,ALABAMA,Adamsville,6,2017,3,124158,NaN
8,ALABAMA,Adamsville,6,2017,9,124839,NaN
9,ALABAMA,Adamsville,6,2019,10,190985,NaN

In [135]:
feature5_childs.head(10)

,state,city_or_county,congressional_district,year,month,level_5,child_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,NaN
2,ALABAMA,Adamsville,6,2014,5,542,NaN
3,ALABAMA,Adamsville,6,2014,8,770,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,NaN
5,ALABAMA,Adamsville,6,2016,11,72207,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,NaN
7,ALABAMA,Adamsville,6,2017,3,124158,NaN
8,ALABAMA,Adamsville,6,2017,9,124839,NaN
9,ALABAMA,Adamsville,6,2019,10,190985,NaN

In [136]:
feature5 = pd.merge(feature5_adults, feature5_teens, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
feature5 = feature5.drop_duplicates()

In [137]:
feature5 = pd.merge(feature5, feature5_childs, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
feature5 = feature5.drop_duplicates()

In [138]:
feature5.head(10)

,state,city_or_county,congressional_district,year,month,level_5,adult_participation_rate,teen_participation_rate,child_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0,NaN,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,NaN,NaN
2,ALABAMA,Adamsville,6,2014,5,542,1.0,NaN,NaN
3,ALABAMA,Adamsville,6,2014,8,770,1.0,NaN,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,1.0,NaN,NaN
5,ALABAMA,Adamsville,6,2016,11,72207,1.0,NaN,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,0.5,NaN,NaN
7,ALABAMA,Adamsville,6,2017,3,124158,0.5,NaN,NaN
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,NaN,NaN
9,ALABAMA,Adamsville,6,2019,10,190985,1.0,NaN,NaN

In [139]:
feature5.to_csv('/content/drive/MyDrive/' + 'feature5.csv', index=False)

In [140]:
print(len(feature5))

206435

In [141]:
features = pd.merge(features, feature5, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
features = features.drop_duplicates()

In [144]:
features.head(10)

,state,city_or_county,congressional_district,year,month,level_5,male_participation_rate,killed_participation_rate,injuredd_participation_rate,killed/participants_rate,unharmed_rate,adult_participation_rate,teen_participation_rate,child_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,1.0,NaN,1.000000,NaN,1.0,NaN,NaN
2,ALABAMA,Adamsville,6,2014,5,542,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN
3,ALABAMA,Adamsville,6,2014,8,770,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,1.0,NaN,1.0,0.000000,1.0,1.0,NaN,NaN
5,ALABAMA,Adamsville,6,2016,11,72207,NaN,NaN,1.0,0.000000,NaN,1.0,NaN,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,0.5,NaN,1.0,0.000000,NaN,0.5,NaN,NaN
7,ALABAMA,Adamsville,6,2017,3,124158,0.5,NaN,0.0,0.000000,NaN,0.5,NaN,NaN
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,1.0,1.0,0.333333,1.0,1.0,NaN,NaN
9,ALABAMA,Adamsville,6,2019,10,190985,1.0,NaN,NaN,0.000000,1.0,1.0,NaN,NaN

In [143]:
features.to_csv('/content/drive/MyDrive/' + 'feature_dataset.csv', index=False)

FEATURE 6

In [149]:
feature6 = df.groupby(['state', 'city_or_county','congressional_district','year','month']).apply(
    lambda x: x['n_arrested'] / x['n_arrested'].sum()
).reset_index(name='arrested_participation_rate')

In [150]:
print(len(feature6))
feature6.head(10)

206435

,state,city_or_county,congressional_district,year,month,level_5,arrested_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,NaN
2,ALABAMA,Adamsville,6,2014,5,542,NaN
3,ALABAMA,Adamsville,6,2014,8,770,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,NaN
5,ALABAMA,Adamsville,6,2016,11,72207,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,0.0
7,ALABAMA,Adamsville,6,2017,3,124158,1.0
8,ALABAMA,Adamsville,6,2017,9,124839,NaN
9,ALABAMA,Adamsville,6,2019,10,190985,NaN

In [152]:
feature6.to_csv('/content/drive/MyDrive/' + 'feature6.csv', index=False)

In [153]:
features = pd.merge(features, feature6, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
features = features.drop_duplicates()

In [154]:
features.head(10)

,state,city_or_county,congressional_district,year,month,level_5,male_participation_rate,killed_participation_rate,injuredd_participation_rate,killed/participants_rate,unharmed_rate,adult_participation_rate,teen_participation_rate,child_participation_rate,arrested_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,1.0,NaN,1.000000,NaN,1.0,NaN,NaN,NaN
2,ALABAMA,Adamsville,6,2014,5,542,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN
3,ALABAMA,Adamsville,6,2014,8,770,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,1.0,NaN,1.0,0.000000,1.0,1.0,NaN,NaN,NaN
5,ALABAMA,Adamsville,6,2016,11,72207,NaN,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,0.5,NaN,1.0,0.000000,NaN,0.5,NaN,NaN,0.0
7,ALABAMA,Adamsville,6,2017,3,124158,0.5,NaN,0.0,0.000000,NaN,0.5,NaN,NaN,1.0
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,1.0,1.0,0.333333,1.0,1.0,NaN,NaN,NaN
9,ALABAMA,Adamsville,6,2019,10,190985,1.0,NaN,NaN,0.000000,1.0,1.0,NaN,NaN,NaN

In [160]:
#DA SPOSTARE IN FEATURE 1
features = pd.merge(features, feature1_2, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
features.head(10)

,state,city_or_county,congressional_district,year,month,level_5,male_participation_rate,killed_participation_rate,injuredd_participation_rate,killed/participants_rate,unharmed_rate,adult_participation_rate,teen_participation_rate,child_participation_rate,arrested_participation_rate,female_participation_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,1.0,NaN,1.000000,NaN,1.0,NaN,NaN,NaN,NaN
2,ALABAMA,Adamsville,6,2014,5,542,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN
3,ALABAMA,Adamsville,6,2014,8,770,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN
4,ALABAMA,Adamsville,6,2016,4,71486,1.0,NaN,1.0,0.000000,1.0,1.0,NaN,NaN,NaN,NaN
5,ALABAMA,Adamsville,6,2016,11,72207,NaN,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN
6,ALABAMA,Adamsville,6,2017,3,124070,0.5,NaN,1.0,0.000000,NaN,0.5,NaN,NaN,0.0,NaN
7,ALABAMA,Adamsville,6,2017,3,124158,0.5,NaN,0.0,0.000000,NaN,0.5,NaN,NaN,1.0,NaN
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,1.0,1.0,0.333333,1.0,1.0,NaN,NaN,NaN,NaN
9,ALABAMA,Adamsville,6,2019,10,190985,1.0,NaN,NaN,0.000000,1.0,1.0,NaN,NaN,NaN,NaN

FEATURE 7

Ratio of the number of the arrested people in the incident w.r.t. the number of participants in the incident

In [161]:
feature7 = df.groupby(['state','city_or_county','congressional_district', 'year', 'month']).apply(
    lambda x: x['n_arrested'] / x['n_participants']
).reset_index(name='arrested/participants_rate')

In [162]:
print(len(feature7))
feature7.head(10)

206435

,state,city_or_county,congressional_district,year,month,level_5,arrested/participants_rate
0,ALABAMA,Abbeville,2,2016,2,71245,0.0
1,ALABAMA,Abbeville,2,2017,6,124508,0.0
2,ALABAMA,Adamsville,6,2014,5,542,0.0
3,ALABAMA,Adamsville,6,2014,8,770,0.0
4,ALABAMA,Adamsville,6,2016,4,71486,0.0
5,ALABAMA,Adamsville,6,2016,11,72207,0.0
6,ALABAMA,Adamsville,6,2017,3,124070,0.0
7,ALABAMA,Adamsville,6,2017,3,124158,1.0
8,ALABAMA,Adamsville,6,2017,9,124839,0.0
9,ALABAMA,Adamsville,6,2019,10,190985,0.0

In [163]:
feature7.to_csv('/content/drive/MyDrive/' + 'feature7.csv', index=False)

In [164]:
features = pd.merge(features, feature7, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
features = features.drop_duplicates()

In [165]:
features.head(10)

,state,city_or_county,congressional_district,year,month,level_5,male_participation_rate,killed_participation_rate,injuredd_participation_rate,killed/participants_rate,unharmed_rate,adult_participation_rate,teen_participation_rate,child_participation_rate,arrested_participation_rate,female_participation_rate,arrested/participants_rate
0,ALABAMA,Abbeville,2,2016,2,71245,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,1.0,NaN,1.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0
2,ALABAMA,Adamsville,6,2014,5,542,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0
3,ALABAMA,Adamsville,6,2014,8,770,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0
4,ALABAMA,Adamsville,6,2016,4,71486,1.0,NaN,1.0,0.000000,1.0,1.0,NaN,NaN,NaN,NaN,0.0
5,ALABAMA,Adamsville,6,2016,11,72207,NaN,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0
6,ALABAMA,Adamsville,6,2017,3,124070,0.5,NaN,1.0,0.000000,NaN,0.5,NaN,NaN,0.0,NaN,0.0
7,ALABAMA,Adamsville,6,2017,3,124158,0.5,NaN,0.0,0.000000,NaN,0.5,NaN,NaN,1.0,NaN,1.0
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,1.0,1.0,0.333333,1.0,1.0,NaN,NaN,NaN,NaN,0.0
9,ALABAMA,Adamsville,6,2019,10,190985,1.0,NaN,NaN,0.000000,1.0,1.0,NaN,NaN,NaN,NaN,0.0

FEATURE 8

PERCENTAGE OF VOTES OBTAINED BY THE WINNER PARTY CANDIDATE

In [192]:
feature8 = df.groupby(['state','city_or_county','congressional_district', 'year', 'month','party']).apply(
    lambda x: x['candidatevotes'] / x['totalvotes']
).reset_index(name='winnerParty_votes_percentage')

In [195]:
print(len(feature8))
feature8.head(10)

200386

,state,city_or_county,congressional_district,year,month,party,level_5,winnerParty_votes_percentage
0,ALABAMA,Abbeville,2,2016,2,REPUBLICAN,71245,0.487685
1,ALABAMA,Abbeville,2,2017,6,REPUBLICAN,124508,0.487685
2,ALABAMA,Adamsville,6,2014,5,REPUBLICAN,542,0.761814
3,ALABAMA,Adamsville,6,2014,8,REPUBLICAN,770,0.761814
4,ALABAMA,Adamsville,6,2016,4,REPUBLICAN,71486,0.744939
5,ALABAMA,Adamsville,6,2016,11,REPUBLICAN,72207,0.744939
6,ALABAMA,Adamsville,6,2017,3,REPUBLICAN,124070,0.744939
7,ALABAMA,Adamsville,6,2017,3,REPUBLICAN,124158,0.744939
8,ALABAMA,Adamsville,6,2017,9,REPUBLICAN,124839,0.744939
9,ALABAMA,Adamsville,6,2019,10,REPUBLICAN,190985,0.691781

In [194]:
feature8.rename(columns={'level_6': 'level_5'}, inplace=True)

In [182]:
feature8.to_csv('/content/drive/MyDrive/' + 'feature8.csv', index=False)

In [199]:
features = pd.merge(features, feature8, on=['state', 'city_or_county','congressional_district','year','month','level_5'], how='left')
features = features.drop_duplicates()

In [250]:
features.head(10)

,state,city_or_county,congressional_district,year,month,level_5,male_participation_rate,killed_participation_rate,injuredd_participation_rate,killed/participants_rate,unharmed_rate,adult_participation_rate,teen_participation_rate,child_participation_rate,arrested_participation_rate,female_participation_rate,arrested/participants_rate,party,winnerParty_votes_percentage
0,ALABAMA,Abbeville,2,2016,2,71245,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0,REPUBLICAN,0.487685
1,ALABAMA,Abbeville,2,2017,6,124508,1.0,1.0,NaN,1.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0,REPUBLICAN,0.487685
2,ALABAMA,Adamsville,6,2014,5,542,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0,REPUBLICAN,0.761814
3,ALABAMA,Adamsville,6,2014,8,770,1.0,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0,REPUBLICAN,0.761814
4,ALABAMA,Adamsville,6,2016,4,71486,1.0,NaN,1.0,0.000000,1.0,1.0,NaN,NaN,NaN,NaN,0.0,REPUBLICAN,0.744939
5,ALABAMA,Adamsville,6,2016,11,72207,NaN,NaN,1.0,0.000000,NaN,1.0,NaN,NaN,NaN,NaN,0.0,REPUBLICAN,0.744939
6,ALABAMA,Adamsville,6,2017,3,124070,0.5,NaN,1.0,0.000000,NaN,0.5,NaN,NaN,0.0,NaN,0.0,REPUBLICAN,0.744939
7,ALABAMA,Adamsville,6,2017,3,124158,0.5,NaN,0.0,0.000000,NaN,0.5,NaN,NaN,1.0,NaN,1.0,REPUBLICAN,0.744939
8,ALABAMA,Adamsville,6,2017,9,124839,1.0,1.0,1.0,0.333333,1.0,1.0,NaN,NaN,NaN,NaN,0.0,REPUBLICAN,0.744939
9,ALABAMA,Adamsville,6,2019,10,190985,1.0,NaN,NaN,0.000000,1.0,1.0,NaN,NaN,NaN,NaN,0.0,REPUBLICAN,0.691781

In [252]:
features.to_csv('/content/drive/MyDrive/' + 'feature_dataset.csv', index=False)

FEATURE 9

Variation of the poverty percentage w.r.t a state and the previous year